export declare const findUserById: (userId: string) => Promise<{
    createdAt: Date | null;
    id: string;
    firstName: string;
    lastName: string;
    isRegistered: boolean;
    expirationDate: string;
    createdAt2: string;
    twoFactorEnabled: boolean | null;
    email: string;
    emailVerified: boolean;
    image: string | null;
    banned: boolean | null;
    banReason: string | null;
    banExpires: Date | null;
    updatedAt: Date;
    role: string;
    enablePaidFeatures: boolean;
    allowImpersonation: boolean;
    enableEnterpriseFeatures: boolean;
    licenseKey: string | null;
    isValidEnterpriseLicense: boolean;
    stripeCustomerId: string | null;
    stripeSubscriptionId: string | null;
    serversQuantity: number;
    sendInvoiceNotifications: boolean;
    isEnterpriseCloud: boolean;
    trustedOrigins: string[] | null;
    bookmarkedTemplates: string[] | null;
}>;
export declare const findOrganizationById: (organizationId: string) => Promise<{
    name: string;
    createdAt: Date;
    id: string;
    slug: string | null;
    logo: string | null;
    metadata: string | null;
    ownerId: string;
    owner: {
        createdAt: Date | null;
        id: string;
        firstName: string;
        lastName: string;
        isRegistered: boolean;
        expirationDate: string;
        createdAt2: string;
        twoFactorEnabled: boolean | null;
        email: string;
        emailVerified: boolean;
        image: string | null;
        banned: boolean | null;
        banReason: string | null;
        banExpires: Date | null;
        updatedAt: Date;
        role: string;
        enablePaidFeatures: boolean;
        allowImpersonation: boolean;
        enableEnterpriseFeatures: boolean;
        licenseKey: string | null;
        isValidEnterpriseLicense: boolean;
        stripeCustomerId: string | null;
        stripeSubscriptionId: string | null;
        serversQuantity: number;
        sendInvoiceNotifications: boolean;
        isEnterpriseCloud: boolean;
        trustedOrigins: string[] | null;
        bookmarkedTemplates: string[] | null;
    };
} | undefined>;
export declare const isAdminPresent: () => Promise<boolean>;
export declare const findOwner: () => Promise<{
    createdAt: Date;
    organizationId: string;
    id: string;
    role: "admin" | "owner" | "member" | (string & {});
    userId: string;
    isDefault: boolean;
    teamId: string | null;
    canCreateProjects: boolean;
    canAccessToSSHKeys: boolean;
    canCreateServices: boolean;
    canDeleteProjects: boolean;
    canDeleteServices: boolean;
    canAccessToDocker: boolean;
    canAccessToAPI: boolean;
    canAccessToGitProviders: boolean;
    canAccessToTraefikFiles: boolean;
    canDeleteEnvironments: boolean;
    canCreateEnvironments: boolean;
    accessedProjects: string[];
    accessedEnvironments: string[];
    accessedServices: string[];
    accessedGitProviders: string[];
    accessedServers: string[];
    user: {
        createdAt: Date | null;
        id: string;
        firstName: string;
        lastName: string;
        isRegistered: boolean;
        expirationDate: string;
        createdAt2: string;
        twoFactorEnabled: boolean | null;
        email: string;
        emailVerified: boolean;
        image: string | null;
        banned: boolean | null;
        banReason: string | null;
        banExpires: Date | null;
        updatedAt: Date;
        role: string;
        enablePaidFeatures: boolean;
        allowImpersonation: boolean;
        enableEnterpriseFeatures: boolean;
        licenseKey: string | null;
        isValidEnterpriseLicense: boolean;
        stripeCustomerId: string | null;
        stripeSubscriptionId: string | null;
        serversQuantity: number;
        sendInvoiceNotifications: boolean;
        isEnterpriseCloud: boolean;
        trustedOrigins: string[] | null;
        bookmarkedTemplates: string[] | null;
    };
}>;
export declare const getUserByToken: (token: string) => Promise<{
    isExpired: boolean;
    userAlreadyExists: boolean;
    id: string;
    email: string;
    role: "admin" | "owner" | "member" | (string & {}) | null;
    status: string;
    inviterId: string;
}>;
export declare const removeUserById: (userId: string) => Promise<void>;
export declare const getDokployUrl: () => Promise<string>;
export declare const getTrustedOrigins: () => Promise<string[]>;
export declare const getTrustedProviders: () => Promise<string[]>;
//# sourceMappingURL=admin.d.ts.map