import { type apiCreateApplication, applications } from "@undevops/server/db/schema";
import type { z } from "zod";
export type Application = typeof applications.$inferSelect;
export declare const createApplication: (input: z.infer<typeof apiCreateApplication>) => Promise<{
    applicationStatus: "idle" | "running" | "done" | "error";
    triggerType: "push" | "tag" | null;
    giteaId: string | null;
    name: string;
    createdAt: string;
    refreshToken: string | null;
    description: string | null;
    owner: string | null;
    githubId: string | null;
    gitlabId: string | null;
    applicationId: string;
    appName: string;
    env: string | null;
    sourceType: "gitea" | "github" | "gitlab" | "bitbucket" | "git" | "docker" | "drop";
    repository: string | null;
    branch: string | null;
    autoDeploy: boolean | null;
    gitlabProjectId: number | null;
    gitlabRepository: string | null;
    gitlabOwner: string | null;
    gitlabBranch: string | null;
    gitlabPathNamespace: string | null;
    bitbucketRepository: string | null;
    bitbucketRepositorySlug: string | null;
    bitbucketOwner: string | null;
    bitbucketBranch: string | null;
    giteaRepository: string | null;
    giteaOwner: string | null;
    giteaBranch: string | null;
    customGitUrl: string | null;
    customGitBranch: string | null;
    customGitSSHKeyId: string | null;
    command: string | null;
    enableSubmodules: boolean;
    environmentId: string;
    watchPaths: string[] | null;
    bitbucketId: string | null;
    serverId: string | null;
    username: string | null;
    previewEnv: string | null;
    previewBuildArgs: string | null;
    previewBuildSecrets: string | null;
    previewLabels: string[] | null;
    previewWildcard: string | null;
    previewPort: number | null;
    previewHttps: boolean;
    previewPath: string | null;
    previewCertificateType: "letsencrypt" | "none" | "custom";
    previewCustomCertResolver: string | null;
    previewLimit: number | null;
    isPreviewDeploymentsActive: boolean | null;
    previewRequireCollaboratorPermissions: boolean | null;
    rollbackActive: boolean | null;
    buildArgs: string | null;
    buildSecrets: string | null;
    memoryReservation: string | null;
    memoryLimit: string | null;
    cpuReservation: string | null;
    cpuLimit: string | null;
    title: string | null;
    enabled: boolean | null;
    subtitle: string | null;
    args: string[] | null;
    icon: string | null;
    cleanCache: boolean | null;
    buildPath: string | null;
    gitlabBuildPath: string | null;
    giteaBuildPath: string | null;
    bitbucketBuildPath: string | null;
    password: string | null;
    dockerImage: string | null;
    registryUrl: string | null;
    customGitBuildPath: string | null;
    dockerfile: string | null;
    dockerContextPath: string | null;
    dockerBuildStage: string | null;
    dropBuildPath: string | null;
    healthCheckSwarm: import("@undevops/server/db").HealthCheckSwarm | null;
    restartPolicySwarm: import("@undevops/server/db").RestartPolicySwarm | null;
    placementSwarm: import("@undevops/server/db").PlacementSwarm | null;
    updateConfigSwarm: import("@undevops/server/db").UpdateConfigSwarm | null;
    rollbackConfigSwarm: import("@undevops/server/db").UpdateConfigSwarm | null;
    modeSwarm: import("@undevops/server/db").ServiceModeSwarm | null;
    labelsSwarm: import("@undevops/server/db").LabelsSwarm | null;
    networkSwarm: import("@undevops/server/db").NetworkSwarm[] | null;
    stopGracePeriodSwarm: number | null;
    endpointSpecSwarm: import("@undevops/server/db").EndpointSpecSwarm | null;
    ulimitsSwarm: import("@undevops/server/db").UlimitsSwarm | null;
    replicas: number;
    buildType: "dockerfile" | "heroku_buildpacks" | "paketo_buildpacks" | "nixpacks" | "static" | "railpack";
    railpackVersion: string | null;
    herokuVersion: string | null;
    publishDirectory: string | null;
    isStaticSpa: boolean | null;
    createEnvFile: boolean;
    registryId: string | null;
    rollbackRegistryId: string | null;
    buildServerId: string | null;
    buildRegistryId: string | null;
}>;
export declare const findApplicationById: (applicationId: string) => Promise<{
    applicationStatus: "idle" | "running" | "done" | "error";
    triggerType: "push" | "tag" | null;
    giteaId: string | null;
    name: string;
    createdAt: string;
    refreshToken: string | null;
    description: string | null;
    owner: string | null;
    githubId: string | null;
    gitlabId: string | null;
    applicationId: string;
    appName: string;
    env: string | null;
    sourceType: "gitea" | "github" | "gitlab" | "bitbucket" | "git" | "docker" | "drop";
    repository: string | null;
    branch: string | null;
    autoDeploy: boolean | null;
    gitlabProjectId: number | null;
    gitlabRepository: string | null;
    gitlabOwner: string | null;
    gitlabBranch: string | null;
    gitlabPathNamespace: string | null;
    bitbucketRepository: string | null;
    bitbucketRepositorySlug: string | null;
    bitbucketOwner: string | null;
    bitbucketBranch: string | null;
    giteaRepository: string | null;
    giteaOwner: string | null;
    giteaBranch: string | null;
    customGitUrl: string | null;
    customGitBranch: string | null;
    customGitSSHKeyId: string | null;
    command: string | null;
    enableSubmodules: boolean;
    environmentId: string;
    watchPaths: string[] | null;
    bitbucketId: string | null;
    serverId: string | null;
    username: string | null;
    previewEnv: string | null;
    previewBuildArgs: string | null;
    previewBuildSecrets: string | null;
    previewLabels: string[] | null;
    previewWildcard: string | null;
    previewPort: number | null;
    previewHttps: boolean;
    previewPath: string | null;
    previewCertificateType: "letsencrypt" | "none" | "custom";
    previewCustomCertResolver: string | null;
    previewLimit: number | null;
    isPreviewDeploymentsActive: boolean | null;
    previewRequireCollaboratorPermissions: boolean | null;
    rollbackActive: boolean | null;
    buildArgs: string | null;
    buildSecrets: string | null;
    memoryReservation: string | null;
    memoryLimit: string | null;
    cpuReservation: string | null;
    cpuLimit: string | null;
    title: string | null;
    enabled: boolean | null;
    subtitle: string | null;
    args: string[] | null;
    icon: string | null;
    cleanCache: boolean | null;
    buildPath: string | null;
    gitlabBuildPath: string | null;
    giteaBuildPath: string | null;
    bitbucketBuildPath: string | null;
    password: string | null;
    dockerImage: string | null;
    registryUrl: string | null;
    customGitBuildPath: string | null;
    dockerfile: string | null;
    dockerContextPath: string | null;
    dockerBuildStage: string | null;
    dropBuildPath: string | null;
    healthCheckSwarm: import("@undevops/server/db").HealthCheckSwarm | null;
    restartPolicySwarm: import("@undevops/server/db").RestartPolicySwarm | null;
    placementSwarm: import("@undevops/server/db").PlacementSwarm | null;
    updateConfigSwarm: import("@undevops/server/db").UpdateConfigSwarm | null;
    rollbackConfigSwarm: import("@undevops/server/db").UpdateConfigSwarm | null;
    modeSwarm: import("@undevops/server/db").ServiceModeSwarm | null;
    labelsSwarm: import("@undevops/server/db").LabelsSwarm | null;
    networkSwarm: import("@undevops/server/db").NetworkSwarm[] | null;
    stopGracePeriodSwarm: number | null;
    endpointSpecSwarm: import("@undevops/server/db").EndpointSpecSwarm | null;
    ulimitsSwarm: import("@undevops/server/db").UlimitsSwarm | null;
    replicas: number;
    buildType: "dockerfile" | "heroku_buildpacks" | "paketo_buildpacks" | "nixpacks" | "static" | "railpack";
    railpackVersion: string | null;
    herokuVersion: string | null;
    publishDirectory: string | null;
    isStaticSpa: boolean | null;
    createEnvFile: boolean;
    registryId: string | null;
    rollbackRegistryId: string | null;
    buildServerId: string | null;
    buildRegistryId: string | null;
    environment: {
        name: string;
        createdAt: string;
        description: string | null;
        env: string;
        environmentId: string;
        projectId: string;
        isDefault: boolean;
        gatePolicy: "disabled" | "single" | "unanimous" | "manual_only";
        reviewerIds: string[];
        autoApproveAgents: boolean;
        project: {
            name: string;
            createdAt: string;
            organizationId: string;
            description: string | null;
            env: string;
            projectId: string;
        };
    };
    gitea: {
        giteaId: string;
        giteaUrl: string;
        giteaInternalUrl: string | null;
        redirectUri: string | null;
        clientId: string | null;
        clientSecret: string | null;
        gitProviderId: string;
        accessToken: string | null;
        refreshToken: string | null;
        expiresAt: number | null;
        scopes: string | null;
        lastAuthenticatedAt: number | null;
    } | null;
    github: {
        gitProviderId: string;
        githubId: string;
        githubAppName: string | null;
        githubAppId: number | null;
        githubClientId: string | null;
        githubClientSecret: string | null;
        githubInstallationId: string | null;
        githubPrivateKey: string | null;
        githubWebhookSecret: string | null;
    } | null;
    gitlab: {
        redirectUri: string | null;
        gitProviderId: string;
        accessToken: string | null;
        refreshToken: string | null;
        expiresAt: number | null;
        gitlabId: string;
        gitlabUrl: string;
        gitlabInternalUrl: string | null;
        applicationId: string | null;
        secret: string | null;
        groupName: string | null;
    } | null;
    bitbucket: {
        gitProviderId: string;
        bitbucketId: string;
        bitbucketUsername: string | null;
        bitbucketEmail: string | null;
        appPassword: string | null;
        apiToken: string | null;
        bitbucketWorkspaceName: string | null;
    } | null;
    server: {
        name: string;
        createdAt: string;
        organizationId: string;
        description: string | null;
        port: number;
        appName: string;
        sshKeyId: string | null;
        command: string;
        serverId: string;
        ipAddress: string;
        username: string;
        enableDockerCleanup: boolean;
        serverStatus: "active" | "inactive";
        serverType: "deploy" | "build";
        metricsConfig: {
            server: {
                type: "Dokploy" | "Remote";
                refreshRate: number;
                port: number;
                token: string;
                urlCallback: string;
                retentionDays: number;
                cronJob: string;
                thresholds: {
                    cpu: number;
                    memory: number;
                };
            };
            containers: {
                refreshRate: number;
                services: {
                    include: string[];
                    exclude: string[];
                };
            };
        };
    } | null;
    registry: {
        createdAt: string;
        organizationId: string;
        username: string;
        password: string;
        registryUrl: string;
        registryId: string;
        registryName: string;
        imagePrefix: string | null;
        registryType: "selfHosted" | "cloud";
    } | null;
    deployments: {
        createdAt: string;
        description: string | null;
        applicationId: string | null;
        composeId: string | null;
        serverId: string | null;
        title: string;
        buildServerId: string | null;
        previewDeploymentId: string | null;
        status: "running" | "done" | "error" | "cancelled" | null;
        deploymentId: string;
        logPath: string;
        pid: string | null;
        isPreviewDeployment: boolean | null;
        startedAt: string | null;
        finishedAt: string | null;
        errorMessage: string | null;
        scheduleId: string | null;
        backupId: string | null;
        rollbackId: string | null;
        volumeBackupId: string | null;
        initiatingActorType: "human" | "agent" | "plugin" | "system";
        initiatingActorId: string | null;
        gateStatus: "skipped" | "pending" | "approved" | "rejected" | "timed_out";
    }[];
    domains: {
        certificateType: "letsencrypt" | "none" | "custom";
        createdAt: string;
        applicationId: string | null;
        host: string;
        port: number | null;
        path: string | null;
        internalPath: string | null;
        stripPath: boolean;
        https: boolean;
        customCertResolver: string | null;
        middlewares: string[] | null;
        serviceName: string | null;
        domainType: "application" | "compose" | "preview" | null;
        domainId: string;
        customEntrypoint: string | null;
        uniqueConfigKey: number;
        composeId: string | null;
        previewDeploymentId: string | null;
    }[];
    mounts: {
        type: "file" | "bind" | "volume";
        applicationId: string | null;
        composeId: string | null;
        serviceType: "application" | "compose" | "mysql" | "libsql" | "mariadb" | "mongo" | "postgres" | "redis";
        mysqlId: string | null;
        filePath: string | null;
        content: string | null;
        mountId: string;
        hostPath: string | null;
        volumeName: string | null;
        mountPath: string;
        libsqlId: string | null;
        mariadbId: string | null;
        mongoId: string | null;
        postgresId: string | null;
        redisId: string | null;
    }[];
    ports: {
        applicationId: string;
        protocol: "tcp" | "udp";
        portId: string;
        publishedPort: number;
        publishMode: "host" | "ingress";
        targetPort: number;
    }[];
    previewDeployments: {
        createdAt: string;
        expiresAt: string | null;
        applicationId: string;
        domainId: string | null;
        appName: string;
        branch: string;
        previewDeploymentId: string;
        pullRequestId: string;
        pullRequestNumber: string;
        pullRequestURL: string;
        pullRequestTitle: string;
        pullRequestCommentId: string;
        previewStatus: "idle" | "running" | "done" | "error";
    }[];
    redirects: {
        createdAt: string;
        applicationId: string;
        uniqueConfigKey: number;
        redirectId: string;
        regex: string;
        replacement: string;
        permanent: boolean;
    }[];
    security: {
        createdAt: string;
        applicationId: string;
        username: string;
        password: string;
        securityId: string;
    }[];
    buildRegistry: {
        createdAt: string;
        organizationId: string;
        username: string;
        password: string;
        registryUrl: string;
        registryId: string;
        registryName: string;
        imagePrefix: string | null;
        registryType: "selfHosted" | "cloud";
    } | null;
    rollbackRegistry: {
        createdAt: string;
        organizationId: string;
        username: string;
        password: string;
        registryUrl: string;
        registryId: string;
        registryName: string;
        imagePrefix: string | null;
        registryType: "selfHosted" | "cloud";
    } | null;
}>;
export declare const findApplicationByName: (appName: string) => Promise<{
    applicationStatus: "idle" | "running" | "done" | "error";
    triggerType: "push" | "tag" | null;
    giteaId: string | null;
    name: string;
    createdAt: string;
    refreshToken: string | null;
    description: string | null;
    owner: string | null;
    githubId: string | null;
    gitlabId: string | null;
    applicationId: string;
    appName: string;
    env: string | null;
    sourceType: "gitea" | "github" | "gitlab" | "bitbucket" | "git" | "docker" | "drop";
    repository: string | null;
    branch: string | null;
    autoDeploy: boolean | null;
    gitlabProjectId: number | null;
    gitlabRepository: string | null;
    gitlabOwner: string | null;
    gitlabBranch: string | null;
    gitlabPathNamespace: string | null;
    bitbucketRepository: string | null;
    bitbucketRepositorySlug: string | null;
    bitbucketOwner: string | null;
    bitbucketBranch: string | null;
    giteaRepository: string | null;
    giteaOwner: string | null;
    giteaBranch: string | null;
    customGitUrl: string | null;
    customGitBranch: string | null;
    customGitSSHKeyId: string | null;
    command: string | null;
    enableSubmodules: boolean;
    environmentId: string;
    watchPaths: string[] | null;
    bitbucketId: string | null;
    serverId: string | null;
    username: string | null;
    previewEnv: string | null;
    previewBuildArgs: string | null;
    previewBuildSecrets: string | null;
    previewLabels: string[] | null;
    previewWildcard: string | null;
    previewPort: number | null;
    previewHttps: boolean;
    previewPath: string | null;
    previewCertificateType: "letsencrypt" | "none" | "custom";
    previewCustomCertResolver: string | null;
    previewLimit: number | null;
    isPreviewDeploymentsActive: boolean | null;
    previewRequireCollaboratorPermissions: boolean | null;
    rollbackActive: boolean | null;
    buildArgs: string | null;
    buildSecrets: string | null;
    memoryReservation: string | null;
    memoryLimit: string | null;
    cpuReservation: string | null;
    cpuLimit: string | null;
    title: string | null;
    enabled: boolean | null;
    subtitle: string | null;
    args: string[] | null;
    icon: string | null;
    cleanCache: boolean | null;
    buildPath: string | null;
    gitlabBuildPath: string | null;
    giteaBuildPath: string | null;
    bitbucketBuildPath: string | null;
    password: string | null;
    dockerImage: string | null;
    registryUrl: string | null;
    customGitBuildPath: string | null;
    dockerfile: string | null;
    dockerContextPath: string | null;
    dockerBuildStage: string | null;
    dropBuildPath: string | null;
    healthCheckSwarm: import("@undevops/server/db").HealthCheckSwarm | null;
    restartPolicySwarm: import("@undevops/server/db").RestartPolicySwarm | null;
    placementSwarm: import("@undevops/server/db").PlacementSwarm | null;
    updateConfigSwarm: import("@undevops/server/db").UpdateConfigSwarm | null;
    rollbackConfigSwarm: import("@undevops/server/db").UpdateConfigSwarm | null;
    modeSwarm: import("@undevops/server/db").ServiceModeSwarm | null;
    labelsSwarm: import("@undevops/server/db").LabelsSwarm | null;
    networkSwarm: import("@undevops/server/db").NetworkSwarm[] | null;
    stopGracePeriodSwarm: number | null;
    endpointSpecSwarm: import("@undevops/server/db").EndpointSpecSwarm | null;
    ulimitsSwarm: import("@undevops/server/db").UlimitsSwarm | null;
    replicas: number;
    buildType: "dockerfile" | "heroku_buildpacks" | "paketo_buildpacks" | "nixpacks" | "static" | "railpack";
    railpackVersion: string | null;
    herokuVersion: string | null;
    publishDirectory: string | null;
    isStaticSpa: boolean | null;
    createEnvFile: boolean;
    registryId: string | null;
    rollbackRegistryId: string | null;
    buildServerId: string | null;
    buildRegistryId: string | null;
} | undefined>;
export declare const updateApplication: (applicationId: string, applicationData: Partial<Application>) => Promise<{
    applicationId: string;
    name: string;
    appName: string;
    description: string | null;
    env: string | null;
    previewEnv: string | null;
    watchPaths: string[] | null;
    previewBuildArgs: string | null;
    previewBuildSecrets: string | null;
    previewLabels: string[] | null;
    previewWildcard: string | null;
    previewPort: number | null;
    previewHttps: boolean;
    previewPath: string | null;
    previewCertificateType: "letsencrypt" | "none" | "custom";
    previewCustomCertResolver: string | null;
    previewLimit: number | null;
    isPreviewDeploymentsActive: boolean | null;
    previewRequireCollaboratorPermissions: boolean | null;
    rollbackActive: boolean | null;
    buildArgs: string | null;
    buildSecrets: string | null;
    memoryReservation: string | null;
    memoryLimit: string | null;
    cpuReservation: string | null;
    cpuLimit: string | null;
    title: string | null;
    enabled: boolean | null;
    subtitle: string | null;
    command: string | null;
    args: string[] | null;
    icon: string | null;
    refreshToken: string | null;
    sourceType: "gitea" | "github" | "gitlab" | "bitbucket" | "git" | "docker" | "drop";
    cleanCache: boolean | null;
    repository: string | null;
    owner: string | null;
    branch: string | null;
    buildPath: string | null;
    triggerType: "push" | "tag" | null;
    autoDeploy: boolean | null;
    gitlabProjectId: number | null;
    gitlabRepository: string | null;
    gitlabOwner: string | null;
    gitlabBranch: string | null;
    gitlabBuildPath: string | null;
    gitlabPathNamespace: string | null;
    giteaRepository: string | null;
    giteaOwner: string | null;
    giteaBranch: string | null;
    giteaBuildPath: string | null;
    bitbucketRepository: string | null;
    bitbucketRepositorySlug: string | null;
    bitbucketOwner: string | null;
    bitbucketBranch: string | null;
    bitbucketBuildPath: string | null;
    username: string | null;
    password: string | null;
    dockerImage: string | null;
    registryUrl: string | null;
    customGitUrl: string | null;
    customGitBranch: string | null;
    customGitBuildPath: string | null;
    customGitSSHKeyId: string | null;
    enableSubmodules: boolean;
    dockerfile: string | null;
    dockerContextPath: string | null;
    dockerBuildStage: string | null;
    dropBuildPath: string | null;
    healthCheckSwarm: import("@undevops/server/db").HealthCheckSwarm | null;
    restartPolicySwarm: import("@undevops/server/db").RestartPolicySwarm | null;
    placementSwarm: import("@undevops/server/db").PlacementSwarm | null;
    updateConfigSwarm: import("@undevops/server/db").UpdateConfigSwarm | null;
    rollbackConfigSwarm: import("@undevops/server/db").UpdateConfigSwarm | null;
    modeSwarm: import("@undevops/server/db").ServiceModeSwarm | null;
    labelsSwarm: import("@undevops/server/db").LabelsSwarm | null;
    networkSwarm: import("@undevops/server/db").NetworkSwarm[] | null;
    stopGracePeriodSwarm: number | null;
    endpointSpecSwarm: import("@undevops/server/db").EndpointSpecSwarm | null;
    ulimitsSwarm: import("@undevops/server/db").UlimitsSwarm | null;
    replicas: number;
    applicationStatus: "idle" | "running" | "done" | "error";
    buildType: "dockerfile" | "heroku_buildpacks" | "paketo_buildpacks" | "nixpacks" | "static" | "railpack";
    railpackVersion: string | null;
    herokuVersion: string | null;
    publishDirectory: string | null;
    isStaticSpa: boolean | null;
    createEnvFile: boolean;
    createdAt: string;
    registryId: string | null;
    rollbackRegistryId: string | null;
    environmentId: string;
    githubId: string | null;
    gitlabId: string | null;
    giteaId: string | null;
    bitbucketId: string | null;
    serverId: string | null;
    buildServerId: string | null;
    buildRegistryId: string | null;
}>;
export declare const updateApplicationStatus: (applicationId: string, applicationStatus: Application["applicationStatus"]) => Promise<{
    applicationId: string;
    name: string;
    appName: string;
    description: string | null;
    env: string | null;
    previewEnv: string | null;
    watchPaths: string[] | null;
    previewBuildArgs: string | null;
    previewBuildSecrets: string | null;
    previewLabels: string[] | null;
    previewWildcard: string | null;
    previewPort: number | null;
    previewHttps: boolean;
    previewPath: string | null;
    previewCertificateType: "letsencrypt" | "none" | "custom";
    previewCustomCertResolver: string | null;
    previewLimit: number | null;
    isPreviewDeploymentsActive: boolean | null;
    previewRequireCollaboratorPermissions: boolean | null;
    rollbackActive: boolean | null;
    buildArgs: string | null;
    buildSecrets: string | null;
    memoryReservation: string | null;
    memoryLimit: string | null;
    cpuReservation: string | null;
    cpuLimit: string | null;
    title: string | null;
    enabled: boolean | null;
    subtitle: string | null;
    command: string | null;
    args: string[] | null;
    icon: string | null;
    refreshToken: string | null;
    sourceType: "gitea" | "github" | "gitlab" | "bitbucket" | "git" | "docker" | "drop";
    cleanCache: boolean | null;
    repository: string | null;
    owner: string | null;
    branch: string | null;
    buildPath: string | null;
    triggerType: "push" | "tag" | null;
    autoDeploy: boolean | null;
    gitlabProjectId: number | null;
    gitlabRepository: string | null;
    gitlabOwner: string | null;
    gitlabBranch: string | null;
    gitlabBuildPath: string | null;
    gitlabPathNamespace: string | null;
    giteaRepository: string | null;
    giteaOwner: string | null;
    giteaBranch: string | null;
    giteaBuildPath: string | null;
    bitbucketRepository: string | null;
    bitbucketRepositorySlug: string | null;
    bitbucketOwner: string | null;
    bitbucketBranch: string | null;
    bitbucketBuildPath: string | null;
    username: string | null;
    password: string | null;
    dockerImage: string | null;
    registryUrl: string | null;
    customGitUrl: string | null;
    customGitBranch: string | null;
    customGitBuildPath: string | null;
    customGitSSHKeyId: string | null;
    enableSubmodules: boolean;
    dockerfile: string | null;
    dockerContextPath: string | null;
    dockerBuildStage: string | null;
    dropBuildPath: string | null;
    healthCheckSwarm: import("@undevops/server/db").HealthCheckSwarm | null;
    restartPolicySwarm: import("@undevops/server/db").RestartPolicySwarm | null;
    placementSwarm: import("@undevops/server/db").PlacementSwarm | null;
    updateConfigSwarm: import("@undevops/server/db").UpdateConfigSwarm | null;
    rollbackConfigSwarm: import("@undevops/server/db").UpdateConfigSwarm | null;
    modeSwarm: import("@undevops/server/db").ServiceModeSwarm | null;
    labelsSwarm: import("@undevops/server/db").LabelsSwarm | null;
    networkSwarm: import("@undevops/server/db").NetworkSwarm[] | null;
    stopGracePeriodSwarm: number | null;
    endpointSpecSwarm: import("@undevops/server/db").EndpointSpecSwarm | null;
    ulimitsSwarm: import("@undevops/server/db").UlimitsSwarm | null;
    replicas: number;
    applicationStatus: "idle" | "running" | "done" | "error";
    buildType: "dockerfile" | "heroku_buildpacks" | "paketo_buildpacks" | "nixpacks" | "static" | "railpack";
    railpackVersion: string | null;
    herokuVersion: string | null;
    publishDirectory: string | null;
    isStaticSpa: boolean | null;
    createEnvFile: boolean;
    createdAt: string;
    registryId: string | null;
    rollbackRegistryId: string | null;
    environmentId: string;
    githubId: string | null;
    gitlabId: string | null;
    giteaId: string | null;
    bitbucketId: string | null;
    serverId: string | null;
    buildServerId: string | null;
    buildRegistryId: string | null;
}[]>;
export declare const deployApplication: ({ applicationId, titleLog, descriptionLog, }: {
    applicationId: string;
    titleLog: string;
    descriptionLog: string;
}) => Promise<boolean>;
export declare const rebuildApplication: ({ applicationId, titleLog, descriptionLog, }: {
    applicationId: string;
    titleLog: string;
    descriptionLog: string;
}) => Promise<boolean>;
export declare const deployPreviewApplication: ({ applicationId, titleLog, descriptionLog, previewDeploymentId, }: {
    applicationId: string;
    titleLog: string;
    descriptionLog: string;
    previewDeploymentId: string;
}) => Promise<boolean>;
export declare const rebuildPreviewApplication: ({ applicationId, titleLog, descriptionLog, previewDeploymentId, }: {
    applicationId: string;
    titleLog: string;
    descriptionLog: string;
    previewDeploymentId: string;
}) => Promise<boolean>;
export declare const getApplicationStats: (appName: string) => Promise<{
    cpu: any;
    memory: any;
    disk: any;
    network: any;
    block: any;
} | null>;
//# sourceMappingURL=application.d.ts.map