import { type apiCreateBackup, backups } from "@undevops/server/db/schema";
import type { z } from "zod";
export type Backup = typeof backups.$inferSelect;
export type BackupSchedule = Awaited<ReturnType<typeof findBackupById>>;
export type BackupScheduleList = Awaited<ReturnType<typeof findBackupsByDbId>>;
export declare const createBackup: (input: z.infer<typeof apiCreateBackup>) => Promise<{
    metadata: {
        postgres?: {
            databaseUser: string;
        };
        mariadb?: {
            databaseUser: string;
            databasePassword: string;
        };
        mongo?: {
            databaseUser: string;
            databasePassword: string;
        };
        mysql?: {
            databaseRootPassword: string;
        };
    } | null | undefined;
    userId: string | null;
    serviceName: string | null;
    composeId: string | null;
    appName: string;
    enabled: boolean | null;
    databaseType: "mysql" | "libsql" | "mariadb" | "mongo" | "postgres" | "web-server";
    backupType: "compose" | "database";
    mysqlId: string | null;
    prefix: string;
    backupId: string;
    libsqlId: string | null;
    mariadbId: string | null;
    mongoId: string | null;
    postgresId: string | null;
    database: string;
    schedule: string;
    destinationId: string;
    keepLatestCount: number | null;
}>;
export declare const findBackupById: (backupId: string) => Promise<{
    metadata: {
        postgres?: {
            databaseUser: string;
        };
        mariadb?: {
            databaseUser: string;
            databasePassword: string;
        };
        mongo?: {
            databaseUser: string;
            databasePassword: string;
        };
        mysql?: {
            databaseRootPassword: string;
        };
    } | null | undefined;
    userId: string | null;
    serviceName: string | null;
    composeId: string | null;
    appName: string;
    enabled: boolean | null;
    databaseType: "mysql" | "libsql" | "mariadb" | "mongo" | "postgres" | "web-server";
    backupType: "compose" | "database";
    mysqlId: string | null;
    prefix: string;
    backupId: string;
    libsqlId: string | null;
    mariadbId: string | null;
    mongoId: string | null;
    postgresId: string | null;
    database: string;
    schedule: string;
    destinationId: string;
    keepLatestCount: number | null;
    compose: {
        triggerType: "push" | "tag" | null;
        giteaId: string | null;
        name: string;
        createdAt: string;
        refreshToken: string | null;
        description: string | null;
        owner: string | null;
        githubId: string | null;
        gitlabId: string | null;
        composeId: string;
        appName: string;
        env: string | null;
        composeFile: string;
        sourceType: "gitea" | "github" | "gitlab" | "bitbucket" | "raw" | "git";
        composeType: "docker-compose" | "stack";
        repository: string | null;
        branch: string | null;
        autoDeploy: boolean | null;
        gitlabProjectId: number | null;
        gitlabRepository: string | null;
        gitlabOwner: string | null;
        gitlabBranch: string | null;
        gitlabPathNamespace: string | null;
        bitbucketRepository: string | null;
        bitbucketRepositorySlug: string | null;
        bitbucketOwner: string | null;
        bitbucketBranch: string | null;
        giteaRepository: string | null;
        giteaOwner: string | null;
        giteaBranch: string | null;
        customGitUrl: string | null;
        customGitBranch: string | null;
        customGitSSHKeyId: string | null;
        command: string;
        enableSubmodules: boolean;
        composePath: string;
        suffix: string;
        randomize: boolean;
        isolatedDeployment: boolean;
        isolatedDeploymentsVolume: boolean;
        composeStatus: "idle" | "running" | "done" | "error";
        environmentId: string;
        watchPaths: string[] | null;
        bitbucketId: string | null;
        serverId: string | null;
    } | null;
    mysql: {
        applicationStatus: "idle" | "running" | "done" | "error";
        name: string;
        createdAt: string;
        description: string | null;
        appName: string;
        env: string | null;
        command: string | null;
        environmentId: string;
        serverId: string | null;
        memoryReservation: string | null;
        memoryLimit: string | null;
        cpuReservation: string | null;
        cpuLimit: string | null;
        args: string[] | null;
        dockerImage: string;
        healthCheckSwarm: import("@undevops/server/db").HealthCheckSwarm | null;
        restartPolicySwarm: import("@undevops/server/db").RestartPolicySwarm | null;
        placementSwarm: import("@undevops/server/db").PlacementSwarm | null;
        updateConfigSwarm: import("@undevops/server/db").UpdateConfigSwarm | null;
        rollbackConfigSwarm: import("@undevops/server/db").UpdateConfigSwarm | null;
        modeSwarm: import("@undevops/server/db").ServiceModeSwarm | null;
        labelsSwarm: import("@undevops/server/db").LabelsSwarm | null;
        networkSwarm: import("@undevops/server/db").NetworkSwarm[] | null;
        stopGracePeriodSwarm: number | null;
        endpointSpecSwarm: import("@undevops/server/db").EndpointSpecSwarm | null;
        ulimitsSwarm: import("@undevops/server/db").UlimitsSwarm | null;
        replicas: number;
        mysqlId: string;
        databaseName: string;
        databaseUser: string;
        databasePassword: string;
        databaseRootPassword: string;
        externalPort: number | null;
    } | null;
    libsql: {
        applicationStatus: "idle" | "running" | "done" | "error";
        sqldNode: "primary" | "replica";
        name: string;
        createdAt: string;
        description: string | null;
        appName: string;
        env: string | null;
        command: string | null;
        environmentId: string;
        serverId: string | null;
        memoryReservation: string | null;
        memoryLimit: string | null;
        cpuReservation: string | null;
        cpuLimit: string | null;
        dockerImage: string;
        healthCheckSwarm: import("@undevops/server/db").HealthCheckSwarm | null;
        restartPolicySwarm: import("@undevops/server/db").RestartPolicySwarm | null;
        placementSwarm: import("@undevops/server/db").PlacementSwarm | null;
        updateConfigSwarm: import("@undevops/server/db").UpdateConfigSwarm | null;
        rollbackConfigSwarm: import("@undevops/server/db").UpdateConfigSwarm | null;
        modeSwarm: import("@undevops/server/db").ServiceModeSwarm | null;
        labelsSwarm: import("@undevops/server/db").LabelsSwarm | null;
        networkSwarm: import("@undevops/server/db").NetworkSwarm[] | null;
        stopGracePeriodSwarm: number | null;
        endpointSpecSwarm: import("@undevops/server/db").EndpointSpecSwarm | null;
        replicas: number;
        databaseUser: string;
        databasePassword: string;
        externalPort: number | null;
        libsqlId: string;
        sqldPrimaryUrl: string | null;
        enableNamespaces: boolean;
        externalGRPCPort: number | null;
        externalAdminPort: number | null;
    } | null;
    mariadb: {
        applicationStatus: "idle" | "running" | "done" | "error";
        name: string;
        createdAt: string;
        description: string | null;
        appName: string;
        env: string | null;
        command: string | null;
        environmentId: string;
        serverId: string | null;
        memoryReservation: string | null;
        memoryLimit: string | null;
        cpuReservation: string | null;
        cpuLimit: string | null;
        args: string[] | null;
        dockerImage: string;
        healthCheckSwarm: import("@undevops/server/db").HealthCheckSwarm | null;
        restartPolicySwarm: import("@undevops/server/db").RestartPolicySwarm | null;
        placementSwarm: import("@undevops/server/db").PlacementSwarm | null;
        updateConfigSwarm: import("@undevops/server/db").UpdateConfigSwarm | null;
        rollbackConfigSwarm: import("@undevops/server/db").UpdateConfigSwarm | null;
        modeSwarm: import("@undevops/server/db").ServiceModeSwarm | null;
        labelsSwarm: import("@undevops/server/db").LabelsSwarm | null;
        networkSwarm: import("@undevops/server/db").NetworkSwarm[] | null;
        stopGracePeriodSwarm: number | null;
        endpointSpecSwarm: import("@undevops/server/db").EndpointSpecSwarm | null;
        ulimitsSwarm: import("@undevops/server/db").UlimitsSwarm | null;
        replicas: number;
        databaseName: string;
        databaseUser: string;
        databasePassword: string;
        databaseRootPassword: string;
        externalPort: number | null;
        mariadbId: string;
    } | null;
    mongo: {
        applicationStatus: "idle" | "running" | "done" | "error";
        name: string;
        createdAt: string;
        description: string | null;
        appName: string;
        env: string | null;
        command: string | null;
        environmentId: string;
        serverId: string | null;
        memoryReservation: string | null;
        memoryLimit: string | null;
        cpuReservation: string | null;
        cpuLimit: string | null;
        args: string[] | null;
        dockerImage: string;
        healthCheckSwarm: import("@undevops/server/db").HealthCheckSwarm | null;
        restartPolicySwarm: import("@undevops/server/db").RestartPolicySwarm | null;
        placementSwarm: import("@undevops/server/db").PlacementSwarm | null;
        updateConfigSwarm: import("@undevops/server/db").UpdateConfigSwarm | null;
        rollbackConfigSwarm: import("@undevops/server/db").UpdateConfigSwarm | null;
        modeSwarm: import("@undevops/server/db").ServiceModeSwarm | null;
        labelsSwarm: import("@undevops/server/db").LabelsSwarm | null;
        networkSwarm: import("@undevops/server/db").NetworkSwarm[] | null;
        stopGracePeriodSwarm: number | null;
        endpointSpecSwarm: import("@undevops/server/db").EndpointSpecSwarm | null;
        ulimitsSwarm: import("@undevops/server/db").UlimitsSwarm | null;
        replicas: number;
        databaseUser: string;
        databasePassword: string;
        externalPort: number | null;
        mongoId: string;
        replicaSets: boolean | null;
    } | null;
    postgres: {
        applicationStatus: "idle" | "running" | "done" | "error";
        name: string;
        createdAt: string;
        description: string | null;
        appName: string;
        env: string | null;
        command: string | null;
        environmentId: string;
        serverId: string | null;
        memoryReservation: string | null;
        memoryLimit: string | null;
        cpuReservation: string | null;
        cpuLimit: string | null;
        args: string[] | null;
        dockerImage: string;
        healthCheckSwarm: import("@undevops/server/db").HealthCheckSwarm | null;
        restartPolicySwarm: import("@undevops/server/db").RestartPolicySwarm | null;
        placementSwarm: import("@undevops/server/db").PlacementSwarm | null;
        updateConfigSwarm: import("@undevops/server/db").UpdateConfigSwarm | null;
        rollbackConfigSwarm: import("@undevops/server/db").UpdateConfigSwarm | null;
        modeSwarm: import("@undevops/server/db").ServiceModeSwarm | null;
        labelsSwarm: import("@undevops/server/db").LabelsSwarm | null;
        networkSwarm: import("@undevops/server/db").NetworkSwarm[] | null;
        stopGracePeriodSwarm: number | null;
        endpointSpecSwarm: import("@undevops/server/db").EndpointSpecSwarm | null;
        ulimitsSwarm: import("@undevops/server/db").UlimitsSwarm | null;
        replicas: number;
        databaseName: string;
        databaseUser: string;
        databasePassword: string;
        externalPort: number | null;
        postgresId: string;
    } | null;
    destination: {
        name: string;
        createdAt: Date;
        organizationId: string;
        endpoint: string;
        destinationId: string;
        provider: string | null;
        accessKey: string;
        secretAccessKey: string;
        bucket: string;
        region: string;
        additionalFlags: string[] | null;
    };
}>;
export declare const updateBackupById: (backupId: string, backupData: Partial<Backup>) => Promise<{
    backupId: string;
    appName: string;
    schedule: string;
    enabled: boolean | null;
    database: string;
    prefix: string;
    serviceName: string | null;
    destinationId: string;
    keepLatestCount: number | null;
    backupType: "compose" | "database";
    databaseType: "mysql" | "libsql" | "mariadb" | "mongo" | "postgres" | "web-server";
    composeId: string | null;
    postgresId: string | null;
    mariadbId: string | null;
    mysqlId: string | null;
    mongoId: string | null;
    libsqlId: string | null;
    userId: string | null;
    metadata: {
        postgres?: {
            databaseUser: string;
        };
        mariadb?: {
            databaseUser: string;
            databasePassword: string;
        };
        mongo?: {
            databaseUser: string;
            databasePassword: string;
        };
        mysql?: {
            databaseRootPassword: string;
        };
    } | null | undefined;
}>;
export declare const removeBackupById: (backupId: string) => Promise<{
    metadata: {
        postgres?: {
            databaseUser: string;
        };
        mariadb?: {
            databaseUser: string;
            databasePassword: string;
        };
        mongo?: {
            databaseUser: string;
            databasePassword: string;
        };
        mysql?: {
            databaseRootPassword: string;
        };
    } | null | undefined;
    userId: string | null;
    serviceName: string | null;
    composeId: string | null;
    appName: string;
    enabled: boolean | null;
    databaseType: "mysql" | "libsql" | "mariadb" | "mongo" | "postgres" | "web-server";
    backupType: "compose" | "database";
    mysqlId: string | null;
    prefix: string;
    backupId: string;
    libsqlId: string | null;
    mariadbId: string | null;
    mongoId: string | null;
    postgresId: string | null;
    database: string;
    schedule: string;
    destinationId: string;
    keepLatestCount: number | null;
}>;
export declare const findBackupsByDbId: (id: string, type: "postgres" | "mysql" | "mariadb" | "mongo" | "libsql") => Promise<{
    metadata: {
        postgres?: {
            databaseUser: string;
        };
        mariadb?: {
            databaseUser: string;
            databasePassword: string;
        };
        mongo?: {
            databaseUser: string;
            databasePassword: string;
        };
        mysql?: {
            databaseRootPassword: string;
        };
    } | null | undefined;
    userId: string | null;
    serviceName: string | null;
    composeId: string | null;
    appName: string;
    enabled: boolean | null;
    databaseType: "mysql" | "libsql" | "mariadb" | "mongo" | "postgres" | "web-server";
    backupType: "compose" | "database";
    mysqlId: string | null;
    prefix: string;
    backupId: string;
    libsqlId: string | null;
    mariadbId: string | null;
    mongoId: string | null;
    postgresId: string | null;
    database: string;
    schedule: string;
    destinationId: string;
    keepLatestCount: number | null;
    mysql: {
        applicationStatus: "idle" | "running" | "done" | "error";
        name: string;
        createdAt: string;
        description: string | null;
        appName: string;
        env: string | null;
        command: string | null;
        environmentId: string;
        serverId: string | null;
        memoryReservation: string | null;
        memoryLimit: string | null;
        cpuReservation: string | null;
        cpuLimit: string | null;
        args: string[] | null;
        dockerImage: string;
        healthCheckSwarm: import("@undevops/server/db").HealthCheckSwarm | null;
        restartPolicySwarm: import("@undevops/server/db").RestartPolicySwarm | null;
        placementSwarm: import("@undevops/server/db").PlacementSwarm | null;
        updateConfigSwarm: import("@undevops/server/db").UpdateConfigSwarm | null;
        rollbackConfigSwarm: import("@undevops/server/db").UpdateConfigSwarm | null;
        modeSwarm: import("@undevops/server/db").ServiceModeSwarm | null;
        labelsSwarm: import("@undevops/server/db").LabelsSwarm | null;
        networkSwarm: import("@undevops/server/db").NetworkSwarm[] | null;
        stopGracePeriodSwarm: number | null;
        endpointSpecSwarm: import("@undevops/server/db").EndpointSpecSwarm | null;
        ulimitsSwarm: import("@undevops/server/db").UlimitsSwarm | null;
        replicas: number;
        mysqlId: string;
        databaseName: string;
        databaseUser: string;
        databasePassword: string;
        databaseRootPassword: string;
        externalPort: number | null;
    } | null;
    libsql: {
        applicationStatus: "idle" | "running" | "done" | "error";
        sqldNode: "primary" | "replica";
        name: string;
        createdAt: string;
        description: string | null;
        appName: string;
        env: string | null;
        command: string | null;
        environmentId: string;
        serverId: string | null;
        memoryReservation: string | null;
        memoryLimit: string | null;
        cpuReservation: string | null;
        cpuLimit: string | null;
        dockerImage: string;
        healthCheckSwarm: import("@undevops/server/db").HealthCheckSwarm | null;
        restartPolicySwarm: import("@undevops/server/db").RestartPolicySwarm | null;
        placementSwarm: import("@undevops/server/db").PlacementSwarm | null;
        updateConfigSwarm: import("@undevops/server/db").UpdateConfigSwarm | null;
        rollbackConfigSwarm: import("@undevops/server/db").UpdateConfigSwarm | null;
        modeSwarm: import("@undevops/server/db").ServiceModeSwarm | null;
        labelsSwarm: import("@undevops/server/db").LabelsSwarm | null;
        networkSwarm: import("@undevops/server/db").NetworkSwarm[] | null;
        stopGracePeriodSwarm: number | null;
        endpointSpecSwarm: import("@undevops/server/db").EndpointSpecSwarm | null;
        replicas: number;
        databaseUser: string;
        databasePassword: string;
        externalPort: number | null;
        libsqlId: string;
        sqldPrimaryUrl: string | null;
        enableNamespaces: boolean;
        externalGRPCPort: number | null;
        externalAdminPort: number | null;
    } | null;
    mariadb: {
        applicationStatus: "idle" | "running" | "done" | "error";
        name: string;
        createdAt: string;
        description: string | null;
        appName: string;
        env: string | null;
        command: string | null;
        environmentId: string;
        serverId: string | null;
        memoryReservation: string | null;
        memoryLimit: string | null;
        cpuReservation: string | null;
        cpuLimit: string | null;
        args: string[] | null;
        dockerImage: string;
        healthCheckSwarm: import("@undevops/server/db").HealthCheckSwarm | null;
        restartPolicySwarm: import("@undevops/server/db").RestartPolicySwarm | null;
        placementSwarm: import("@undevops/server/db").PlacementSwarm | null;
        updateConfigSwarm: import("@undevops/server/db").UpdateConfigSwarm | null;
        rollbackConfigSwarm: import("@undevops/server/db").UpdateConfigSwarm | null;
        modeSwarm: import("@undevops/server/db").ServiceModeSwarm | null;
        labelsSwarm: import("@undevops/server/db").LabelsSwarm | null;
        networkSwarm: import("@undevops/server/db").NetworkSwarm[] | null;
        stopGracePeriodSwarm: number | null;
        endpointSpecSwarm: import("@undevops/server/db").EndpointSpecSwarm | null;
        ulimitsSwarm: import("@undevops/server/db").UlimitsSwarm | null;
        replicas: number;
        databaseName: string;
        databaseUser: string;
        databasePassword: string;
        databaseRootPassword: string;
        externalPort: number | null;
        mariadbId: string;
    } | null;
    mongo: {
        applicationStatus: "idle" | "running" | "done" | "error";
        name: string;
        createdAt: string;
        description: string | null;
        appName: string;
        env: string | null;
        command: string | null;
        environmentId: string;
        serverId: string | null;
        memoryReservation: string | null;
        memoryLimit: string | null;
        cpuReservation: string | null;
        cpuLimit: string | null;
        args: string[] | null;
        dockerImage: string;
        healthCheckSwarm: import("@undevops/server/db").HealthCheckSwarm | null;
        restartPolicySwarm: import("@undevops/server/db").RestartPolicySwarm | null;
        placementSwarm: import("@undevops/server/db").PlacementSwarm | null;
        updateConfigSwarm: import("@undevops/server/db").UpdateConfigSwarm | null;
        rollbackConfigSwarm: import("@undevops/server/db").UpdateConfigSwarm | null;
        modeSwarm: import("@undevops/server/db").ServiceModeSwarm | null;
        labelsSwarm: import("@undevops/server/db").LabelsSwarm | null;
        networkSwarm: import("@undevops/server/db").NetworkSwarm[] | null;
        stopGracePeriodSwarm: number | null;
        endpointSpecSwarm: import("@undevops/server/db").EndpointSpecSwarm | null;
        ulimitsSwarm: import("@undevops/server/db").UlimitsSwarm | null;
        replicas: number;
        databaseUser: string;
        databasePassword: string;
        externalPort: number | null;
        mongoId: string;
        replicaSets: boolean | null;
    } | null;
    postgres: {
        applicationStatus: "idle" | "running" | "done" | "error";
        name: string;
        createdAt: string;
        description: string | null;
        appName: string;
        env: string | null;
        command: string | null;
        environmentId: string;
        serverId: string | null;
        memoryReservation: string | null;
        memoryLimit: string | null;
        cpuReservation: string | null;
        cpuLimit: string | null;
        args: string[] | null;
        dockerImage: string;
        healthCheckSwarm: import("@undevops/server/db").HealthCheckSwarm | null;
        restartPolicySwarm: import("@undevops/server/db").RestartPolicySwarm | null;
        placementSwarm: import("@undevops/server/db").PlacementSwarm | null;
        updateConfigSwarm: import("@undevops/server/db").UpdateConfigSwarm | null;
        rollbackConfigSwarm: import("@undevops/server/db").UpdateConfigSwarm | null;
        modeSwarm: import("@undevops/server/db").ServiceModeSwarm | null;
        labelsSwarm: import("@undevops/server/db").LabelsSwarm | null;
        networkSwarm: import("@undevops/server/db").NetworkSwarm[] | null;
        stopGracePeriodSwarm: number | null;
        endpointSpecSwarm: import("@undevops/server/db").EndpointSpecSwarm | null;
        ulimitsSwarm: import("@undevops/server/db").UlimitsSwarm | null;
        replicas: number;
        databaseName: string;
        databaseUser: string;
        databasePassword: string;
        externalPort: number | null;
        postgresId: string;
    } | null;
    destination: {
        name: string;
        createdAt: Date;
        organizationId: string;
        endpoint: string;
        destinationId: string;
        provider: string | null;
        accessKey: string;
        secretAccessKey: string;
        bucket: string;
        region: string;
        additionalFlags: string[] | null;
    };
}[]>;
//# sourceMappingURL=backup.d.ts.map