import { type apiCreateCompose, compose } from "@undevops/server/db/schema";
import type { z } from "zod";
export type Compose = typeof compose.$inferSelect;
export declare const createCompose: (input: z.infer<typeof apiCreateCompose>) => Promise<{
    triggerType: "push" | "tag" | null;
    giteaId: string | null;
    name: string;
    createdAt: string;
    refreshToken: string | null;
    description: string | null;
    owner: string | null;
    githubId: string | null;
    gitlabId: string | null;
    composeId: string;
    appName: string;
    env: string | null;
    composeFile: string;
    sourceType: "gitea" | "github" | "gitlab" | "bitbucket" | "raw" | "git";
    composeType: "docker-compose" | "stack";
    repository: string | null;
    branch: string | null;
    autoDeploy: boolean | null;
    gitlabProjectId: number | null;
    gitlabRepository: string | null;
    gitlabOwner: string | null;
    gitlabBranch: string | null;
    gitlabPathNamespace: string | null;
    bitbucketRepository: string | null;
    bitbucketRepositorySlug: string | null;
    bitbucketOwner: string | null;
    bitbucketBranch: string | null;
    giteaRepository: string | null;
    giteaOwner: string | null;
    giteaBranch: string | null;
    customGitUrl: string | null;
    customGitBranch: string | null;
    customGitSSHKeyId: string | null;
    command: string;
    enableSubmodules: boolean;
    composePath: string;
    suffix: string;
    randomize: boolean;
    isolatedDeployment: boolean;
    isolatedDeploymentsVolume: boolean;
    composeStatus: "idle" | "running" | "done" | "error";
    environmentId: string;
    watchPaths: string[] | null;
    bitbucketId: string | null;
    serverId: string | null;
}>;
export declare const createComposeByTemplate: (input: typeof compose.$inferInsert) => Promise<{
    triggerType: "push" | "tag" | null;
    giteaId: string | null;
    name: string;
    createdAt: string;
    refreshToken: string | null;
    description: string | null;
    owner: string | null;
    githubId: string | null;
    gitlabId: string | null;
    composeId: string;
    appName: string;
    env: string | null;
    composeFile: string;
    sourceType: "gitea" | "github" | "gitlab" | "bitbucket" | "raw" | "git";
    composeType: "docker-compose" | "stack";
    repository: string | null;
    branch: string | null;
    autoDeploy: boolean | null;
    gitlabProjectId: number | null;
    gitlabRepository: string | null;
    gitlabOwner: string | null;
    gitlabBranch: string | null;
    gitlabPathNamespace: string | null;
    bitbucketRepository: string | null;
    bitbucketRepositorySlug: string | null;
    bitbucketOwner: string | null;
    bitbucketBranch: string | null;
    giteaRepository: string | null;
    giteaOwner: string | null;
    giteaBranch: string | null;
    customGitUrl: string | null;
    customGitBranch: string | null;
    customGitSSHKeyId: string | null;
    command: string;
    enableSubmodules: boolean;
    composePath: string;
    suffix: string;
    randomize: boolean;
    isolatedDeployment: boolean;
    isolatedDeploymentsVolume: boolean;
    composeStatus: "idle" | "running" | "done" | "error";
    environmentId: string;
    watchPaths: string[] | null;
    bitbucketId: string | null;
    serverId: string | null;
}>;
export declare const findComposeById: (composeId: string) => Promise<{
    triggerType: "push" | "tag" | null;
    giteaId: string | null;
    name: string;
    createdAt: string;
    refreshToken: string | null;
    description: string | null;
    owner: string | null;
    githubId: string | null;
    gitlabId: string | null;
    composeId: string;
    appName: string;
    env: string | null;
    composeFile: string;
    sourceType: "gitea" | "github" | "gitlab" | "bitbucket" | "raw" | "git";
    composeType: "docker-compose" | "stack";
    repository: string | null;
    branch: string | null;
    autoDeploy: boolean | null;
    gitlabProjectId: number | null;
    gitlabRepository: string | null;
    gitlabOwner: string | null;
    gitlabBranch: string | null;
    gitlabPathNamespace: string | null;
    bitbucketRepository: string | null;
    bitbucketRepositorySlug: string | null;
    bitbucketOwner: string | null;
    bitbucketBranch: string | null;
    giteaRepository: string | null;
    giteaOwner: string | null;
    giteaBranch: string | null;
    customGitUrl: string | null;
    customGitBranch: string | null;
    customGitSSHKeyId: string | null;
    command: string;
    enableSubmodules: boolean;
    composePath: string;
    suffix: string;
    randomize: boolean;
    isolatedDeployment: boolean;
    isolatedDeploymentsVolume: boolean;
    composeStatus: "idle" | "running" | "done" | "error";
    environmentId: string;
    watchPaths: string[] | null;
    bitbucketId: string | null;
    serverId: string | null;
    environment: {
        name: string;
        createdAt: string;
        description: string | null;
        env: string;
        environmentId: string;
        projectId: string;
        isDefault: boolean;
        gatePolicy: "disabled" | "single" | "unanimous" | "manual_only";
        reviewerIds: string[];
        autoApproveAgents: boolean;
        project: {
            name: string;
            createdAt: string;
            organizationId: string;
            description: string | null;
            env: string;
            projectId: string;
        };
    };
    gitea: {
        giteaId: string;
        giteaUrl: string;
        giteaInternalUrl: string | null;
        redirectUri: string | null;
        clientId: string | null;
        clientSecret: string | null;
        gitProviderId: string;
        accessToken: string | null;
        refreshToken: string | null;
        expiresAt: number | null;
        scopes: string | null;
        lastAuthenticatedAt: number | null;
    } | null;
    github: {
        gitProviderId: string;
        githubId: string;
        githubAppName: string | null;
        githubAppId: number | null;
        githubClientId: string | null;
        githubClientSecret: string | null;
        githubInstallationId: string | null;
        githubPrivateKey: string | null;
        githubWebhookSecret: string | null;
    } | null;
    gitlab: {
        redirectUri: string | null;
        gitProviderId: string;
        accessToken: string | null;
        refreshToken: string | null;
        expiresAt: number | null;
        gitlabId: string;
        gitlabUrl: string;
        gitlabInternalUrl: string | null;
        applicationId: string | null;
        secret: string | null;
        groupName: string | null;
    } | null;
    bitbucket: {
        gitProviderId: string;
        bitbucketId: string;
        bitbucketUsername: string | null;
        bitbucketEmail: string | null;
        appPassword: string | null;
        apiToken: string | null;
        bitbucketWorkspaceName: string | null;
    } | null;
    server: {
        name: string;
        createdAt: string;
        organizationId: string;
        description: string | null;
        port: number;
        appName: string;
        sshKeyId: string | null;
        command: string;
        serverId: string;
        ipAddress: string;
        username: string;
        enableDockerCleanup: boolean;
        serverStatus: "active" | "inactive";
        serverType: "deploy" | "build";
        metricsConfig: {
            server: {
                type: "Dokploy" | "Remote";
                refreshRate: number;
                port: number;
                token: string;
                urlCallback: string;
                retentionDays: number;
                cronJob: string;
                thresholds: {
                    cpu: number;
                    memory: number;
                };
            };
            containers: {
                refreshRate: number;
                services: {
                    include: string[];
                    exclude: string[];
                };
            };
        };
    } | null;
    backups: {
        metadata: {
            postgres?: {
                databaseUser: string;
            };
            mariadb?: {
                databaseUser: string;
                databasePassword: string;
            };
            mongo?: {
                databaseUser: string;
                databasePassword: string;
            };
            mysql?: {
                databaseRootPassword: string;
            };
        } | null | undefined;
        userId: string | null;
        serviceName: string | null;
        composeId: string | null;
        appName: string;
        enabled: boolean | null;
        databaseType: "mysql" | "libsql" | "mariadb" | "mongo" | "postgres" | "web-server";
        backupType: "compose" | "database";
        mysqlId: string | null;
        prefix: string;
        backupId: string;
        libsqlId: string | null;
        mariadbId: string | null;
        mongoId: string | null;
        postgresId: string | null;
        database: string;
        schedule: string;
        destinationId: string;
        keepLatestCount: number | null;
        deployments: {
            createdAt: string;
            description: string | null;
            applicationId: string | null;
            composeId: string | null;
            serverId: string | null;
            title: string;
            buildServerId: string | null;
            previewDeploymentId: string | null;
            status: "running" | "done" | "error" | "cancelled" | null;
            deploymentId: string;
            logPath: string;
            pid: string | null;
            isPreviewDeployment: boolean | null;
            startedAt: string | null;
            finishedAt: string | null;
            errorMessage: string | null;
            scheduleId: string | null;
            backupId: string | null;
            rollbackId: string | null;
            volumeBackupId: string | null;
            initiatingActorType: "human" | "agent" | "plugin" | "system";
            initiatingActorId: string | null;
            gateStatus: "skipped" | "pending" | "approved" | "rejected" | "timed_out";
        }[];
        destination: {
            name: string;
            createdAt: Date;
            organizationId: string;
            endpoint: string;
            destinationId: string;
            provider: string | null;
            accessKey: string;
            secretAccessKey: string;
            bucket: string;
            region: string;
            additionalFlags: string[] | null;
        };
    }[];
    deployments: {
        createdAt: string;
        description: string | null;
        applicationId: string | null;
        composeId: string | null;
        serverId: string | null;
        title: string;
        buildServerId: string | null;
        previewDeploymentId: string | null;
        status: "running" | "done" | "error" | "cancelled" | null;
        deploymentId: string;
        logPath: string;
        pid: string | null;
        isPreviewDeployment: boolean | null;
        startedAt: string | null;
        finishedAt: string | null;
        errorMessage: string | null;
        scheduleId: string | null;
        backupId: string | null;
        rollbackId: string | null;
        volumeBackupId: string | null;
        initiatingActorType: "human" | "agent" | "plugin" | "system";
        initiatingActorId: string | null;
        gateStatus: "skipped" | "pending" | "approved" | "rejected" | "timed_out";
    }[];
    domains: {
        certificateType: "letsencrypt" | "none" | "custom";
        createdAt: string;
        applicationId: string | null;
        host: string;
        port: number | null;
        path: string | null;
        internalPath: string | null;
        stripPath: boolean;
        https: boolean;
        customCertResolver: string | null;
        middlewares: string[] | null;
        serviceName: string | null;
        domainType: "application" | "compose" | "preview" | null;
        domainId: string;
        customEntrypoint: string | null;
        uniqueConfigKey: number;
        composeId: string | null;
        previewDeploymentId: string | null;
    }[];
    mounts: {
        type: "file" | "bind" | "volume";
        applicationId: string | null;
        composeId: string | null;
        serviceType: "application" | "compose" | "mysql" | "libsql" | "mariadb" | "mongo" | "postgres" | "redis";
        mysqlId: string | null;
        filePath: string | null;
        content: string | null;
        mountId: string;
        hostPath: string | null;
        volumeName: string | null;
        mountPath: string;
        libsqlId: string | null;
        mariadbId: string | null;
        mongoId: string | null;
        postgresId: string | null;
        redisId: string | null;
    }[];
}>;
export declare const loadServices: (composeId: string, type?: "fetch" | "cache") => Promise<string[]>;
export declare const updateCompose: (composeId: string, composeData: Partial<Compose>) => Promise<{
    composeId: string;
    name: string;
    appName: string;
    description: string | null;
    env: string | null;
    composeFile: string;
    refreshToken: string | null;
    sourceType: "gitea" | "github" | "gitlab" | "bitbucket" | "raw" | "git";
    composeType: "docker-compose" | "stack";
    repository: string | null;
    owner: string | null;
    branch: string | null;
    autoDeploy: boolean | null;
    gitlabProjectId: number | null;
    gitlabRepository: string | null;
    gitlabOwner: string | null;
    gitlabBranch: string | null;
    gitlabPathNamespace: string | null;
    bitbucketRepository: string | null;
    bitbucketRepositorySlug: string | null;
    bitbucketOwner: string | null;
    bitbucketBranch: string | null;
    giteaRepository: string | null;
    giteaOwner: string | null;
    giteaBranch: string | null;
    customGitUrl: string | null;
    customGitBranch: string | null;
    customGitSSHKeyId: string | null;
    command: string;
    enableSubmodules: boolean;
    composePath: string;
    suffix: string;
    randomize: boolean;
    isolatedDeployment: boolean;
    isolatedDeploymentsVolume: boolean;
    triggerType: "push" | "tag" | null;
    composeStatus: "idle" | "running" | "done" | "error";
    environmentId: string;
    createdAt: string;
    watchPaths: string[] | null;
    githubId: string | null;
    gitlabId: string | null;
    bitbucketId: string | null;
    giteaId: string | null;
    serverId: string | null;
}>;
export declare const deployCompose: ({ composeId, titleLog, descriptionLog, }: {
    composeId: string;
    titleLog: string;
    descriptionLog: string;
}) => Promise<void>;
export declare const rebuildCompose: ({ composeId, titleLog, descriptionLog, }: {
    composeId: string;
    titleLog: string;
    descriptionLog: string;
}) => Promise<boolean>;
export declare const removeCompose: (compose: Compose, deleteVolumes: boolean) => Promise<boolean>;
export declare const startCompose: (composeId: string) => Promise<boolean>;
export declare const stopCompose: (composeId: string) => Promise<boolean>;
//# sourceMappingURL=compose.d.ts.map