import { type apiCreateDeployment, type apiCreateDeploymentBackup, type apiCreateDeploymentCompose, type apiCreateDeploymentPreview, type apiCreateDeploymentSchedule, type apiCreateDeploymentServer, type apiCreateDeploymentVolumeBackup, deployments } from "@undevops/server/db/schema";
import type { z } from "zod";
import { type Application } from "./application";
import { type Compose } from "./compose";
import { type PreviewDeployment } from "./preview-deployment";
import { type Server } from "./server";
export type ServicePath = {
    href: string | null;
    label: string;
};
export declare function resolveServicePath(orgId: string, data: Record<string, unknown>): Promise<ServicePath>;
export type Deployment = typeof deployments.$inferSelect;
export declare const findDeploymentById: (deploymentId: string) => Promise<{
    createdAt: string;
    description: string | null;
    applicationId: string | null;
    composeId: string | null;
    serverId: string | null;
    title: string;
    buildServerId: string | null;
    previewDeploymentId: string | null;
    status: "running" | "done" | "error" | "cancelled" | null;
    deploymentId: string;
    logPath: string;
    pid: string | null;
    isPreviewDeployment: boolean | null;
    startedAt: string | null;
    finishedAt: string | null;
    errorMessage: string | null;
    scheduleId: string | null;
    backupId: string | null;
    rollbackId: string | null;
    volumeBackupId: string | null;
    initiatingActorType: "human" | "agent" | "plugin" | "system";
    initiatingActorId: string | null;
    gateStatus: "skipped" | "pending" | "approved" | "rejected" | "timed_out";
    application: {
        applicationStatus: "idle" | "running" | "done" | "error";
        triggerType: "push" | "tag" | null;
        giteaId: string | null;
        name: string;
        createdAt: string;
        refreshToken: string | null;
        description: string | null;
        owner: string | null;
        githubId: string | null;
        gitlabId: string | null;
        applicationId: string;
        appName: string;
        env: string | null;
        sourceType: "gitea" | "github" | "gitlab" | "bitbucket" | "git" | "docker" | "drop";
        repository: string | null;
        branch: string | null;
        autoDeploy: boolean | null;
        gitlabProjectId: number | null;
        gitlabRepository: string | null;
        gitlabOwner: string | null;
        gitlabBranch: string | null;
        gitlabPathNamespace: string | null;
        bitbucketRepository: string | null;
        bitbucketRepositorySlug: string | null;
        bitbucketOwner: string | null;
        bitbucketBranch: string | null;
        giteaRepository: string | null;
        giteaOwner: string | null;
        giteaBranch: string | null;
        customGitUrl: string | null;
        customGitBranch: string | null;
        customGitSSHKeyId: string | null;
        command: string | null;
        enableSubmodules: boolean;
        environmentId: string;
        watchPaths: string[] | null;
        bitbucketId: string | null;
        serverId: string | null;
        username: string | null;
        previewEnv: string | null;
        previewBuildArgs: string | null;
        previewBuildSecrets: string | null;
        previewLabels: string[] | null;
        previewWildcard: string | null;
        previewPort: number | null;
        previewHttps: boolean;
        previewPath: string | null;
        previewCertificateType: "letsencrypt" | "none" | "custom";
        previewCustomCertResolver: string | null;
        previewLimit: number | null;
        isPreviewDeploymentsActive: boolean | null;
        previewRequireCollaboratorPermissions: boolean | null;
        rollbackActive: boolean | null;
        buildArgs: string | null;
        buildSecrets: string | null;
        memoryReservation: string | null;
        memoryLimit: string | null;
        cpuReservation: string | null;
        cpuLimit: string | null;
        title: string | null;
        enabled: boolean | null;
        subtitle: string | null;
        args: string[] | null;
        icon: string | null;
        cleanCache: boolean | null;
        buildPath: string | null;
        gitlabBuildPath: string | null;
        giteaBuildPath: string | null;
        bitbucketBuildPath: string | null;
        password: string | null;
        dockerImage: string | null;
        registryUrl: string | null;
        customGitBuildPath: string | null;
        dockerfile: string | null;
        dockerContextPath: string | null;
        dockerBuildStage: string | null;
        dropBuildPath: string | null;
        healthCheckSwarm: import("@undevops/server/db").HealthCheckSwarm | null;
        restartPolicySwarm: import("@undevops/server/db").RestartPolicySwarm | null;
        placementSwarm: import("@undevops/server/db").PlacementSwarm | null;
        updateConfigSwarm: import("@undevops/server/db").UpdateConfigSwarm | null;
        rollbackConfigSwarm: import("@undevops/server/db").UpdateConfigSwarm | null;
        modeSwarm: import("@undevops/server/db").ServiceModeSwarm | null;
        labelsSwarm: import("@undevops/server/db").LabelsSwarm | null;
        networkSwarm: import("@undevops/server/db").NetworkSwarm[] | null;
        stopGracePeriodSwarm: number | null;
        endpointSpecSwarm: import("@undevops/server/db").EndpointSpecSwarm | null;
        ulimitsSwarm: import("@undevops/server/db").UlimitsSwarm | null;
        replicas: number;
        buildType: "dockerfile" | "heroku_buildpacks" | "paketo_buildpacks" | "nixpacks" | "static" | "railpack";
        railpackVersion: string | null;
        herokuVersion: string | null;
        publishDirectory: string | null;
        isStaticSpa: boolean | null;
        createEnvFile: boolean;
        registryId: string | null;
        rollbackRegistryId: string | null;
        buildServerId: string | null;
        buildRegistryId: string | null;
    } | null;
    schedule: {
        name: string;
        createdAt: string;
        userId: string | null;
        description: string | null;
        applicationId: string | null;
        serviceName: string | null;
        composeId: string | null;
        appName: string;
        command: string;
        serverId: string | null;
        enabled: boolean;
        scheduleType: "application" | "compose" | "server" | "dokploy-server";
        scheduleId: string;
        cronExpression: string;
        shellType: "bash" | "sh";
        script: string | null;
        timezone: string | null;
    } | null;
}>;
export declare const findDeploymentByApplicationId: (applicationId: string) => Promise<{
    createdAt: string;
    description: string | null;
    applicationId: string | null;
    composeId: string | null;
    serverId: string | null;
    title: string;
    buildServerId: string | null;
    previewDeploymentId: string | null;
    status: "running" | "done" | "error" | "cancelled" | null;
    deploymentId: string;
    logPath: string;
    pid: string | null;
    isPreviewDeployment: boolean | null;
    startedAt: string | null;
    finishedAt: string | null;
    errorMessage: string | null;
    scheduleId: string | null;
    backupId: string | null;
    rollbackId: string | null;
    volumeBackupId: string | null;
    initiatingActorType: "human" | "agent" | "plugin" | "system";
    initiatingActorId: string | null;
    gateStatus: "skipped" | "pending" | "approved" | "rejected" | "timed_out";
}>;
export declare const createDeployment: (deployment: Omit<z.infer<typeof apiCreateDeployment>, "deploymentId" | "createdAt" | "status" | "logPath">) => Promise<{
    createdAt: string;
    description: string | null;
    applicationId: string | null;
    composeId: string | null;
    serverId: string | null;
    title: string;
    buildServerId: string | null;
    previewDeploymentId: string | null;
    status: "running" | "done" | "error" | "cancelled" | null;
    deploymentId: string;
    logPath: string;
    pid: string | null;
    isPreviewDeployment: boolean | null;
    startedAt: string | null;
    finishedAt: string | null;
    errorMessage: string | null;
    scheduleId: string | null;
    backupId: string | null;
    rollbackId: string | null;
    volumeBackupId: string | null;
    initiatingActorType: "human" | "agent" | "plugin" | "system";
    initiatingActorId: string | null;
    gateStatus: "skipped" | "pending" | "approved" | "rejected" | "timed_out";
}>;
export declare const createDeploymentPreview: (deployment: Omit<z.infer<typeof apiCreateDeploymentPreview>, "deploymentId" | "createdAt" | "status" | "logPath">) => Promise<{
    createdAt: string;
    description: string | null;
    applicationId: string | null;
    composeId: string | null;
    serverId: string | null;
    title: string;
    buildServerId: string | null;
    previewDeploymentId: string | null;
    status: "running" | "done" | "error" | "cancelled" | null;
    deploymentId: string;
    logPath: string;
    pid: string | null;
    isPreviewDeployment: boolean | null;
    startedAt: string | null;
    finishedAt: string | null;
    errorMessage: string | null;
    scheduleId: string | null;
    backupId: string | null;
    rollbackId: string | null;
    volumeBackupId: string | null;
    initiatingActorType: "human" | "agent" | "plugin" | "system";
    initiatingActorId: string | null;
    gateStatus: "skipped" | "pending" | "approved" | "rejected" | "timed_out";
}>;
export declare const createDeploymentCompose: (deployment: Omit<z.infer<typeof apiCreateDeploymentCompose>, "deploymentId" | "createdAt" | "status" | "logPath">) => Promise<{
    createdAt: string;
    description: string | null;
    applicationId: string | null;
    composeId: string | null;
    serverId: string | null;
    title: string;
    buildServerId: string | null;
    previewDeploymentId: string | null;
    status: "running" | "done" | "error" | "cancelled" | null;
    deploymentId: string;
    logPath: string;
    pid: string | null;
    isPreviewDeployment: boolean | null;
    startedAt: string | null;
    finishedAt: string | null;
    errorMessage: string | null;
    scheduleId: string | null;
    backupId: string | null;
    rollbackId: string | null;
    volumeBackupId: string | null;
    initiatingActorType: "human" | "agent" | "plugin" | "system";
    initiatingActorId: string | null;
    gateStatus: "skipped" | "pending" | "approved" | "rejected" | "timed_out";
}>;
export declare const createDeploymentBackup: (deployment: Omit<z.infer<typeof apiCreateDeploymentBackup>, "deploymentId" | "createdAt" | "status" | "logPath">) => Promise<{
    createdAt: string;
    description: string | null;
    applicationId: string | null;
    composeId: string | null;
    serverId: string | null;
    title: string;
    buildServerId: string | null;
    previewDeploymentId: string | null;
    status: "running" | "done" | "error" | "cancelled" | null;
    deploymentId: string;
    logPath: string;
    pid: string | null;
    isPreviewDeployment: boolean | null;
    startedAt: string | null;
    finishedAt: string | null;
    errorMessage: string | null;
    scheduleId: string | null;
    backupId: string | null;
    rollbackId: string | null;
    volumeBackupId: string | null;
    initiatingActorType: "human" | "agent" | "plugin" | "system";
    initiatingActorId: string | null;
    gateStatus: "skipped" | "pending" | "approved" | "rejected" | "timed_out";
}>;
export declare const createDeploymentSchedule: (deployment: Omit<z.infer<typeof apiCreateDeploymentSchedule>, "deploymentId" | "createdAt" | "status" | "logPath">) => Promise<{
    createdAt: string;
    description: string | null;
    applicationId: string | null;
    composeId: string | null;
    serverId: string | null;
    title: string;
    buildServerId: string | null;
    previewDeploymentId: string | null;
    status: "running" | "done" | "error" | "cancelled" | null;
    deploymentId: string;
    logPath: string;
    pid: string | null;
    isPreviewDeployment: boolean | null;
    startedAt: string | null;
    finishedAt: string | null;
    errorMessage: string | null;
    scheduleId: string | null;
    backupId: string | null;
    rollbackId: string | null;
    volumeBackupId: string | null;
    initiatingActorType: "human" | "agent" | "plugin" | "system";
    initiatingActorId: string | null;
    gateStatus: "skipped" | "pending" | "approved" | "rejected" | "timed_out";
}>;
export declare const createDeploymentVolumeBackup: (deployment: Omit<z.infer<typeof apiCreateDeploymentVolumeBackup>, "deploymentId" | "createdAt" | "status" | "logPath">) => Promise<{
    createdAt: string;
    description: string | null;
    applicationId: string | null;
    composeId: string | null;
    serverId: string | null;
    title: string;
    buildServerId: string | null;
    previewDeploymentId: string | null;
    status: "running" | "done" | "error" | "cancelled" | null;
    deploymentId: string;
    logPath: string;
    pid: string | null;
    isPreviewDeployment: boolean | null;
    startedAt: string | null;
    finishedAt: string | null;
    errorMessage: string | null;
    scheduleId: string | null;
    backupId: string | null;
    rollbackId: string | null;
    volumeBackupId: string | null;
    initiatingActorType: "human" | "agent" | "plugin" | "system";
    initiatingActorId: string | null;
    gateStatus: "skipped" | "pending" | "approved" | "rejected" | "timed_out";
}>;
export declare const removeDeployment: (deploymentId: string) => Promise<{
    createdAt: string;
    description: string | null;
    applicationId: string | null;
    composeId: string | null;
    serverId: string | null;
    title: string;
    buildServerId: string | null;
    previewDeploymentId: string | null;
    status: "running" | "done" | "error" | "cancelled" | null;
    deploymentId: string;
    logPath: string;
    pid: string | null;
    isPreviewDeployment: boolean | null;
    startedAt: string | null;
    finishedAt: string | null;
    errorMessage: string | null;
    scheduleId: string | null;
    backupId: string | null;
    rollbackId: string | null;
    volumeBackupId: string | null;
    initiatingActorType: "human" | "agent" | "plugin" | "system";
    initiatingActorId: string | null;
    gateStatus: "skipped" | "pending" | "approved" | "rejected" | "timed_out";
} | null>;
export declare const removeDeploymentsByApplicationId: (applicationId: string) => Promise<void>;
export declare const removeDeployments: (application: Application) => Promise<void>;
export declare const removeDeploymentsByPreviewDeploymentId: (previewDeployment: PreviewDeployment, serverId: string | null) => Promise<void>;
export declare const removeDeploymentsByComposeId: (compose: Compose) => Promise<void>;
export declare const findAllDeploymentsByApplicationId: (applicationId: string) => Promise<{
    createdAt: string;
    description: string | null;
    applicationId: string | null;
    composeId: string | null;
    serverId: string | null;
    title: string;
    buildServerId: string | null;
    previewDeploymentId: string | null;
    status: "running" | "done" | "error" | "cancelled" | null;
    deploymentId: string;
    logPath: string;
    pid: string | null;
    isPreviewDeployment: boolean | null;
    startedAt: string | null;
    finishedAt: string | null;
    errorMessage: string | null;
    scheduleId: string | null;
    backupId: string | null;
    rollbackId: string | null;
    volumeBackupId: string | null;
    initiatingActorType: "human" | "agent" | "plugin" | "system";
    initiatingActorId: string | null;
    gateStatus: "skipped" | "pending" | "approved" | "rejected" | "timed_out";
}[]>;
export declare const findAllDeploymentsByComposeId: (composeId: string) => Promise<{
    createdAt: string;
    description: string | null;
    applicationId: string | null;
    composeId: string | null;
    serverId: string | null;
    title: string;
    buildServerId: string | null;
    previewDeploymentId: string | null;
    status: "running" | "done" | "error" | "cancelled" | null;
    deploymentId: string;
    logPath: string;
    pid: string | null;
    isPreviewDeployment: boolean | null;
    startedAt: string | null;
    finishedAt: string | null;
    errorMessage: string | null;
    scheduleId: string | null;
    backupId: string | null;
    rollbackId: string | null;
    volumeBackupId: string | null;
    initiatingActorType: "human" | "agent" | "plugin" | "system";
    initiatingActorId: string | null;
    gateStatus: "skipped" | "pending" | "approved" | "rejected" | "timed_out";
}[]>;
/**
 * All deployments for applications and compose in the org.
 * Pass accessedServices for members (only those services), null for owner/admin.
 */
export declare const findAllDeploymentsCentralized: (orgId: string, accessedServices: string[] | null) => Promise<{
    createdAt: string;
    description: string | null;
    applicationId: string | null;
    composeId: string | null;
    serverId: string | null;
    title: string;
    buildServerId: string | null;
    previewDeploymentId: string | null;
    status: "running" | "done" | "error" | "cancelled" | null;
    deploymentId: string;
    logPath: string;
    pid: string | null;
    isPreviewDeployment: boolean | null;
    startedAt: string | null;
    finishedAt: string | null;
    errorMessage: string | null;
    scheduleId: string | null;
    backupId: string | null;
    rollbackId: string | null;
    volumeBackupId: string | null;
    initiatingActorType: "human" | "agent" | "plugin" | "system";
    initiatingActorId: string | null;
    gateStatus: "skipped" | "pending" | "approved" | "rejected" | "timed_out";
    application: {
        name: string;
        applicationId: string;
        appName: string;
        environment: {
            name: string;
            environmentId: string;
            project: {
                name: string;
                projectId: string;
            };
        };
        server: {
            name: string;
            serverId: string;
            serverType: "deploy" | "build";
        } | null;
        buildServer: {
            name: string;
            serverId: string;
            serverType: "deploy" | "build";
        } | null;
    } | null;
    compose: {
        name: string;
        composeId: string;
        appName: string;
        environment: {
            name: string;
            environmentId: string;
            project: {
                name: string;
                projectId: string;
            };
        };
        server: {
            name: string;
            serverId: string;
            serverType: "deploy" | "build";
        } | null;
    } | null;
    server: {
        name: string;
        serverId: string;
        serverType: "deploy" | "build";
    } | null;
    buildServer: {
        name: string;
        serverId: string;
        serverType: "deploy" | "build";
    } | null;
}[]>;
export declare const updateDeployment: (deploymentId: string, deploymentData: Partial<Deployment>) => Promise<{
    deploymentId: string;
    title: string;
    description: string | null;
    status: "running" | "done" | "error" | "cancelled" | null;
    logPath: string;
    pid: string | null;
    applicationId: string | null;
    composeId: string | null;
    serverId: string | null;
    isPreviewDeployment: boolean | null;
    previewDeploymentId: string | null;
    createdAt: string;
    startedAt: string | null;
    finishedAt: string | null;
    errorMessage: string | null;
    scheduleId: string | null;
    backupId: string | null;
    rollbackId: string | null;
    volumeBackupId: string | null;
    buildServerId: string | null;
    initiatingActorType: "human" | "agent" | "plugin" | "system";
    initiatingActorId: string | null;
    gateStatus: "skipped" | "pending" | "approved" | "rejected" | "timed_out";
}[]>;
export declare const updateDeploymentStatus: (deploymentId: string, deploymentStatus: Deployment["status"]) => Promise<{
    deploymentId: string;
    title: string;
    description: string | null;
    status: "running" | "done" | "error" | "cancelled" | null;
    logPath: string;
    pid: string | null;
    applicationId: string | null;
    composeId: string | null;
    serverId: string | null;
    isPreviewDeployment: boolean | null;
    previewDeploymentId: string | null;
    createdAt: string;
    startedAt: string | null;
    finishedAt: string | null;
    errorMessage: string | null;
    scheduleId: string | null;
    backupId: string | null;
    rollbackId: string | null;
    volumeBackupId: string | null;
    buildServerId: string | null;
    initiatingActorType: "human" | "agent" | "plugin" | "system";
    initiatingActorId: string | null;
    gateStatus: "skipped" | "pending" | "approved" | "rejected" | "timed_out";
}[]>;
export declare const createServerDeployment: (deployment: Omit<z.infer<typeof apiCreateDeploymentServer>, "deploymentId" | "createdAt" | "status" | "logPath">) => Promise<{
    createdAt: string;
    description: string | null;
    applicationId: string | null;
    composeId: string | null;
    serverId: string | null;
    title: string;
    buildServerId: string | null;
    previewDeploymentId: string | null;
    status: "running" | "done" | "error" | "cancelled" | null;
    deploymentId: string;
    logPath: string;
    pid: string | null;
    isPreviewDeployment: boolean | null;
    startedAt: string | null;
    finishedAt: string | null;
    errorMessage: string | null;
    scheduleId: string | null;
    backupId: string | null;
    rollbackId: string | null;
    volumeBackupId: string | null;
    initiatingActorType: "human" | "agent" | "plugin" | "system";
    initiatingActorId: string | null;
    gateStatus: "skipped" | "pending" | "approved" | "rejected" | "timed_out";
}>;
export declare const removeLastFiveDeployments: (serverId: string) => Promise<void>;
export declare const removeDeploymentsByServerId: (server: Server) => Promise<void>;
export declare const findAllDeploymentsByServerId: (serverId: string) => Promise<{
    createdAt: string;
    description: string | null;
    applicationId: string | null;
    composeId: string | null;
    serverId: string | null;
    title: string;
    buildServerId: string | null;
    previewDeploymentId: string | null;
    status: "running" | "done" | "error" | "cancelled" | null;
    deploymentId: string;
    logPath: string;
    pid: string | null;
    isPreviewDeployment: boolean | null;
    startedAt: string | null;
    finishedAt: string | null;
    errorMessage: string | null;
    scheduleId: string | null;
    backupId: string | null;
    rollbackId: string | null;
    volumeBackupId: string | null;
    initiatingActorType: "human" | "agent" | "plugin" | "system";
    initiatingActorId: string | null;
    gateStatus: "skipped" | "pending" | "approved" | "rejected" | "timed_out";
}[]>;
export declare const clearOldDeployments: (appName: string, serverId: string | null) => Promise<void>;
//# sourceMappingURL=deployment.d.ts.map