import type { z } from "zod";
import { type apiCreateDomain, domains } from "../db/schema";
export type Domain = typeof domains.$inferSelect;
export declare const createDomain: (input: z.infer<typeof apiCreateDomain>) => Promise<{
    certificateType: "letsencrypt" | "none" | "custom";
    createdAt: string;
    applicationId: string | null;
    host: string;
    port: number | null;
    path: string | null;
    internalPath: string | null;
    stripPath: boolean;
    https: boolean;
    customCertResolver: string | null;
    middlewares: string[] | null;
    serviceName: string | null;
    domainType: "application" | "compose" | "preview" | null;
    domainId: string;
    customEntrypoint: string | null;
    uniqueConfigKey: number;
    composeId: string | null;
    previewDeploymentId: string | null;
}>;
export declare const generateTraefikMeDomain: (appName: string, _userId: string, serverId?: string) => Promise<string>;
export declare const generateWildcardDomain: (appName: string, serverDomain: string) => string;
export declare const findDomainById: (domainId: string) => Promise<{
    certificateType: "letsencrypt" | "none" | "custom";
    createdAt: string;
    applicationId: string | null;
    host: string;
    port: number | null;
    path: string | null;
    internalPath: string | null;
    stripPath: boolean;
    https: boolean;
    customCertResolver: string | null;
    middlewares: string[] | null;
    serviceName: string | null;
    domainType: "application" | "compose" | "preview" | null;
    domainId: string;
    customEntrypoint: string | null;
    uniqueConfigKey: number;
    composeId: string | null;
    previewDeploymentId: string | null;
    application: {
        applicationStatus: "idle" | "running" | "done" | "error";
        triggerType: "push" | "tag" | null;
        giteaId: string | null;
        name: string;
        createdAt: string;
        refreshToken: string | null;
        description: string | null;
        owner: string | null;
        githubId: string | null;
        gitlabId: string | null;
        applicationId: string;
        appName: string;
        env: string | null;
        sourceType: "gitea" | "github" | "gitlab" | "bitbucket" | "git" | "docker" | "drop";
        repository: string | null;
        branch: string | null;
        autoDeploy: boolean | null;
        gitlabProjectId: number | null;
        gitlabRepository: string | null;
        gitlabOwner: string | null;
        gitlabBranch: string | null;
        gitlabPathNamespace: string | null;
        bitbucketRepository: string | null;
        bitbucketRepositorySlug: string | null;
        bitbucketOwner: string | null;
        bitbucketBranch: string | null;
        giteaRepository: string | null;
        giteaOwner: string | null;
        giteaBranch: string | null;
        customGitUrl: string | null;
        customGitBranch: string | null;
        customGitSSHKeyId: string | null;
        command: string | null;
        enableSubmodules: boolean;
        environmentId: string;
        watchPaths: string[] | null;
        bitbucketId: string | null;
        serverId: string | null;
        username: string | null;
        previewEnv: string | null;
        previewBuildArgs: string | null;
        previewBuildSecrets: string | null;
        previewLabels: string[] | null;
        previewWildcard: string | null;
        previewPort: number | null;
        previewHttps: boolean;
        previewPath: string | null;
        previewCertificateType: "letsencrypt" | "none" | "custom";
        previewCustomCertResolver: string | null;
        previewLimit: number | null;
        isPreviewDeploymentsActive: boolean | null;
        previewRequireCollaboratorPermissions: boolean | null;
        rollbackActive: boolean | null;
        buildArgs: string | null;
        buildSecrets: string | null;
        memoryReservation: string | null;
        memoryLimit: string | null;
        cpuReservation: string | null;
        cpuLimit: string | null;
        title: string | null;
        enabled: boolean | null;
        subtitle: string | null;
        args: string[] | null;
        icon: string | null;
        cleanCache: boolean | null;
        buildPath: string | null;
        gitlabBuildPath: string | null;
        giteaBuildPath: string | null;
        bitbucketBuildPath: string | null;
        password: string | null;
        dockerImage: string | null;
        registryUrl: string | null;
        customGitBuildPath: string | null;
        dockerfile: string | null;
        dockerContextPath: string | null;
        dockerBuildStage: string | null;
        dropBuildPath: string | null;
        healthCheckSwarm: import("@undevops/server/db").HealthCheckSwarm | null;
        restartPolicySwarm: import("@undevops/server/db").RestartPolicySwarm | null;
        placementSwarm: import("@undevops/server/db").PlacementSwarm | null;
        updateConfigSwarm: import("@undevops/server/db").UpdateConfigSwarm | null;
        rollbackConfigSwarm: import("@undevops/server/db").UpdateConfigSwarm | null;
        modeSwarm: import("@undevops/server/db").ServiceModeSwarm | null;
        labelsSwarm: import("@undevops/server/db").LabelsSwarm | null;
        networkSwarm: import("@undevops/server/db").NetworkSwarm[] | null;
        stopGracePeriodSwarm: number | null;
        endpointSpecSwarm: import("@undevops/server/db").EndpointSpecSwarm | null;
        ulimitsSwarm: import("@undevops/server/db").UlimitsSwarm | null;
        replicas: number;
        buildType: "dockerfile" | "heroku_buildpacks" | "paketo_buildpacks" | "nixpacks" | "static" | "railpack";
        railpackVersion: string | null;
        herokuVersion: string | null;
        publishDirectory: string | null;
        isStaticSpa: boolean | null;
        createEnvFile: boolean;
        registryId: string | null;
        rollbackRegistryId: string | null;
        buildServerId: string | null;
        buildRegistryId: string | null;
    } | null;
}>;
export declare const findDomainsByApplicationId: (applicationId: string) => Promise<{
    certificateType: "letsencrypt" | "none" | "custom";
    createdAt: string;
    applicationId: string | null;
    host: string;
    port: number | null;
    path: string | null;
    internalPath: string | null;
    stripPath: boolean;
    https: boolean;
    customCertResolver: string | null;
    middlewares: string[] | null;
    serviceName: string | null;
    domainType: "application" | "compose" | "preview" | null;
    domainId: string;
    customEntrypoint: string | null;
    uniqueConfigKey: number;
    composeId: string | null;
    previewDeploymentId: string | null;
    application: {
        applicationStatus: "idle" | "running" | "done" | "error";
        triggerType: "push" | "tag" | null;
        giteaId: string | null;
        name: string;
        createdAt: string;
        refreshToken: string | null;
        description: string | null;
        owner: string | null;
        githubId: string | null;
        gitlabId: string | null;
        applicationId: string;
        appName: string;
        env: string | null;
        sourceType: "gitea" | "github" | "gitlab" | "bitbucket" | "git" | "docker" | "drop";
        repository: string | null;
        branch: string | null;
        autoDeploy: boolean | null;
        gitlabProjectId: number | null;
        gitlabRepository: string | null;
        gitlabOwner: string | null;
        gitlabBranch: string | null;
        gitlabPathNamespace: string | null;
        bitbucketRepository: string | null;
        bitbucketRepositorySlug: string | null;
        bitbucketOwner: string | null;
        bitbucketBranch: string | null;
        giteaRepository: string | null;
        giteaOwner: string | null;
        giteaBranch: string | null;
        customGitUrl: string | null;
        customGitBranch: string | null;
        customGitSSHKeyId: string | null;
        command: string | null;
        enableSubmodules: boolean;
        environmentId: string;
        watchPaths: string[] | null;
        bitbucketId: string | null;
        serverId: string | null;
        username: string | null;
        previewEnv: string | null;
        previewBuildArgs: string | null;
        previewBuildSecrets: string | null;
        previewLabels: string[] | null;
        previewWildcard: string | null;
        previewPort: number | null;
        previewHttps: boolean;
        previewPath: string | null;
        previewCertificateType: "letsencrypt" | "none" | "custom";
        previewCustomCertResolver: string | null;
        previewLimit: number | null;
        isPreviewDeploymentsActive: boolean | null;
        previewRequireCollaboratorPermissions: boolean | null;
        rollbackActive: boolean | null;
        buildArgs: string | null;
        buildSecrets: string | null;
        memoryReservation: string | null;
        memoryLimit: string | null;
        cpuReservation: string | null;
        cpuLimit: string | null;
        title: string | null;
        enabled: boolean | null;
        subtitle: string | null;
        args: string[] | null;
        icon: string | null;
        cleanCache: boolean | null;
        buildPath: string | null;
        gitlabBuildPath: string | null;
        giteaBuildPath: string | null;
        bitbucketBuildPath: string | null;
        password: string | null;
        dockerImage: string | null;
        registryUrl: string | null;
        customGitBuildPath: string | null;
        dockerfile: string | null;
        dockerContextPath: string | null;
        dockerBuildStage: string | null;
        dropBuildPath: string | null;
        healthCheckSwarm: import("@undevops/server/db").HealthCheckSwarm | null;
        restartPolicySwarm: import("@undevops/server/db").RestartPolicySwarm | null;
        placementSwarm: import("@undevops/server/db").PlacementSwarm | null;
        updateConfigSwarm: import("@undevops/server/db").UpdateConfigSwarm | null;
        rollbackConfigSwarm: import("@undevops/server/db").UpdateConfigSwarm | null;
        modeSwarm: import("@undevops/server/db").ServiceModeSwarm | null;
        labelsSwarm: import("@undevops/server/db").LabelsSwarm | null;
        networkSwarm: import("@undevops/server/db").NetworkSwarm[] | null;
        stopGracePeriodSwarm: number | null;
        endpointSpecSwarm: import("@undevops/server/db").EndpointSpecSwarm | null;
        ulimitsSwarm: import("@undevops/server/db").UlimitsSwarm | null;
        replicas: number;
        buildType: "dockerfile" | "heroku_buildpacks" | "paketo_buildpacks" | "nixpacks" | "static" | "railpack";
        railpackVersion: string | null;
        herokuVersion: string | null;
        publishDirectory: string | null;
        isStaticSpa: boolean | null;
        createEnvFile: boolean;
        registryId: string | null;
        rollbackRegistryId: string | null;
        buildServerId: string | null;
        buildRegistryId: string | null;
    } | null;
}[]>;
export declare const findDomainsByComposeId: (composeId: string) => Promise<{
    certificateType: "letsencrypt" | "none" | "custom";
    createdAt: string;
    applicationId: string | null;
    host: string;
    port: number | null;
    path: string | null;
    internalPath: string | null;
    stripPath: boolean;
    https: boolean;
    customCertResolver: string | null;
    middlewares: string[] | null;
    serviceName: string | null;
    domainType: "application" | "compose" | "preview" | null;
    domainId: string;
    customEntrypoint: string | null;
    uniqueConfigKey: number;
    composeId: string | null;
    previewDeploymentId: string | null;
    compose: {
        triggerType: "push" | "tag" | null;
        giteaId: string | null;
        name: string;
        createdAt: string;
        refreshToken: string | null;
        description: string | null;
        owner: string | null;
        githubId: string | null;
        gitlabId: string | null;
        composeId: string;
        appName: string;
        env: string | null;
        composeFile: string;
        sourceType: "gitea" | "github" | "gitlab" | "bitbucket" | "raw" | "git";
        composeType: "docker-compose" | "stack";
        repository: string | null;
        branch: string | null;
        autoDeploy: boolean | null;
        gitlabProjectId: number | null;
        gitlabRepository: string | null;
        gitlabOwner: string | null;
        gitlabBranch: string | null;
        gitlabPathNamespace: string | null;
        bitbucketRepository: string | null;
        bitbucketRepositorySlug: string | null;
        bitbucketOwner: string | null;
        bitbucketBranch: string | null;
        giteaRepository: string | null;
        giteaOwner: string | null;
        giteaBranch: string | null;
        customGitUrl: string | null;
        customGitBranch: string | null;
        customGitSSHKeyId: string | null;
        command: string;
        enableSubmodules: boolean;
        composePath: string;
        suffix: string;
        randomize: boolean;
        isolatedDeployment: boolean;
        isolatedDeploymentsVolume: boolean;
        composeStatus: "idle" | "running" | "done" | "error";
        environmentId: string;
        watchPaths: string[] | null;
        bitbucketId: string | null;
        serverId: string | null;
    } | null;
}[]>;
export declare const updateDomainById: (domainId: string, domainData: Partial<Domain>) => Promise<{
    domainId: string;
    host: string;
    https: boolean;
    port: number | null;
    customEntrypoint: string | null;
    path: string | null;
    serviceName: string | null;
    domainType: "application" | "compose" | "preview" | null;
    uniqueConfigKey: number;
    createdAt: string;
    composeId: string | null;
    customCertResolver: string | null;
    applicationId: string | null;
    previewDeploymentId: string | null;
    certificateType: "letsencrypt" | "none" | "custom";
    internalPath: string | null;
    stripPath: boolean;
    middlewares: string[] | null;
}>;
export declare const removeDomainById: (domainId: string) => Promise<{
    certificateType: "letsencrypt" | "none" | "custom";
    createdAt: string;
    applicationId: string | null;
    host: string;
    port: number | null;
    path: string | null;
    internalPath: string | null;
    stripPath: boolean;
    https: boolean;
    customCertResolver: string | null;
    middlewares: string[] | null;
    serviceName: string | null;
    domainType: "application" | "compose" | "preview" | null;
    domainId: string;
    customEntrypoint: string | null;
    uniqueConfigKey: number;
    composeId: string | null;
    previewDeploymentId: string | null;
}>;
export declare const getDomainHost: (domain: Domain) => string;
export declare const validateDomain: (domain: string, expectedIp?: string) => Promise<{
    isValid: boolean;
    resolvedIp?: string;
    error?: string;
    isCloudflare?: boolean;
    cdnProvider?: string;
}>;
//# sourceMappingURL=domain.d.ts.map