import { type apiCreateEnvironment, type apiDuplicateEnvironment, environments } from "@undevops/server/db/schema";
import type { z } from "zod";
export type Environment = typeof environments.$inferSelect;
export declare const createEnvironment: (input: z.infer<typeof apiCreateEnvironment>) => Promise<{
    name: string;
    createdAt: string;
    description: string | null;
    env: string;
    environmentId: string;
    projectId: string;
    isDefault: boolean;
    gatePolicy: "disabled" | "single" | "unanimous" | "manual_only";
    reviewerIds: string[];
    autoApproveAgents: boolean;
}>;
export declare const findEnvironmentById: (environmentId: string) => Promise<{
    name: string;
    description: string | null;
    env: string;
    environmentId: string;
    projectId: string;
    isDefault: boolean;
    project: {
        name: string;
        createdAt: string;
        organizationId: string;
        description: string | null;
        env: string;
        projectId: string;
    };
    compose: {
        name: string;
        createdAt: string;
        description: string | null;
        composeId: string;
        composeStatus: "idle" | "running" | "done" | "error";
        serverId: string | null;
        server: {
            name: string;
            serverId: string;
        } | null;
    }[];
    mysql: {
        applicationStatus: "idle" | "running" | "done" | "error";
        name: string;
        createdAt: string;
        description: string | null;
        serverId: string | null;
        mysqlId: string;
        server: {
            name: string;
            serverId: string;
        } | null;
    }[];
    applications: {
        applicationStatus: "idle" | "running" | "done" | "error";
        name: string;
        createdAt: string;
        description: string | null;
        applicationId: string;
        serverId: string | null;
        icon: string | null;
        server: {
            name: string;
            serverId: string;
        } | null;
    }[];
    libsql: {
        applicationStatus: "idle" | "running" | "done" | "error";
        name: string;
        createdAt: string;
        description: string | null;
        serverId: string | null;
        libsqlId: string;
        server: {
            name: string;
            serverId: string;
        } | null;
    }[];
    mariadb: {
        applicationStatus: "idle" | "running" | "done" | "error";
        name: string;
        createdAt: string;
        description: string | null;
        serverId: string | null;
        mariadbId: string;
        server: {
            name: string;
            serverId: string;
        } | null;
    }[];
    mongo: {
        applicationStatus: "idle" | "running" | "done" | "error";
        name: string;
        createdAt: string;
        description: string | null;
        serverId: string | null;
        mongoId: string;
        server: {
            name: string;
            serverId: string;
        } | null;
    }[];
    postgres: {
        applicationStatus: "idle" | "running" | "done" | "error";
        name: string;
        createdAt: string;
        description: string | null;
        serverId: string | null;
        postgresId: string;
        server: {
            name: string;
            serverId: string;
        } | null;
    }[];
    redis: {
        applicationStatus: "idle" | "running" | "done" | "error";
        name: string;
        createdAt: string;
        description: string | null;
        serverId: string | null;
        redisId: string;
        server: {
            name: string;
            serverId: string;
        } | null;
    }[];
}>;
export declare const findEnvironmentsByProjectId: (projectId: string) => Promise<{
    name: string;
    description: string | null;
    environmentId: string;
    isDefault: boolean;
    project: {
        name: string;
        createdAt: string;
        organizationId: string;
        description: string | null;
        env: string;
        projectId: string;
    };
    compose: {
        triggerType: "push" | "tag" | null;
        giteaId: string | null;
        name: string;
        createdAt: string;
        refreshToken: string | null;
        description: string | null;
        owner: string | null;
        githubId: string | null;
        gitlabId: string | null;
        composeId: string;
        appName: string;
        env: string | null;
        composeFile: string;
        sourceType: "gitea" | "github" | "gitlab" | "bitbucket" | "raw" | "git";
        composeType: "docker-compose" | "stack";
        repository: string | null;
        branch: string | null;
        autoDeploy: boolean | null;
        gitlabProjectId: number | null;
        gitlabRepository: string | null;
        gitlabOwner: string | null;
        gitlabBranch: string | null;
        gitlabPathNamespace: string | null;
        bitbucketRepository: string | null;
        bitbucketRepositorySlug: string | null;
        bitbucketOwner: string | null;
        bitbucketBranch: string | null;
        giteaRepository: string | null;
        giteaOwner: string | null;
        giteaBranch: string | null;
        customGitUrl: string | null;
        customGitBranch: string | null;
        customGitSSHKeyId: string | null;
        command: string;
        enableSubmodules: boolean;
        composePath: string;
        suffix: string;
        randomize: boolean;
        isolatedDeployment: boolean;
        isolatedDeploymentsVolume: boolean;
        composeStatus: "idle" | "running" | "done" | "error";
        environmentId: string;
        watchPaths: string[] | null;
        bitbucketId: string | null;
        serverId: string | null;
    }[];
    mysql: {
        applicationStatus: "idle" | "running" | "done" | "error";
        name: string;
        createdAt: string;
        description: string | null;
        appName: string;
        env: string | null;
        command: string | null;
        environmentId: string;
        serverId: string | null;
        memoryReservation: string | null;
        memoryLimit: string | null;
        cpuReservation: string | null;
        cpuLimit: string | null;
        args: string[] | null;
        dockerImage: string;
        healthCheckSwarm: import("@undevops/server/db").HealthCheckSwarm | null;
        restartPolicySwarm: import("@undevops/server/db").RestartPolicySwarm | null;
        placementSwarm: import("@undevops/server/db").PlacementSwarm | null;
        updateConfigSwarm: import("@undevops/server/db").UpdateConfigSwarm | null;
        rollbackConfigSwarm: import("@undevops/server/db").UpdateConfigSwarm | null;
        modeSwarm: import("@undevops/server/db").ServiceModeSwarm | null;
        labelsSwarm: import("@undevops/server/db").LabelsSwarm | null;
        networkSwarm: import("@undevops/server/db").NetworkSwarm[] | null;
        stopGracePeriodSwarm: number | null;
        endpointSpecSwarm: import("@undevops/server/db").EndpointSpecSwarm | null;
        ulimitsSwarm: import("@undevops/server/db").UlimitsSwarm | null;
        replicas: number;
        mysqlId: string;
        databaseName: string;
        databaseUser: string;
        databasePassword: string;
        databaseRootPassword: string;
        externalPort: number | null;
    }[];
    applications: {
        applicationStatus: "idle" | "running" | "done" | "error";
        triggerType: "push" | "tag" | null;
        giteaId: string | null;
        name: string;
        createdAt: string;
        refreshToken: string | null;
        description: string | null;
        owner: string | null;
        githubId: string | null;
        gitlabId: string | null;
        applicationId: string;
        appName: string;
        env: string | null;
        sourceType: "gitea" | "github" | "gitlab" | "bitbucket" | "git" | "docker" | "drop";
        repository: string | null;
        branch: string | null;
        autoDeploy: boolean | null;
        gitlabProjectId: number | null;
        gitlabRepository: string | null;
        gitlabOwner: string | null;
        gitlabBranch: string | null;
        gitlabPathNamespace: string | null;
        bitbucketRepository: string | null;
        bitbucketRepositorySlug: string | null;
        bitbucketOwner: string | null;
        bitbucketBranch: string | null;
        giteaRepository: string | null;
        giteaOwner: string | null;
        giteaBranch: string | null;
        customGitUrl: string | null;
        customGitBranch: string | null;
        customGitSSHKeyId: string | null;
        command: string | null;
        enableSubmodules: boolean;
        environmentId: string;
        watchPaths: string[] | null;
        bitbucketId: string | null;
        serverId: string | null;
        username: string | null;
        previewEnv: string | null;
        previewBuildArgs: string | null;
        previewBuildSecrets: string | null;
        previewLabels: string[] | null;
        previewWildcard: string | null;
        previewPort: number | null;
        previewHttps: boolean;
        previewPath: string | null;
        previewCertificateType: "letsencrypt" | "none" | "custom";
        previewCustomCertResolver: string | null;
        previewLimit: number | null;
        isPreviewDeploymentsActive: boolean | null;
        previewRequireCollaboratorPermissions: boolean | null;
        rollbackActive: boolean | null;
        buildArgs: string | null;
        buildSecrets: string | null;
        memoryReservation: string | null;
        memoryLimit: string | null;
        cpuReservation: string | null;
        cpuLimit: string | null;
        title: string | null;
        enabled: boolean | null;
        subtitle: string | null;
        args: string[] | null;
        icon: string | null;
        cleanCache: boolean | null;
        buildPath: string | null;
        gitlabBuildPath: string | null;
        giteaBuildPath: string | null;
        bitbucketBuildPath: string | null;
        password: string | null;
        dockerImage: string | null;
        registryUrl: string | null;
        customGitBuildPath: string | null;
        dockerfile: string | null;
        dockerContextPath: string | null;
        dockerBuildStage: string | null;
        dropBuildPath: string | null;
        healthCheckSwarm: import("@undevops/server/db").HealthCheckSwarm | null;
        restartPolicySwarm: import("@undevops/server/db").RestartPolicySwarm | null;
        placementSwarm: import("@undevops/server/db").PlacementSwarm | null;
        updateConfigSwarm: import("@undevops/server/db").UpdateConfigSwarm | null;
        rollbackConfigSwarm: import("@undevops/server/db").UpdateConfigSwarm | null;
        modeSwarm: import("@undevops/server/db").ServiceModeSwarm | null;
        labelsSwarm: import("@undevops/server/db").LabelsSwarm | null;
        networkSwarm: import("@undevops/server/db").NetworkSwarm[] | null;
        stopGracePeriodSwarm: number | null;
        endpointSpecSwarm: import("@undevops/server/db").EndpointSpecSwarm | null;
        ulimitsSwarm: import("@undevops/server/db").UlimitsSwarm | null;
        replicas: number;
        buildType: "dockerfile" | "heroku_buildpacks" | "paketo_buildpacks" | "nixpacks" | "static" | "railpack";
        railpackVersion: string | null;
        herokuVersion: string | null;
        publishDirectory: string | null;
        isStaticSpa: boolean | null;
        createEnvFile: boolean;
        registryId: string | null;
        rollbackRegistryId: string | null;
        buildServerId: string | null;
        buildRegistryId: string | null;
    }[];
    libsql: {
        applicationStatus: "idle" | "running" | "done" | "error";
        sqldNode: "primary" | "replica";
        name: string;
        createdAt: string;
        description: string | null;
        appName: string;
        env: string | null;
        command: string | null;
        environmentId: string;
        serverId: string | null;
        memoryReservation: string | null;
        memoryLimit: string | null;
        cpuReservation: string | null;
        cpuLimit: string | null;
        dockerImage: string;
        healthCheckSwarm: import("@undevops/server/db").HealthCheckSwarm | null;
        restartPolicySwarm: import("@undevops/server/db").RestartPolicySwarm | null;
        placementSwarm: import("@undevops/server/db").PlacementSwarm | null;
        updateConfigSwarm: import("@undevops/server/db").UpdateConfigSwarm | null;
        rollbackConfigSwarm: import("@undevops/server/db").UpdateConfigSwarm | null;
        modeSwarm: import("@undevops/server/db").ServiceModeSwarm | null;
        labelsSwarm: import("@undevops/server/db").LabelsSwarm | null;
        networkSwarm: import("@undevops/server/db").NetworkSwarm[] | null;
        stopGracePeriodSwarm: number | null;
        endpointSpecSwarm: import("@undevops/server/db").EndpointSpecSwarm | null;
        replicas: number;
        databaseUser: string;
        databasePassword: string;
        externalPort: number | null;
        libsqlId: string;
        sqldPrimaryUrl: string | null;
        enableNamespaces: boolean;
        externalGRPCPort: number | null;
        externalAdminPort: number | null;
    }[];
    mariadb: {
        applicationStatus: "idle" | "running" | "done" | "error";
        name: string;
        createdAt: string;
        description: string | null;
        appName: string;
        env: string | null;
        command: string | null;
        environmentId: string;
        serverId: string | null;
        memoryReservation: string | null;
        memoryLimit: string | null;
        cpuReservation: string | null;
        cpuLimit: string | null;
        args: string[] | null;
        dockerImage: string;
        healthCheckSwarm: import("@undevops/server/db").HealthCheckSwarm | null;
        restartPolicySwarm: import("@undevops/server/db").RestartPolicySwarm | null;
        placementSwarm: import("@undevops/server/db").PlacementSwarm | null;
        updateConfigSwarm: import("@undevops/server/db").UpdateConfigSwarm | null;
        rollbackConfigSwarm: import("@undevops/server/db").UpdateConfigSwarm | null;
        modeSwarm: import("@undevops/server/db").ServiceModeSwarm | null;
        labelsSwarm: import("@undevops/server/db").LabelsSwarm | null;
        networkSwarm: import("@undevops/server/db").NetworkSwarm[] | null;
        stopGracePeriodSwarm: number | null;
        endpointSpecSwarm: import("@undevops/server/db").EndpointSpecSwarm | null;
        ulimitsSwarm: import("@undevops/server/db").UlimitsSwarm | null;
        replicas: number;
        databaseName: string;
        databaseUser: string;
        databasePassword: string;
        databaseRootPassword: string;
        externalPort: number | null;
        mariadbId: string;
    }[];
    mongo: {
        applicationStatus: "idle" | "running" | "done" | "error";
        name: string;
        createdAt: string;
        description: string | null;
        appName: string;
        env: string | null;
        command: string | null;
        environmentId: string;
        serverId: string | null;
        memoryReservation: string | null;
        memoryLimit: string | null;
        cpuReservation: string | null;
        cpuLimit: string | null;
        args: string[] | null;
        dockerImage: string;
        healthCheckSwarm: import("@undevops/server/db").HealthCheckSwarm | null;
        restartPolicySwarm: import("@undevops/server/db").RestartPolicySwarm | null;
        placementSwarm: import("@undevops/server/db").PlacementSwarm | null;
        updateConfigSwarm: import("@undevops/server/db").UpdateConfigSwarm | null;
        rollbackConfigSwarm: import("@undevops/server/db").UpdateConfigSwarm | null;
        modeSwarm: import("@undevops/server/db").ServiceModeSwarm | null;
        labelsSwarm: import("@undevops/server/db").LabelsSwarm | null;
        networkSwarm: import("@undevops/server/db").NetworkSwarm[] | null;
        stopGracePeriodSwarm: number | null;
        endpointSpecSwarm: import("@undevops/server/db").EndpointSpecSwarm | null;
        ulimitsSwarm: import("@undevops/server/db").UlimitsSwarm | null;
        replicas: number;
        databaseUser: string;
        databasePassword: string;
        externalPort: number | null;
        mongoId: string;
        replicaSets: boolean | null;
    }[];
    postgres: {
        applicationStatus: "idle" | "running" | "done" | "error";
        name: string;
        createdAt: string;
        description: string | null;
        appName: string;
        env: string | null;
        command: string | null;
        environmentId: string;
        serverId: string | null;
        memoryReservation: string | null;
        memoryLimit: string | null;
        cpuReservation: string | null;
        cpuLimit: string | null;
        args: string[] | null;
        dockerImage: string;
        healthCheckSwarm: import("@undevops/server/db").HealthCheckSwarm | null;
        restartPolicySwarm: import("@undevops/server/db").RestartPolicySwarm | null;
        placementSwarm: import("@undevops/server/db").PlacementSwarm | null;
        updateConfigSwarm: import("@undevops/server/db").UpdateConfigSwarm | null;
        rollbackConfigSwarm: import("@undevops/server/db").UpdateConfigSwarm | null;
        modeSwarm: import("@undevops/server/db").ServiceModeSwarm | null;
        labelsSwarm: import("@undevops/server/db").LabelsSwarm | null;
        networkSwarm: import("@undevops/server/db").NetworkSwarm[] | null;
        stopGracePeriodSwarm: number | null;
        endpointSpecSwarm: import("@undevops/server/db").EndpointSpecSwarm | null;
        ulimitsSwarm: import("@undevops/server/db").UlimitsSwarm | null;
        replicas: number;
        databaseName: string;
        databaseUser: string;
        databasePassword: string;
        externalPort: number | null;
        postgresId: string;
    }[];
    redis: {
        applicationStatus: "idle" | "running" | "done" | "error";
        name: string;
        createdAt: string;
        description: string | null;
        appName: string;
        env: string | null;
        command: string | null;
        environmentId: string;
        serverId: string | null;
        memoryReservation: string | null;
        memoryLimit: string | null;
        cpuReservation: string | null;
        cpuLimit: string | null;
        args: string[] | null;
        dockerImage: string;
        healthCheckSwarm: import("@undevops/server/db").HealthCheckSwarm | null;
        restartPolicySwarm: import("@undevops/server/db").RestartPolicySwarm | null;
        placementSwarm: import("@undevops/server/db").PlacementSwarm | null;
        updateConfigSwarm: import("@undevops/server/db").UpdateConfigSwarm | null;
        rollbackConfigSwarm: import("@undevops/server/db").UpdateConfigSwarm | null;
        modeSwarm: import("@undevops/server/db").ServiceModeSwarm | null;
        labelsSwarm: import("@undevops/server/db").LabelsSwarm | null;
        networkSwarm: import("@undevops/server/db").NetworkSwarm[] | null;
        stopGracePeriodSwarm: number | null;
        endpointSpecSwarm: import("@undevops/server/db").EndpointSpecSwarm | null;
        ulimitsSwarm: import("@undevops/server/db").UlimitsSwarm | null;
        replicas: number;
        databasePassword: string;
        externalPort: number | null;
        redisId: string;
    }[];
}[]>;
export declare const deleteEnvironment: (environmentId: string) => Promise<{
    name: string;
    createdAt: string;
    description: string | null;
    env: string;
    environmentId: string;
    projectId: string;
    isDefault: boolean;
    gatePolicy: "disabled" | "single" | "unanimous" | "manual_only";
    reviewerIds: string[];
    autoApproveAgents: boolean;
}>;
export declare const updateEnvironmentById: (environmentId: string, environmentData: Partial<Environment>) => Promise<{
    environmentId: string;
    name: string;
    description: string | null;
    createdAt: string;
    env: string;
    projectId: string;
    isDefault: boolean;
    gatePolicy: "disabled" | "single" | "unanimous" | "manual_only";
    reviewerIds: string[];
    autoApproveAgents: boolean;
}>;
export declare const duplicateEnvironment: (input: z.infer<typeof apiDuplicateEnvironment>) => Promise<{
    name: string;
    createdAt: string;
    description: string | null;
    env: string;
    environmentId: string;
    projectId: string;
    isDefault: boolean;
    gatePolicy: "disabled" | "single" | "unanimous" | "manual_only";
    reviewerIds: string[];
    autoApproveAgents: boolean;
}>;
export declare const createProductionEnvironment: (projectId: string) => Promise<{
    name: string;
    createdAt: string;
    description: string | null;
    env: string;
    environmentId: string;
    projectId: string;
    isDefault: boolean;
    gatePolicy: "disabled" | "single" | "unanimous" | "manual_only";
    reviewerIds: string[];
    autoApproveAgents: boolean;
}>;
//# sourceMappingURL=environment.d.ts.map