import { type apiCreatePort, ports } from "@undevops/server/db/schema";
import type { z } from "zod";
export type Port = typeof ports.$inferSelect;
export declare const createPort: (input: z.infer<typeof apiCreatePort>) => Promise<{
    applicationId: string;
    protocol: "tcp" | "udp";
    portId: string;
    publishedPort: number;
    publishMode: "host" | "ingress";
    targetPort: number;
}>;
export declare const finPortById: (portId: string) => Promise<{
    applicationId: string;
    protocol: "tcp" | "udp";
    portId: string;
    publishedPort: number;
    publishMode: "host" | "ingress";
    targetPort: number;
    application: {
        applicationStatus: "idle" | "running" | "done" | "error";
        triggerType: "push" | "tag" | null;
        giteaId: string | null;
        name: string;
        createdAt: string;
        refreshToken: string | null;
        description: string | null;
        owner: string | null;
        githubId: string | null;
        gitlabId: string | null;
        applicationId: string;
        appName: string;
        env: string | null;
        sourceType: "gitea" | "github" | "gitlab" | "bitbucket" | "git" | "docker" | "drop";
        repository: string | null;
        branch: string | null;
        autoDeploy: boolean | null;
        gitlabProjectId: number | null;
        gitlabRepository: string | null;
        gitlabOwner: string | null;
        gitlabBranch: string | null;
        gitlabPathNamespace: string | null;
        bitbucketRepository: string | null;
        bitbucketRepositorySlug: string | null;
        bitbucketOwner: string | null;
        bitbucketBranch: string | null;
        giteaRepository: string | null;
        giteaOwner: string | null;
        giteaBranch: string | null;
        customGitUrl: string | null;
        customGitBranch: string | null;
        customGitSSHKeyId: string | null;
        command: string | null;
        enableSubmodules: boolean;
        environmentId: string;
        watchPaths: string[] | null;
        bitbucketId: string | null;
        serverId: string | null;
        username: string | null;
        previewEnv: string | null;
        previewBuildArgs: string | null;
        previewBuildSecrets: string | null;
        previewLabels: string[] | null;
        previewWildcard: string | null;
        previewPort: number | null;
        previewHttps: boolean;
        previewPath: string | null;
        previewCertificateType: "letsencrypt" | "none" | "custom";
        previewCustomCertResolver: string | null;
        previewLimit: number | null;
        isPreviewDeploymentsActive: boolean | null;
        previewRequireCollaboratorPermissions: boolean | null;
        rollbackActive: boolean | null;
        buildArgs: string | null;
        buildSecrets: string | null;
        memoryReservation: string | null;
        memoryLimit: string | null;
        cpuReservation: string | null;
        cpuLimit: string | null;
        title: string | null;
        enabled: boolean | null;
        subtitle: string | null;
        args: string[] | null;
        icon: string | null;
        cleanCache: boolean | null;
        buildPath: string | null;
        gitlabBuildPath: string | null;
        giteaBuildPath: string | null;
        bitbucketBuildPath: string | null;
        password: string | null;
        dockerImage: string | null;
        registryUrl: string | null;
        customGitBuildPath: string | null;
        dockerfile: string | null;
        dockerContextPath: string | null;
        dockerBuildStage: string | null;
        dropBuildPath: string | null;
        healthCheckSwarm: import("@undevops/server/db").HealthCheckSwarm | null;
        restartPolicySwarm: import("@undevops/server/db").RestartPolicySwarm | null;
        placementSwarm: import("@undevops/server/db").PlacementSwarm | null;
        updateConfigSwarm: import("@undevops/server/db").UpdateConfigSwarm | null;
        rollbackConfigSwarm: import("@undevops/server/db").UpdateConfigSwarm | null;
        modeSwarm: import("@undevops/server/db").ServiceModeSwarm | null;
        labelsSwarm: import("@undevops/server/db").LabelsSwarm | null;
        networkSwarm: import("@undevops/server/db").NetworkSwarm[] | null;
        stopGracePeriodSwarm: number | null;
        endpointSpecSwarm: import("@undevops/server/db").EndpointSpecSwarm | null;
        ulimitsSwarm: import("@undevops/server/db").UlimitsSwarm | null;
        replicas: number;
        buildType: "dockerfile" | "heroku_buildpacks" | "paketo_buildpacks" | "nixpacks" | "static" | "railpack";
        railpackVersion: string | null;
        herokuVersion: string | null;
        publishDirectory: string | null;
        isStaticSpa: boolean | null;
        createEnvFile: boolean;
        registryId: string | null;
        rollbackRegistryId: string | null;
        buildServerId: string | null;
        buildRegistryId: string | null;
        environment: {
            name: string;
            createdAt: string;
            description: string | null;
            env: string;
            environmentId: string;
            projectId: string;
            isDefault: boolean;
            gatePolicy: "disabled" | "single" | "unanimous" | "manual_only";
            reviewerIds: string[];
            autoApproveAgents: boolean;
            project: {
                name: string;
                createdAt: string;
                organizationId: string;
                description: string | null;
                env: string;
                projectId: string;
            };
        };
    };
}>;
export declare const removePortById: (portId: string) => Promise<{
    applicationId: string;
    protocol: "tcp" | "udp";
    portId: string;
    publishedPort: number;
    publishMode: "host" | "ingress";
    targetPort: number;
}>;
export declare const updatePortById: (portId: string, portData: Partial<Port>) => Promise<{
    portId: string;
    publishedPort: number;
    publishMode: "host" | "ingress";
    targetPort: number;
    protocol: "tcp" | "udp";
    applicationId: string;
}>;
//# sourceMappingURL=port.d.ts.map