import { type apiCreatePreviewDeployment, previewDeployments } from "@undevops/server/db/schema";
import type { z } from "zod";
export type PreviewDeployment = typeof previewDeployments.$inferSelect;
export declare const findPreviewDeploymentById: (previewDeploymentId: string) => Promise<{
    createdAt: string;
    expiresAt: string | null;
    applicationId: string;
    domainId: string | null;
    appName: string;
    branch: string;
    previewDeploymentId: string;
    pullRequestId: string;
    pullRequestNumber: string;
    pullRequestURL: string;
    pullRequestTitle: string;
    pullRequestCommentId: string;
    previewStatus: "idle" | "running" | "done" | "error";
    application: {
        applicationId: string;
        serverId: string | null;
    };
    domain: {
        certificateType: "letsencrypt" | "none" | "custom";
        createdAt: string;
        applicationId: string | null;
        host: string;
        port: number | null;
        path: string | null;
        internalPath: string | null;
        stripPath: boolean;
        https: boolean;
        customCertResolver: string | null;
        middlewares: string[] | null;
        serviceName: string | null;
        domainType: "application" | "compose" | "preview" | null;
        domainId: string;
        customEntrypoint: string | null;
        uniqueConfigKey: number;
        composeId: string | null;
        previewDeploymentId: string | null;
    } | null;
}>;
export declare const removePreviewDeployment: (previewDeploymentId: string) => Promise<{
    createdAt: string;
    expiresAt: string | null;
    applicationId: string;
    domainId: string | null;
    appName: string;
    branch: string;
    previewDeploymentId: string;
    pullRequestId: string;
    pullRequestNumber: string;
    pullRequestURL: string;
    pullRequestTitle: string;
    pullRequestCommentId: string;
    previewStatus: "idle" | "running" | "done" | "error";
    application: {
        applicationId: string;
        serverId: string | null;
    };
    domain: {
        certificateType: "letsencrypt" | "none" | "custom";
        createdAt: string;
        applicationId: string | null;
        host: string;
        port: number | null;
        path: string | null;
        internalPath: string | null;
        stripPath: boolean;
        https: boolean;
        customCertResolver: string | null;
        middlewares: string[] | null;
        serviceName: string | null;
        domainType: "application" | "compose" | "preview" | null;
        domainId: string;
        customEntrypoint: string | null;
        uniqueConfigKey: number;
        composeId: string | null;
        previewDeploymentId: string | null;
    } | null;
}>;
export declare const updatePreviewDeployment: (previewDeploymentId: string, previewDeploymentData: Partial<PreviewDeployment>) => Promise<{
    previewDeploymentId: string;
    branch: string;
    pullRequestId: string;
    pullRequestNumber: string;
    pullRequestURL: string;
    pullRequestTitle: string;
    pullRequestCommentId: string;
    previewStatus: "idle" | "running" | "done" | "error";
    appName: string;
    applicationId: string;
    domainId: string | null;
    createdAt: string;
    expiresAt: string | null;
}[]>;
export declare const findPreviewDeploymentsByApplicationId: (applicationId: string) => Promise<{
    createdAt: string;
    expiresAt: string | null;
    applicationId: string;
    domainId: string | null;
    appName: string;
    branch: string;
    previewDeploymentId: string;
    pullRequestId: string;
    pullRequestNumber: string;
    pullRequestURL: string;
    pullRequestTitle: string;
    pullRequestCommentId: string;
    previewStatus: "idle" | "running" | "done" | "error";
    domain: {
        certificateType: "letsencrypt" | "none" | "custom";
        createdAt: string;
        applicationId: string | null;
        host: string;
        port: number | null;
        path: string | null;
        internalPath: string | null;
        stripPath: boolean;
        https: boolean;
        customCertResolver: string | null;
        middlewares: string[] | null;
        serviceName: string | null;
        domainType: "application" | "compose" | "preview" | null;
        domainId: string;
        customEntrypoint: string | null;
        uniqueConfigKey: number;
        composeId: string | null;
        previewDeploymentId: string | null;
    } | null;
    deployments: {
        createdAt: string;
        description: string | null;
        applicationId: string | null;
        composeId: string | null;
        serverId: string | null;
        title: string;
        buildServerId: string | null;
        previewDeploymentId: string | null;
        status: "running" | "done" | "error" | "cancelled" | null;
        deploymentId: string;
        logPath: string;
        pid: string | null;
        isPreviewDeployment: boolean | null;
        startedAt: string | null;
        finishedAt: string | null;
        errorMessage: string | null;
        scheduleId: string | null;
        backupId: string | null;
        rollbackId: string | null;
        volumeBackupId: string | null;
        initiatingActorType: "human" | "agent" | "plugin" | "system";
        initiatingActorId: string | null;
        gateStatus: "skipped" | "pending" | "approved" | "rejected" | "timed_out";
    }[];
}[]>;
export declare const createPreviewDeployment: (schema: z.infer<typeof apiCreatePreviewDeployment>) => Promise<{
    createdAt: string;
    expiresAt: string | null;
    applicationId: string;
    domainId: string | null;
    appName: string;
    branch: string;
    previewDeploymentId: string;
    pullRequestId: string;
    pullRequestNumber: string;
    pullRequestURL: string;
    pullRequestTitle: string;
    pullRequestCommentId: string;
    previewStatus: "idle" | "running" | "done" | "error";
}>;
export declare const findPreviewDeploymentsByPullRequestId: (pullRequestId: string) => Promise<{
    createdAt: string;
    expiresAt: string | null;
    applicationId: string;
    domainId: string | null;
    appName: string;
    branch: string;
    previewDeploymentId: string;
    pullRequestId: string;
    pullRequestNumber: string;
    pullRequestURL: string;
    pullRequestTitle: string;
    pullRequestCommentId: string;
    previewStatus: "idle" | "running" | "done" | "error";
}[]>;
export declare const findPreviewDeploymentByApplicationId: (applicationId: string, pullRequestId: string) => Promise<{
    createdAt: string;
    expiresAt: string | null;
    applicationId: string;
    domainId: string | null;
    appName: string;
    branch: string;
    previewDeploymentId: string;
    pullRequestId: string;
    pullRequestNumber: string;
    pullRequestURL: string;
    pullRequestTitle: string;
    pullRequestCommentId: string;
    previewStatus: "idle" | "running" | "done" | "error";
} | undefined>;
//# sourceMappingURL=preview-deployment.d.ts.map