import type { z } from "zod";
import { type createRollbackSchema } from "../db/schema";
import type { Mount } from "./mount";
import type { Port } from "./port";
import type { Project } from "./project";
import { type Registry } from "./registry";
export declare const createRollback: (input: z.infer<typeof createRollbackSchema>) => Promise<{
    createdAt: string;
    image: string | null;
    version: number;
    deploymentId: string;
    rollbackId: string;
    fullContext: ({
        applicationStatus: "idle" | "running" | "done" | "error";
        triggerType: "push" | "tag" | null;
        giteaId: string | null;
        name: string;
        createdAt: string;
        refreshToken: string | null;
        description: string | null;
        owner: string | null;
        githubId: string | null;
        gitlabId: string | null;
        applicationId: string;
        appName: string;
        env: string | null;
        sourceType: "gitea" | "github" | "gitlab" | "bitbucket" | "git" | "docker" | "drop";
        repository: string | null;
        branch: string | null;
        autoDeploy: boolean | null;
        gitlabProjectId: number | null;
        gitlabRepository: string | null;
        gitlabOwner: string | null;
        gitlabBranch: string | null;
        gitlabPathNamespace: string | null;
        bitbucketRepository: string | null;
        bitbucketRepositorySlug: string | null;
        bitbucketOwner: string | null;
        bitbucketBranch: string | null;
        giteaRepository: string | null;
        giteaOwner: string | null;
        giteaBranch: string | null;
        customGitUrl: string | null;
        customGitBranch: string | null;
        customGitSSHKeyId: string | null;
        command: string | null;
        enableSubmodules: boolean;
        environmentId: string;
        watchPaths: string[] | null;
        bitbucketId: string | null;
        serverId: string | null;
        username: string | null;
        previewEnv: string | null;
        previewBuildArgs: string | null;
        previewBuildSecrets: string | null;
        previewLabels: string[] | null;
        previewWildcard: string | null;
        previewPort: number | null;
        previewHttps: boolean;
        previewPath: string | null;
        previewCertificateType: "letsencrypt" | "none" | "custom";
        previewCustomCertResolver: string | null;
        previewLimit: number | null;
        isPreviewDeploymentsActive: boolean | null;
        previewRequireCollaboratorPermissions: boolean | null;
        rollbackActive: boolean | null;
        buildArgs: string | null;
        buildSecrets: string | null;
        memoryReservation: string | null;
        memoryLimit: string | null;
        cpuReservation: string | null;
        cpuLimit: string | null;
        title: string | null;
        enabled: boolean | null;
        subtitle: string | null;
        args: string[] | null;
        icon: string | null;
        cleanCache: boolean | null;
        buildPath: string | null;
        gitlabBuildPath: string | null;
        giteaBuildPath: string | null;
        bitbucketBuildPath: string | null;
        password: string | null;
        dockerImage: string | null;
        registryUrl: string | null;
        customGitBuildPath: string | null;
        dockerfile: string | null;
        dockerContextPath: string | null;
        dockerBuildStage: string | null;
        dropBuildPath: string | null;
        healthCheckSwarm: import("../db").HealthCheckSwarm | null;
        restartPolicySwarm: import("../db").RestartPolicySwarm | null;
        placementSwarm: import("../db").PlacementSwarm | null;
        updateConfigSwarm: import("../db").UpdateConfigSwarm | null;
        rollbackConfigSwarm: import("../db").UpdateConfigSwarm | null;
        modeSwarm: import("../db").ServiceModeSwarm | null;
        labelsSwarm: import("../db").LabelsSwarm | null;
        networkSwarm: import("../db").NetworkSwarm[] | null;
        stopGracePeriodSwarm: number | null;
        endpointSpecSwarm: import("../db").EndpointSpecSwarm | null;
        ulimitsSwarm: import("../db").UlimitsSwarm | null;
        replicas: number;
        buildType: "dockerfile" | "heroku_buildpacks" | "paketo_buildpacks" | "nixpacks" | "static" | "railpack";
        railpackVersion: string | null;
        herokuVersion: string | null;
        publishDirectory: string | null;
        isStaticSpa: boolean | null;
        createEnvFile: boolean;
        registryId: string | null;
        rollbackRegistryId: string | null;
        buildServerId: string | null;
        buildRegistryId: string | null;
    } & {
        environment: {
            project: Project;
        };
        mounts: Mount[];
        ports: Port[];
        registry?: Registry | null;
    }) | null;
} | undefined>;
export declare const findRollbackById: (rollbackId: string) => Promise<{
    createdAt: string;
    image: string | null;
    version: number;
    deploymentId: string;
    rollbackId: string;
    fullContext: ({
        applicationStatus: "idle" | "running" | "done" | "error";
        triggerType: "push" | "tag" | null;
        giteaId: string | null;
        name: string;
        createdAt: string;
        refreshToken: string | null;
        description: string | null;
        owner: string | null;
        githubId: string | null;
        gitlabId: string | null;
        applicationId: string;
        appName: string;
        env: string | null;
        sourceType: "gitea" | "github" | "gitlab" | "bitbucket" | "git" | "docker" | "drop";
        repository: string | null;
        branch: string | null;
        autoDeploy: boolean | null;
        gitlabProjectId: number | null;
        gitlabRepository: string | null;
        gitlabOwner: string | null;
        gitlabBranch: string | null;
        gitlabPathNamespace: string | null;
        bitbucketRepository: string | null;
        bitbucketRepositorySlug: string | null;
        bitbucketOwner: string | null;
        bitbucketBranch: string | null;
        giteaRepository: string | null;
        giteaOwner: string | null;
        giteaBranch: string | null;
        customGitUrl: string | null;
        customGitBranch: string | null;
        customGitSSHKeyId: string | null;
        command: string | null;
        enableSubmodules: boolean;
        environmentId: string;
        watchPaths: string[] | null;
        bitbucketId: string | null;
        serverId: string | null;
        username: string | null;
        previewEnv: string | null;
        previewBuildArgs: string | null;
        previewBuildSecrets: string | null;
        previewLabels: string[] | null;
        previewWildcard: string | null;
        previewPort: number | null;
        previewHttps: boolean;
        previewPath: string | null;
        previewCertificateType: "letsencrypt" | "none" | "custom";
        previewCustomCertResolver: string | null;
        previewLimit: number | null;
        isPreviewDeploymentsActive: boolean | null;
        previewRequireCollaboratorPermissions: boolean | null;
        rollbackActive: boolean | null;
        buildArgs: string | null;
        buildSecrets: string | null;
        memoryReservation: string | null;
        memoryLimit: string | null;
        cpuReservation: string | null;
        cpuLimit: string | null;
        title: string | null;
        enabled: boolean | null;
        subtitle: string | null;
        args: string[] | null;
        icon: string | null;
        cleanCache: boolean | null;
        buildPath: string | null;
        gitlabBuildPath: string | null;
        giteaBuildPath: string | null;
        bitbucketBuildPath: string | null;
        password: string | null;
        dockerImage: string | null;
        registryUrl: string | null;
        customGitBuildPath: string | null;
        dockerfile: string | null;
        dockerContextPath: string | null;
        dockerBuildStage: string | null;
        dropBuildPath: string | null;
        healthCheckSwarm: import("../db").HealthCheckSwarm | null;
        restartPolicySwarm: import("../db").RestartPolicySwarm | null;
        placementSwarm: import("../db").PlacementSwarm | null;
        updateConfigSwarm: import("../db").UpdateConfigSwarm | null;
        rollbackConfigSwarm: import("../db").UpdateConfigSwarm | null;
        modeSwarm: import("../db").ServiceModeSwarm | null;
        labelsSwarm: import("../db").LabelsSwarm | null;
        networkSwarm: import("../db").NetworkSwarm[] | null;
        stopGracePeriodSwarm: number | null;
        endpointSpecSwarm: import("../db").EndpointSpecSwarm | null;
        ulimitsSwarm: import("../db").UlimitsSwarm | null;
        replicas: number;
        buildType: "dockerfile" | "heroku_buildpacks" | "paketo_buildpacks" | "nixpacks" | "static" | "railpack";
        railpackVersion: string | null;
        herokuVersion: string | null;
        publishDirectory: string | null;
        isStaticSpa: boolean | null;
        createEnvFile: boolean;
        registryId: string | null;
        rollbackRegistryId: string | null;
        buildServerId: string | null;
        buildRegistryId: string | null;
    } & {
        environment: {
            project: Project;
        };
        mounts: Mount[];
        ports: Port[];
        registry?: Registry | null;
    }) | null;
    deployment: {
        createdAt: string;
        description: string | null;
        applicationId: string | null;
        composeId: string | null;
        serverId: string | null;
        title: string;
        buildServerId: string | null;
        previewDeploymentId: string | null;
        status: "running" | "done" | "error" | "cancelled" | null;
        deploymentId: string;
        logPath: string;
        pid: string | null;
        isPreviewDeployment: boolean | null;
        startedAt: string | null;
        finishedAt: string | null;
        errorMessage: string | null;
        scheduleId: string | null;
        backupId: string | null;
        rollbackId: string | null;
        volumeBackupId: string | null;
        initiatingActorType: "human" | "agent" | "plugin" | "system";
        initiatingActorId: string | null;
        gateStatus: "skipped" | "pending" | "approved" | "rejected" | "timed_out";
        application: {
            applicationStatus: "idle" | "running" | "done" | "error";
            triggerType: "push" | "tag" | null;
            giteaId: string | null;
            name: string;
            createdAt: string;
            refreshToken: string | null;
            description: string | null;
            owner: string | null;
            githubId: string | null;
            gitlabId: string | null;
            applicationId: string;
            appName: string;
            env: string | null;
            sourceType: "gitea" | "github" | "gitlab" | "bitbucket" | "git" | "docker" | "drop";
            repository: string | null;
            branch: string | null;
            autoDeploy: boolean | null;
            gitlabProjectId: number | null;
            gitlabRepository: string | null;
            gitlabOwner: string | null;
            gitlabBranch: string | null;
            gitlabPathNamespace: string | null;
            bitbucketRepository: string | null;
            bitbucketRepositorySlug: string | null;
            bitbucketOwner: string | null;
            bitbucketBranch: string | null;
            giteaRepository: string | null;
            giteaOwner: string | null;
            giteaBranch: string | null;
            customGitUrl: string | null;
            customGitBranch: string | null;
            customGitSSHKeyId: string | null;
            command: string | null;
            enableSubmodules: boolean;
            environmentId: string;
            watchPaths: string[] | null;
            bitbucketId: string | null;
            serverId: string | null;
            username: string | null;
            previewEnv: string | null;
            previewBuildArgs: string | null;
            previewBuildSecrets: string | null;
            previewLabels: string[] | null;
            previewWildcard: string | null;
            previewPort: number | null;
            previewHttps: boolean;
            previewPath: string | null;
            previewCertificateType: "letsencrypt" | "none" | "custom";
            previewCustomCertResolver: string | null;
            previewLimit: number | null;
            isPreviewDeploymentsActive: boolean | null;
            previewRequireCollaboratorPermissions: boolean | null;
            rollbackActive: boolean | null;
            buildArgs: string | null;
            buildSecrets: string | null;
            memoryReservation: string | null;
            memoryLimit: string | null;
            cpuReservation: string | null;
            cpuLimit: string | null;
            title: string | null;
            enabled: boolean | null;
            subtitle: string | null;
            args: string[] | null;
            icon: string | null;
            cleanCache: boolean | null;
            buildPath: string | null;
            gitlabBuildPath: string | null;
            giteaBuildPath: string | null;
            bitbucketBuildPath: string | null;
            password: string | null;
            dockerImage: string | null;
            registryUrl: string | null;
            customGitBuildPath: string | null;
            dockerfile: string | null;
            dockerContextPath: string | null;
            dockerBuildStage: string | null;
            dropBuildPath: string | null;
            healthCheckSwarm: import("../db").HealthCheckSwarm | null;
            restartPolicySwarm: import("../db").RestartPolicySwarm | null;
            placementSwarm: import("../db").PlacementSwarm | null;
            updateConfigSwarm: import("../db").UpdateConfigSwarm | null;
            rollbackConfigSwarm: import("../db").UpdateConfigSwarm | null;
            modeSwarm: import("../db").ServiceModeSwarm | null;
            labelsSwarm: import("../db").LabelsSwarm | null;
            networkSwarm: import("../db").NetworkSwarm[] | null;
            stopGracePeriodSwarm: number | null;
            endpointSpecSwarm: import("../db").EndpointSpecSwarm | null;
            ulimitsSwarm: import("../db").UlimitsSwarm | null;
            replicas: number;
            buildType: "dockerfile" | "heroku_buildpacks" | "paketo_buildpacks" | "nixpacks" | "static" | "railpack";
            railpackVersion: string | null;
            herokuVersion: string | null;
            publishDirectory: string | null;
            isStaticSpa: boolean | null;
            createEnvFile: boolean;
            registryId: string | null;
            rollbackRegistryId: string | null;
            buildServerId: string | null;
            buildRegistryId: string | null;
            environment: {
                name: string;
                createdAt: string;
                description: string | null;
                env: string;
                environmentId: string;
                projectId: string;
                isDefault: boolean;
                gatePolicy: "disabled" | "single" | "unanimous" | "manual_only";
                reviewerIds: string[];
                autoApproveAgents: boolean;
                project: {
                    name: string;
                    createdAt: string;
                    organizationId: string;
                    description: string | null;
                    env: string;
                    projectId: string;
                };
            };
        } | null;
    };
}>;
export declare const removeRollbackById: (rollbackId: string) => Promise<{
    createdAt: string;
    image: string | null;
    version: number;
    deploymentId: string;
    rollbackId: string;
    fullContext: ({
        applicationStatus: "idle" | "running" | "done" | "error";
        triggerType: "push" | "tag" | null;
        giteaId: string | null;
        name: string;
        createdAt: string;
        refreshToken: string | null;
        description: string | null;
        owner: string | null;
        githubId: string | null;
        gitlabId: string | null;
        applicationId: string;
        appName: string;
        env: string | null;
        sourceType: "gitea" | "github" | "gitlab" | "bitbucket" | "git" | "docker" | "drop";
        repository: string | null;
        branch: string | null;
        autoDeploy: boolean | null;
        gitlabProjectId: number | null;
        gitlabRepository: string | null;
        gitlabOwner: string | null;
        gitlabBranch: string | null;
        gitlabPathNamespace: string | null;
        bitbucketRepository: string | null;
        bitbucketRepositorySlug: string | null;
        bitbucketOwner: string | null;
        bitbucketBranch: string | null;
        giteaRepository: string | null;
        giteaOwner: string | null;
        giteaBranch: string | null;
        customGitUrl: string | null;
        customGitBranch: string | null;
        customGitSSHKeyId: string | null;
        command: string | null;
        enableSubmodules: boolean;
        environmentId: string;
        watchPaths: string[] | null;
        bitbucketId: string | null;
        serverId: string | null;
        username: string | null;
        previewEnv: string | null;
        previewBuildArgs: string | null;
        previewBuildSecrets: string | null;
        previewLabels: string[] | null;
        previewWildcard: string | null;
        previewPort: number | null;
        previewHttps: boolean;
        previewPath: string | null;
        previewCertificateType: "letsencrypt" | "none" | "custom";
        previewCustomCertResolver: string | null;
        previewLimit: number | null;
        isPreviewDeploymentsActive: boolean | null;
        previewRequireCollaboratorPermissions: boolean | null;
        rollbackActive: boolean | null;
        buildArgs: string | null;
        buildSecrets: string | null;
        memoryReservation: string | null;
        memoryLimit: string | null;
        cpuReservation: string | null;
        cpuLimit: string | null;
        title: string | null;
        enabled: boolean | null;
        subtitle: string | null;
        args: string[] | null;
        icon: string | null;
        cleanCache: boolean | null;
        buildPath: string | null;
        gitlabBuildPath: string | null;
        giteaBuildPath: string | null;
        bitbucketBuildPath: string | null;
        password: string | null;
        dockerImage: string | null;
        registryUrl: string | null;
        customGitBuildPath: string | null;
        dockerfile: string | null;
        dockerContextPath: string | null;
        dockerBuildStage: string | null;
        dropBuildPath: string | null;
        healthCheckSwarm: import("../db").HealthCheckSwarm | null;
        restartPolicySwarm: import("../db").RestartPolicySwarm | null;
        placementSwarm: import("../db").PlacementSwarm | null;
        updateConfigSwarm: import("../db").UpdateConfigSwarm | null;
        rollbackConfigSwarm: import("../db").UpdateConfigSwarm | null;
        modeSwarm: import("../db").ServiceModeSwarm | null;
        labelsSwarm: import("../db").LabelsSwarm | null;
        networkSwarm: import("../db").NetworkSwarm[] | null;
        stopGracePeriodSwarm: number | null;
        endpointSpecSwarm: import("../db").EndpointSpecSwarm | null;
        ulimitsSwarm: import("../db").UlimitsSwarm | null;
        replicas: number;
        buildType: "dockerfile" | "heroku_buildpacks" | "paketo_buildpacks" | "nixpacks" | "static" | "railpack";
        railpackVersion: string | null;
        herokuVersion: string | null;
        publishDirectory: string | null;
        isStaticSpa: boolean | null;
        createEnvFile: boolean;
        registryId: string | null;
        rollbackRegistryId: string | null;
        buildServerId: string | null;
        buildRegistryId: string | null;
    } & {
        environment: {
            project: Project;
        };
        mounts: Mount[];
        ports: Port[];
        registry?: Registry | null;
    }) | null;
    deployment: {
        createdAt: string;
        description: string | null;
        applicationId: string | null;
        composeId: string | null;
        serverId: string | null;
        title: string;
        buildServerId: string | null;
        previewDeploymentId: string | null;
        status: "running" | "done" | "error" | "cancelled" | null;
        deploymentId: string;
        logPath: string;
        pid: string | null;
        isPreviewDeployment: boolean | null;
        startedAt: string | null;
        finishedAt: string | null;
        errorMessage: string | null;
        scheduleId: string | null;
        backupId: string | null;
        rollbackId: string | null;
        volumeBackupId: string | null;
        initiatingActorType: "human" | "agent" | "plugin" | "system";
        initiatingActorId: string | null;
        gateStatus: "skipped" | "pending" | "approved" | "rejected" | "timed_out";
        application: {
            applicationStatus: "idle" | "running" | "done" | "error";
            triggerType: "push" | "tag" | null;
            giteaId: string | null;
            name: string;
            createdAt: string;
            refreshToken: string | null;
            description: string | null;
            owner: string | null;
            githubId: string | null;
            gitlabId: string | null;
            applicationId: string;
            appName: string;
            env: string | null;
            sourceType: "gitea" | "github" | "gitlab" | "bitbucket" | "git" | "docker" | "drop";
            repository: string | null;
            branch: string | null;
            autoDeploy: boolean | null;
            gitlabProjectId: number | null;
            gitlabRepository: string | null;
            gitlabOwner: string | null;
            gitlabBranch: string | null;
            gitlabPathNamespace: string | null;
            bitbucketRepository: string | null;
            bitbucketRepositorySlug: string | null;
            bitbucketOwner: string | null;
            bitbucketBranch: string | null;
            giteaRepository: string | null;
            giteaOwner: string | null;
            giteaBranch: string | null;
            customGitUrl: string | null;
            customGitBranch: string | null;
            customGitSSHKeyId: string | null;
            command: string | null;
            enableSubmodules: boolean;
            environmentId: string;
            watchPaths: string[] | null;
            bitbucketId: string | null;
            serverId: string | null;
            username: string | null;
            previewEnv: string | null;
            previewBuildArgs: string | null;
            previewBuildSecrets: string | null;
            previewLabels: string[] | null;
            previewWildcard: string | null;
            previewPort: number | null;
            previewHttps: boolean;
            previewPath: string | null;
            previewCertificateType: "letsencrypt" | "none" | "custom";
            previewCustomCertResolver: string | null;
            previewLimit: number | null;
            isPreviewDeploymentsActive: boolean | null;
            previewRequireCollaboratorPermissions: boolean | null;
            rollbackActive: boolean | null;
            buildArgs: string | null;
            buildSecrets: string | null;
            memoryReservation: string | null;
            memoryLimit: string | null;
            cpuReservation: string | null;
            cpuLimit: string | null;
            title: string | null;
            enabled: boolean | null;
            subtitle: string | null;
            args: string[] | null;
            icon: string | null;
            cleanCache: boolean | null;
            buildPath: string | null;
            gitlabBuildPath: string | null;
            giteaBuildPath: string | null;
            bitbucketBuildPath: string | null;
            password: string | null;
            dockerImage: string | null;
            registryUrl: string | null;
            customGitBuildPath: string | null;
            dockerfile: string | null;
            dockerContextPath: string | null;
            dockerBuildStage: string | null;
            dropBuildPath: string | null;
            healthCheckSwarm: import("../db").HealthCheckSwarm | null;
            restartPolicySwarm: import("../db").RestartPolicySwarm | null;
            placementSwarm: import("../db").PlacementSwarm | null;
            updateConfigSwarm: import("../db").UpdateConfigSwarm | null;
            rollbackConfigSwarm: import("../db").UpdateConfigSwarm | null;
            modeSwarm: import("../db").ServiceModeSwarm | null;
            labelsSwarm: import("../db").LabelsSwarm | null;
            networkSwarm: import("../db").NetworkSwarm[] | null;
            stopGracePeriodSwarm: number | null;
            endpointSpecSwarm: import("../db").EndpointSpecSwarm | null;
            ulimitsSwarm: import("../db").UlimitsSwarm | null;
            replicas: number;
            buildType: "dockerfile" | "heroku_buildpacks" | "paketo_buildpacks" | "nixpacks" | "static" | "railpack";
            railpackVersion: string | null;
            herokuVersion: string | null;
            publishDirectory: string | null;
            isStaticSpa: boolean | null;
            createEnvFile: boolean;
            registryId: string | null;
            rollbackRegistryId: string | null;
            buildServerId: string | null;
            buildRegistryId: string | null;
            environment: {
                name: string;
                createdAt: string;
                description: string | null;
                env: string;
                environmentId: string;
                projectId: string;
                isDefault: boolean;
                gatePolicy: "disabled" | "single" | "unanimous" | "manual_only";
                reviewerIds: string[];
                autoApproveAgents: boolean;
                project: {
                    name: string;
                    createdAt: string;
                    organizationId: string;
                    description: string | null;
                    env: string;
                    projectId: string;
                };
            };
        } | null;
    };
}>;
export declare const rollback: (rollbackId: string) => Promise<void>;
//# sourceMappingURL=rollbacks.d.ts.map