import type { z } from "zod";
import type { createScheduleSchema, updateScheduleSchema } from "../db/schema/schedule";
export type ScheduleExtended = Awaited<ReturnType<typeof findScheduleById>>;
export declare const createSchedule: (input: z.infer<typeof createScheduleSchema>) => Promise<{
    name: string;
    createdAt: string;
    userId: string | null;
    description: string | null;
    applicationId: string | null;
    serviceName: string | null;
    composeId: string | null;
    appName: string;
    command: string;
    serverId: string | null;
    enabled: boolean;
    scheduleType: "application" | "compose" | "server" | "dokploy-server";
    scheduleId: string;
    cronExpression: string;
    shellType: "bash" | "sh";
    script: string | null;
    timezone: string | null;
}>;
export declare const findScheduleById: (scheduleId: string) => Promise<{
    name: string;
    createdAt: string;
    userId: string | null;
    description: string | null;
    applicationId: string | null;
    serviceName: string | null;
    composeId: string | null;
    appName: string;
    command: string;
    serverId: string | null;
    enabled: boolean;
    scheduleType: "application" | "compose" | "server" | "dokploy-server";
    scheduleId: string;
    cronExpression: string;
    shellType: "bash" | "sh";
    script: string | null;
    timezone: string | null;
    application: {
        applicationStatus: "idle" | "running" | "done" | "error";
        triggerType: "push" | "tag" | null;
        giteaId: string | null;
        name: string;
        createdAt: string;
        refreshToken: string | null;
        description: string | null;
        owner: string | null;
        githubId: string | null;
        gitlabId: string | null;
        applicationId: string;
        appName: string;
        env: string | null;
        sourceType: "gitea" | "github" | "gitlab" | "bitbucket" | "git" | "docker" | "drop";
        repository: string | null;
        branch: string | null;
        autoDeploy: boolean | null;
        gitlabProjectId: number | null;
        gitlabRepository: string | null;
        gitlabOwner: string | null;
        gitlabBranch: string | null;
        gitlabPathNamespace: string | null;
        bitbucketRepository: string | null;
        bitbucketRepositorySlug: string | null;
        bitbucketOwner: string | null;
        bitbucketBranch: string | null;
        giteaRepository: string | null;
        giteaOwner: string | null;
        giteaBranch: string | null;
        customGitUrl: string | null;
        customGitBranch: string | null;
        customGitSSHKeyId: string | null;
        command: string | null;
        enableSubmodules: boolean;
        environmentId: string;
        watchPaths: string[] | null;
        bitbucketId: string | null;
        serverId: string | null;
        username: string | null;
        previewEnv: string | null;
        previewBuildArgs: string | null;
        previewBuildSecrets: string | null;
        previewLabels: string[] | null;
        previewWildcard: string | null;
        previewPort: number | null;
        previewHttps: boolean;
        previewPath: string | null;
        previewCertificateType: "letsencrypt" | "none" | "custom";
        previewCustomCertResolver: string | null;
        previewLimit: number | null;
        isPreviewDeploymentsActive: boolean | null;
        previewRequireCollaboratorPermissions: boolean | null;
        rollbackActive: boolean | null;
        buildArgs: string | null;
        buildSecrets: string | null;
        memoryReservation: string | null;
        memoryLimit: string | null;
        cpuReservation: string | null;
        cpuLimit: string | null;
        title: string | null;
        enabled: boolean | null;
        subtitle: string | null;
        args: string[] | null;
        icon: string | null;
        cleanCache: boolean | null;
        buildPath: string | null;
        gitlabBuildPath: string | null;
        giteaBuildPath: string | null;
        bitbucketBuildPath: string | null;
        password: string | null;
        dockerImage: string | null;
        registryUrl: string | null;
        customGitBuildPath: string | null;
        dockerfile: string | null;
        dockerContextPath: string | null;
        dockerBuildStage: string | null;
        dropBuildPath: string | null;
        healthCheckSwarm: import("../db").HealthCheckSwarm | null;
        restartPolicySwarm: import("../db").RestartPolicySwarm | null;
        placementSwarm: import("../db").PlacementSwarm | null;
        updateConfigSwarm: import("../db").UpdateConfigSwarm | null;
        rollbackConfigSwarm: import("../db").UpdateConfigSwarm | null;
        modeSwarm: import("../db").ServiceModeSwarm | null;
        labelsSwarm: import("../db").LabelsSwarm | null;
        networkSwarm: import("../db").NetworkSwarm[] | null;
        stopGracePeriodSwarm: number | null;
        endpointSpecSwarm: import("../db").EndpointSpecSwarm | null;
        ulimitsSwarm: import("../db").UlimitsSwarm | null;
        replicas: number;
        buildType: "dockerfile" | "heroku_buildpacks" | "paketo_buildpacks" | "nixpacks" | "static" | "railpack";
        railpackVersion: string | null;
        herokuVersion: string | null;
        publishDirectory: string | null;
        isStaticSpa: boolean | null;
        createEnvFile: boolean;
        registryId: string | null;
        rollbackRegistryId: string | null;
        buildServerId: string | null;
        buildRegistryId: string | null;
        environment: {
            name: string;
            createdAt: string;
            description: string | null;
            env: string;
            environmentId: string;
            projectId: string;
            isDefault: boolean;
            gatePolicy: "disabled" | "single" | "unanimous" | "manual_only";
            reviewerIds: string[];
            autoApproveAgents: boolean;
            project: {
                name: string;
                createdAt: string;
                organizationId: string;
                description: string | null;
                env: string;
                projectId: string;
            };
        };
    } | null;
    compose: {
        triggerType: "push" | "tag" | null;
        giteaId: string | null;
        name: string;
        createdAt: string;
        refreshToken: string | null;
        description: string | null;
        owner: string | null;
        githubId: string | null;
        gitlabId: string | null;
        composeId: string;
        appName: string;
        env: string | null;
        composeFile: string;
        sourceType: "gitea" | "github" | "gitlab" | "bitbucket" | "raw" | "git";
        composeType: "docker-compose" | "stack";
        repository: string | null;
        branch: string | null;
        autoDeploy: boolean | null;
        gitlabProjectId: number | null;
        gitlabRepository: string | null;
        gitlabOwner: string | null;
        gitlabBranch: string | null;
        gitlabPathNamespace: string | null;
        bitbucketRepository: string | null;
        bitbucketRepositorySlug: string | null;
        bitbucketOwner: string | null;
        bitbucketBranch: string | null;
        giteaRepository: string | null;
        giteaOwner: string | null;
        giteaBranch: string | null;
        customGitUrl: string | null;
        customGitBranch: string | null;
        customGitSSHKeyId: string | null;
        command: string;
        enableSubmodules: boolean;
        composePath: string;
        suffix: string;
        randomize: boolean;
        isolatedDeployment: boolean;
        isolatedDeploymentsVolume: boolean;
        composeStatus: "idle" | "running" | "done" | "error";
        environmentId: string;
        watchPaths: string[] | null;
        bitbucketId: string | null;
        serverId: string | null;
        environment: {
            name: string;
            createdAt: string;
            description: string | null;
            env: string;
            environmentId: string;
            projectId: string;
            isDefault: boolean;
            gatePolicy: "disabled" | "single" | "unanimous" | "manual_only";
            reviewerIds: string[];
            autoApproveAgents: boolean;
            project: {
                name: string;
                createdAt: string;
                organizationId: string;
                description: string | null;
                env: string;
                projectId: string;
            };
        };
    } | null;
    server: {
        name: string;
        createdAt: string;
        organizationId: string;
        description: string | null;
        port: number;
        appName: string;
        sshKeyId: string | null;
        command: string;
        serverId: string;
        ipAddress: string;
        username: string;
        enableDockerCleanup: boolean;
        serverStatus: "active" | "inactive";
        serverType: "deploy" | "build";
        metricsConfig: {
            server: {
                type: "Dokploy" | "Remote";
                refreshRate: number;
                port: number;
                token: string;
                urlCallback: string;
                retentionDays: number;
                cronJob: string;
                thresholds: {
                    cpu: number;
                    memory: number;
                };
            };
            containers: {
                refreshRate: number;
                services: {
                    include: string[];
                    exclude: string[];
                };
            };
        };
        organization: {
            name: string;
            createdAt: Date;
            id: string;
            slug: string | null;
            logo: string | null;
            metadata: string | null;
            ownerId: string;
        };
    } | null;
}>;
export declare const findScheduleOrganizationId: (scheduleId: string) => Promise<string | null>;
export declare const deleteSchedule: (scheduleId: string) => Promise<boolean>;
export declare const updateSchedule: (input: z.infer<typeof updateScheduleSchema>) => Promise<{
    scheduleId: string;
    name: string;
    description: string | null;
    cronExpression: string;
    appName: string;
    serviceName: string | null;
    shellType: "bash" | "sh";
    scheduleType: "application" | "compose" | "server" | "dokploy-server";
    command: string;
    script: string | null;
    applicationId: string | null;
    composeId: string | null;
    serverId: string | null;
    userId: string | null;
    enabled: boolean;
    timezone: string | null;
    createdAt: string;
}>;
//# sourceMappingURL=schedule.d.ts.map