import type { z } from "zod";
import { type createVolumeBackupSchema, type updateVolumeBackupSchema } from "../db/schema";
export declare const findVolumeBackupById: (volumeBackupId: string) => Promise<{
    name: string;
    createdAt: string;
    applicationId: string | null;
    serviceName: string | null;
    composeId: string | null;
    appName: string;
    enabled: boolean | null;
    serviceType: "application" | "compose" | "mysql" | "libsql" | "mariadb" | "mongo" | "postgres" | "redis";
    mysqlId: string | null;
    prefix: string;
    volumeBackupId: string;
    volumeName: string;
    libsqlId: string | null;
    mariadbId: string | null;
    mongoId: string | null;
    postgresId: string | null;
    redisId: string | null;
    destinationId: string;
    keepLatestCount: number | null;
    cronExpression: string;
    turnOff: boolean;
    application: {
        applicationStatus: "idle" | "running" | "done" | "error";
        triggerType: "push" | "tag" | null;
        giteaId: string | null;
        name: string;
        createdAt: string;
        refreshToken: string | null;
        description: string | null;
        owner: string | null;
        githubId: string | null;
        gitlabId: string | null;
        applicationId: string;
        appName: string;
        env: string | null;
        sourceType: "gitea" | "github" | "gitlab" | "bitbucket" | "git" | "docker" | "drop";
        repository: string | null;
        branch: string | null;
        autoDeploy: boolean | null;
        gitlabProjectId: number | null;
        gitlabRepository: string | null;
        gitlabOwner: string | null;
        gitlabBranch: string | null;
        gitlabPathNamespace: string | null;
        bitbucketRepository: string | null;
        bitbucketRepositorySlug: string | null;
        bitbucketOwner: string | null;
        bitbucketBranch: string | null;
        giteaRepository: string | null;
        giteaOwner: string | null;
        giteaBranch: string | null;
        customGitUrl: string | null;
        customGitBranch: string | null;
        customGitSSHKeyId: string | null;
        command: string | null;
        enableSubmodules: boolean;
        environmentId: string;
        watchPaths: string[] | null;
        bitbucketId: string | null;
        serverId: string | null;
        username: string | null;
        previewEnv: string | null;
        previewBuildArgs: string | null;
        previewBuildSecrets: string | null;
        previewLabels: string[] | null;
        previewWildcard: string | null;
        previewPort: number | null;
        previewHttps: boolean;
        previewPath: string | null;
        previewCertificateType: "letsencrypt" | "none" | "custom";
        previewCustomCertResolver: string | null;
        previewLimit: number | null;
        isPreviewDeploymentsActive: boolean | null;
        previewRequireCollaboratorPermissions: boolean | null;
        rollbackActive: boolean | null;
        buildArgs: string | null;
        buildSecrets: string | null;
        memoryReservation: string | null;
        memoryLimit: string | null;
        cpuReservation: string | null;
        cpuLimit: string | null;
        title: string | null;
        enabled: boolean | null;
        subtitle: string | null;
        args: string[] | null;
        icon: string | null;
        cleanCache: boolean | null;
        buildPath: string | null;
        gitlabBuildPath: string | null;
        giteaBuildPath: string | null;
        bitbucketBuildPath: string | null;
        password: string | null;
        dockerImage: string | null;
        registryUrl: string | null;
        customGitBuildPath: string | null;
        dockerfile: string | null;
        dockerContextPath: string | null;
        dockerBuildStage: string | null;
        dropBuildPath: string | null;
        healthCheckSwarm: import("../db").HealthCheckSwarm | null;
        restartPolicySwarm: import("../db").RestartPolicySwarm | null;
        placementSwarm: import("../db").PlacementSwarm | null;
        updateConfigSwarm: import("../db").UpdateConfigSwarm | null;
        rollbackConfigSwarm: import("../db").UpdateConfigSwarm | null;
        modeSwarm: import("../db").ServiceModeSwarm | null;
        labelsSwarm: import("../db").LabelsSwarm | null;
        networkSwarm: import("../db").NetworkSwarm[] | null;
        stopGracePeriodSwarm: number | null;
        endpointSpecSwarm: import("../db").EndpointSpecSwarm | null;
        ulimitsSwarm: import("../db").UlimitsSwarm | null;
        replicas: number;
        buildType: "dockerfile" | "heroku_buildpacks" | "paketo_buildpacks" | "nixpacks" | "static" | "railpack";
        railpackVersion: string | null;
        herokuVersion: string | null;
        publishDirectory: string | null;
        isStaticSpa: boolean | null;
        createEnvFile: boolean;
        registryId: string | null;
        rollbackRegistryId: string | null;
        buildServerId: string | null;
        buildRegistryId: string | null;
        environment: {
            name: string;
            createdAt: string;
            description: string | null;
            env: string;
            environmentId: string;
            projectId: string;
            isDefault: boolean;
            gatePolicy: "disabled" | "single" | "unanimous" | "manual_only";
            reviewerIds: string[];
            autoApproveAgents: boolean;
            project: {
                name: string;
                createdAt: string;
                organizationId: string;
                description: string | null;
                env: string;
                projectId: string;
            };
        };
    } | null;
    compose: {
        triggerType: "push" | "tag" | null;
        giteaId: string | null;
        name: string;
        createdAt: string;
        refreshToken: string | null;
        description: string | null;
        owner: string | null;
        githubId: string | null;
        gitlabId: string | null;
        composeId: string;
        appName: string;
        env: string | null;
        composeFile: string;
        sourceType: "gitea" | "github" | "gitlab" | "bitbucket" | "raw" | "git";
        composeType: "docker-compose" | "stack";
        repository: string | null;
        branch: string | null;
        autoDeploy: boolean | null;
        gitlabProjectId: number | null;
        gitlabRepository: string | null;
        gitlabOwner: string | null;
        gitlabBranch: string | null;
        gitlabPathNamespace: string | null;
        bitbucketRepository: string | null;
        bitbucketRepositorySlug: string | null;
        bitbucketOwner: string | null;
        bitbucketBranch: string | null;
        giteaRepository: string | null;
        giteaOwner: string | null;
        giteaBranch: string | null;
        customGitUrl: string | null;
        customGitBranch: string | null;
        customGitSSHKeyId: string | null;
        command: string;
        enableSubmodules: boolean;
        composePath: string;
        suffix: string;
        randomize: boolean;
        isolatedDeployment: boolean;
        isolatedDeploymentsVolume: boolean;
        composeStatus: "idle" | "running" | "done" | "error";
        environmentId: string;
        watchPaths: string[] | null;
        bitbucketId: string | null;
        serverId: string | null;
        environment: {
            name: string;
            createdAt: string;
            description: string | null;
            env: string;
            environmentId: string;
            projectId: string;
            isDefault: boolean;
            gatePolicy: "disabled" | "single" | "unanimous" | "manual_only";
            reviewerIds: string[];
            autoApproveAgents: boolean;
            project: {
                name: string;
                createdAt: string;
                organizationId: string;
                description: string | null;
                env: string;
                projectId: string;
            };
        };
    } | null;
    mysql: {
        applicationStatus: "idle" | "running" | "done" | "error";
        name: string;
        createdAt: string;
        description: string | null;
        appName: string;
        env: string | null;
        command: string | null;
        environmentId: string;
        serverId: string | null;
        memoryReservation: string | null;
        memoryLimit: string | null;
        cpuReservation: string | null;
        cpuLimit: string | null;
        args: string[] | null;
        dockerImage: string;
        healthCheckSwarm: import("../db").HealthCheckSwarm | null;
        restartPolicySwarm: import("../db").RestartPolicySwarm | null;
        placementSwarm: import("../db").PlacementSwarm | null;
        updateConfigSwarm: import("../db").UpdateConfigSwarm | null;
        rollbackConfigSwarm: import("../db").UpdateConfigSwarm | null;
        modeSwarm: import("../db").ServiceModeSwarm | null;
        labelsSwarm: import("../db").LabelsSwarm | null;
        networkSwarm: import("../db").NetworkSwarm[] | null;
        stopGracePeriodSwarm: number | null;
        endpointSpecSwarm: import("../db").EndpointSpecSwarm | null;
        ulimitsSwarm: import("../db").UlimitsSwarm | null;
        replicas: number;
        mysqlId: string;
        databaseName: string;
        databaseUser: string;
        databasePassword: string;
        databaseRootPassword: string;
        externalPort: number | null;
        environment: {
            name: string;
            createdAt: string;
            description: string | null;
            env: string;
            environmentId: string;
            projectId: string;
            isDefault: boolean;
            gatePolicy: "disabled" | "single" | "unanimous" | "manual_only";
            reviewerIds: string[];
            autoApproveAgents: boolean;
            project: {
                name: string;
                createdAt: string;
                organizationId: string;
                description: string | null;
                env: string;
                projectId: string;
            };
        };
    } | null;
    libsql: {
        applicationStatus: "idle" | "running" | "done" | "error";
        sqldNode: "primary" | "replica";
        name: string;
        createdAt: string;
        description: string | null;
        appName: string;
        env: string | null;
        command: string | null;
        environmentId: string;
        serverId: string | null;
        memoryReservation: string | null;
        memoryLimit: string | null;
        cpuReservation: string | null;
        cpuLimit: string | null;
        dockerImage: string;
        healthCheckSwarm: import("../db").HealthCheckSwarm | null;
        restartPolicySwarm: import("../db").RestartPolicySwarm | null;
        placementSwarm: import("../db").PlacementSwarm | null;
        updateConfigSwarm: import("../db").UpdateConfigSwarm | null;
        rollbackConfigSwarm: import("../db").UpdateConfigSwarm | null;
        modeSwarm: import("../db").ServiceModeSwarm | null;
        labelsSwarm: import("../db").LabelsSwarm | null;
        networkSwarm: import("../db").NetworkSwarm[] | null;
        stopGracePeriodSwarm: number | null;
        endpointSpecSwarm: import("../db").EndpointSpecSwarm | null;
        replicas: number;
        databaseUser: string;
        databasePassword: string;
        externalPort: number | null;
        libsqlId: string;
        sqldPrimaryUrl: string | null;
        enableNamespaces: boolean;
        externalGRPCPort: number | null;
        externalAdminPort: number | null;
        environment: {
            name: string;
            createdAt: string;
            description: string | null;
            env: string;
            environmentId: string;
            projectId: string;
            isDefault: boolean;
            gatePolicy: "disabled" | "single" | "unanimous" | "manual_only";
            reviewerIds: string[];
            autoApproveAgents: boolean;
            project: {
                name: string;
                createdAt: string;
                organizationId: string;
                description: string | null;
                env: string;
                projectId: string;
            };
        };
    } | null;
    mariadb: {
        applicationStatus: "idle" | "running" | "done" | "error";
        name: string;
        createdAt: string;
        description: string | null;
        appName: string;
        env: string | null;
        command: string | null;
        environmentId: string;
        serverId: string | null;
        memoryReservation: string | null;
        memoryLimit: string | null;
        cpuReservation: string | null;
        cpuLimit: string | null;
        args: string[] | null;
        dockerImage: string;
        healthCheckSwarm: import("../db").HealthCheckSwarm | null;
        restartPolicySwarm: import("../db").RestartPolicySwarm | null;
        placementSwarm: import("../db").PlacementSwarm | null;
        updateConfigSwarm: import("../db").UpdateConfigSwarm | null;
        rollbackConfigSwarm: import("../db").UpdateConfigSwarm | null;
        modeSwarm: import("../db").ServiceModeSwarm | null;
        labelsSwarm: import("../db").LabelsSwarm | null;
        networkSwarm: import("../db").NetworkSwarm[] | null;
        stopGracePeriodSwarm: number | null;
        endpointSpecSwarm: import("../db").EndpointSpecSwarm | null;
        ulimitsSwarm: import("../db").UlimitsSwarm | null;
        replicas: number;
        databaseName: string;
        databaseUser: string;
        databasePassword: string;
        databaseRootPassword: string;
        externalPort: number | null;
        mariadbId: string;
        environment: {
            name: string;
            createdAt: string;
            description: string | null;
            env: string;
            environmentId: string;
            projectId: string;
            isDefault: boolean;
            gatePolicy: "disabled" | "single" | "unanimous" | "manual_only";
            reviewerIds: string[];
            autoApproveAgents: boolean;
            project: {
                name: string;
                createdAt: string;
                organizationId: string;
                description: string | null;
                env: string;
                projectId: string;
            };
        };
    } | null;
    mongo: {
        applicationStatus: "idle" | "running" | "done" | "error";
        name: string;
        createdAt: string;
        description: string | null;
        appName: string;
        env: string | null;
        command: string | null;
        environmentId: string;
        serverId: string | null;
        memoryReservation: string | null;
        memoryLimit: string | null;
        cpuReservation: string | null;
        cpuLimit: string | null;
        args: string[] | null;
        dockerImage: string;
        healthCheckSwarm: import("../db").HealthCheckSwarm | null;
        restartPolicySwarm: import("../db").RestartPolicySwarm | null;
        placementSwarm: import("../db").PlacementSwarm | null;
        updateConfigSwarm: import("../db").UpdateConfigSwarm | null;
        rollbackConfigSwarm: import("../db").UpdateConfigSwarm | null;
        modeSwarm: import("../db").ServiceModeSwarm | null;
        labelsSwarm: import("../db").LabelsSwarm | null;
        networkSwarm: import("../db").NetworkSwarm[] | null;
        stopGracePeriodSwarm: number | null;
        endpointSpecSwarm: import("../db").EndpointSpecSwarm | null;
        ulimitsSwarm: import("../db").UlimitsSwarm | null;
        replicas: number;
        databaseUser: string;
        databasePassword: string;
        externalPort: number | null;
        mongoId: string;
        replicaSets: boolean | null;
        environment: {
            name: string;
            createdAt: string;
            description: string | null;
            env: string;
            environmentId: string;
            projectId: string;
            isDefault: boolean;
            gatePolicy: "disabled" | "single" | "unanimous" | "manual_only";
            reviewerIds: string[];
            autoApproveAgents: boolean;
            project: {
                name: string;
                createdAt: string;
                organizationId: string;
                description: string | null;
                env: string;
                projectId: string;
            };
        };
    } | null;
    postgres: {
        applicationStatus: "idle" | "running" | "done" | "error";
        name: string;
        createdAt: string;
        description: string | null;
        appName: string;
        env: string | null;
        command: string | null;
        environmentId: string;
        serverId: string | null;
        memoryReservation: string | null;
        memoryLimit: string | null;
        cpuReservation: string | null;
        cpuLimit: string | null;
        args: string[] | null;
        dockerImage: string;
        healthCheckSwarm: import("../db").HealthCheckSwarm | null;
        restartPolicySwarm: import("../db").RestartPolicySwarm | null;
        placementSwarm: import("../db").PlacementSwarm | null;
        updateConfigSwarm: import("../db").UpdateConfigSwarm | null;
        rollbackConfigSwarm: import("../db").UpdateConfigSwarm | null;
        modeSwarm: import("../db").ServiceModeSwarm | null;
        labelsSwarm: import("../db").LabelsSwarm | null;
        networkSwarm: import("../db").NetworkSwarm[] | null;
        stopGracePeriodSwarm: number | null;
        endpointSpecSwarm: import("../db").EndpointSpecSwarm | null;
        ulimitsSwarm: import("../db").UlimitsSwarm | null;
        replicas: number;
        databaseName: string;
        databaseUser: string;
        databasePassword: string;
        externalPort: number | null;
        postgresId: string;
        environment: {
            name: string;
            createdAt: string;
            description: string | null;
            env: string;
            environmentId: string;
            projectId: string;
            isDefault: boolean;
            gatePolicy: "disabled" | "single" | "unanimous" | "manual_only";
            reviewerIds: string[];
            autoApproveAgents: boolean;
            project: {
                name: string;
                createdAt: string;
                organizationId: string;
                description: string | null;
                env: string;
                projectId: string;
            };
        };
    } | null;
    redis: {
        applicationStatus: "idle" | "running" | "done" | "error";
        name: string;
        createdAt: string;
        description: string | null;
        appName: string;
        env: string | null;
        command: string | null;
        environmentId: string;
        serverId: string | null;
        memoryReservation: string | null;
        memoryLimit: string | null;
        cpuReservation: string | null;
        cpuLimit: string | null;
        args: string[] | null;
        dockerImage: string;
        healthCheckSwarm: import("../db").HealthCheckSwarm | null;
        restartPolicySwarm: import("../db").RestartPolicySwarm | null;
        placementSwarm: import("../db").PlacementSwarm | null;
        updateConfigSwarm: import("../db").UpdateConfigSwarm | null;
        rollbackConfigSwarm: import("../db").UpdateConfigSwarm | null;
        modeSwarm: import("../db").ServiceModeSwarm | null;
        labelsSwarm: import("../db").LabelsSwarm | null;
        networkSwarm: import("../db").NetworkSwarm[] | null;
        stopGracePeriodSwarm: number | null;
        endpointSpecSwarm: import("../db").EndpointSpecSwarm | null;
        ulimitsSwarm: import("../db").UlimitsSwarm | null;
        replicas: number;
        databasePassword: string;
        externalPort: number | null;
        redisId: string;
        environment: {
            name: string;
            createdAt: string;
            description: string | null;
            env: string;
            environmentId: string;
            projectId: string;
            isDefault: boolean;
            gatePolicy: "disabled" | "single" | "unanimous" | "manual_only";
            reviewerIds: string[];
            autoApproveAgents: boolean;
            project: {
                name: string;
                createdAt: string;
                organizationId: string;
                description: string | null;
                env: string;
                projectId: string;
            };
        };
    } | null;
    destination: {
        name: string;
        createdAt: Date;
        organizationId: string;
        endpoint: string;
        destinationId: string;
        provider: string | null;
        accessKey: string;
        secretAccessKey: string;
        bucket: string;
        region: string;
        additionalFlags: string[] | null;
    };
}>;
export declare const createVolumeBackup: (volumeBackup: z.infer<typeof createVolumeBackupSchema>) => Promise<{
    name: string;
    createdAt: string;
    applicationId: string | null;
    serviceName: string | null;
    composeId: string | null;
    appName: string;
    enabled: boolean | null;
    serviceType: "application" | "compose" | "mysql" | "libsql" | "mariadb" | "mongo" | "postgres" | "redis";
    mysqlId: string | null;
    prefix: string;
    volumeBackupId: string;
    volumeName: string;
    libsqlId: string | null;
    mariadbId: string | null;
    mongoId: string | null;
    postgresId: string | null;
    redisId: string | null;
    destinationId: string;
    keepLatestCount: number | null;
    cronExpression: string;
    turnOff: boolean;
}>;
export declare const removeVolumeBackup: (volumeBackupId: string) => Promise<void>;
export declare const updateVolumeBackup: (volumeBackupId: string, volumeBackup: z.infer<typeof updateVolumeBackupSchema>) => Promise<{
    volumeBackupId: string;
    name: string;
    volumeName: string;
    prefix: string;
    serviceType: "application" | "compose" | "mysql" | "libsql" | "mariadb" | "mongo" | "postgres" | "redis";
    appName: string;
    serviceName: string | null;
    turnOff: boolean;
    cronExpression: string;
    keepLatestCount: number | null;
    enabled: boolean | null;
    applicationId: string | null;
    postgresId: string | null;
    mariadbId: string | null;
    mongoId: string | null;
    mysqlId: string | null;
    redisId: string | null;
    libsqlId: string | null;
    composeId: string | null;
    createdAt: string;
    destinationId: string;
}>;
//# sourceMappingURL=volume-backups.d.ts.map