export declare const PLUGIN_SDK_VERSION = "0.1.0";
export { pluginManifestSchema, validateManifest, } from "./types/manifest.js";
export type { PluginManifest, PluginHookDeclaration, PluginPermission, PluginConfig, PluginSetting, } from "./types/manifest.js";
export type { PreDeployPayload, PreDeployResult, PostDeployPayload, PostDeployResult, DeployFailedPayload, DeployFailedResult, ServerAddedPayload, ServerRemovedPayload, ProjectCreatedPayload, ProjectDeletedPayload, Project, Server, Deployment, LogLine, PluginLogger, PluginApiClient, PluginContext, UndevopsPlugin, HookName, } from "./types/payloads.js";
export { HOOK_TO_METHOD } from "./types/payloads.js";
export { PluginPermissionError, checkPermission, validatePermissions, filterPayloadByPermissions, getRequiredPermission, CANONICAL_PERMISSIONS, } from "./permissions/index.js";
export { createPluginApiClient } from "./api-client.js";
export type { LoadedPlugin, PluginLoadError } from "./host/loader.js";
export { scanPluginDirectory, loadPlugin, loadAllPlugins } from "./host/loader.js";
export { HookDispatcher, PluginError, PluginTimeoutError, PluginManifestError, } from "./host/dispatcher.js";
export type { HookDispatcherEvent, HookDispatcherListener, } from "./host/dispatcher.js";
export { createTestContext, mockPayload } from "./testing.js";
