import { z } from "zod";
import { type EndpointSpecSwarm, type HealthCheckSwarm, type LabelsSwarm, type NetworkSwarm, type PlacementSwarm, type RestartPolicySwarm, type ServiceModeSwarm, type UlimitsSwarm, type UpdateConfigSwarm } from "./shared";
export declare const sourceType: import("drizzle-orm/pg-core").PgEnum<["docker", "git", "github", "gitlab", "bitbucket", "gitea", "drop"]>;
export declare const buildType: import("drizzle-orm/pg-core").PgEnum<["dockerfile", "heroku_buildpacks", "paketo_buildpacks", "nixpacks", "static", "railpack"]>;
export declare const applications: import("drizzle-orm/pg-core").PgTableWithColumns<{
    name: "application";
    schema: undefined;
    columns: {
        applicationId: import("drizzle-orm/pg-core").PgColumn<{
            name: "applicationId";
            tableName: "application";
            dataType: "string";
            columnType: "PgText";
            data: string;
            driverParam: string;
            notNull: true;
            hasDefault: true;
            isPrimaryKey: true;
            isAutoincrement: false;
            hasRuntimeDefault: true;
            enumValues: [string, ...string[]];
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        name: import("drizzle-orm/pg-core").PgColumn<{
            name: "name";
            tableName: "application";
            dataType: "string";
            columnType: "PgText";
            data: string;
            driverParam: string;
            notNull: true;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        appName: import("drizzle-orm/pg-core").PgColumn<{
            name: "appName";
            tableName: "application";
            dataType: "string";
            columnType: "PgText";
            data: string;
            driverParam: string;
            notNull: true;
            hasDefault: true;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: true;
            enumValues: [string, ...string[]];
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        description: import("drizzle-orm/pg-core").PgColumn<{
            name: "description";
            tableName: "application";
            dataType: "string";
            columnType: "PgText";
            data: string;
            driverParam: string;
            notNull: false;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        env: import("drizzle-orm/pg-core").PgColumn<{
            name: "env";
            tableName: "application";
            dataType: "string";
            columnType: "PgText";
            data: string;
            driverParam: string;
            notNull: false;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        previewEnv: import("drizzle-orm/pg-core").PgColumn<{
            name: "previewEnv";
            tableName: "application";
            dataType: "string";
            columnType: "PgText";
            data: string;
            driverParam: string;
            notNull: false;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        watchPaths: import("drizzle-orm/pg-core").PgColumn<{
            name: "watchPaths";
            tableName: "application";
            dataType: "array";
            columnType: "PgArray";
            data: string[];
            driverParam: string | string[];
            notNull: false;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: import("drizzle-orm").Column<{
                name: "watchPaths";
                tableName: "application";
                dataType: "string";
                columnType: "PgText";
                data: string;
                driverParam: string;
                notNull: false;
                hasDefault: false;
                isPrimaryKey: false;
                isAutoincrement: false;
                hasRuntimeDefault: false;
                enumValues: [string, ...string[]];
                baseColumn: never;
                identity: undefined;
                generated: undefined;
            }, {}, {}>;
            identity: undefined;
            generated: undefined;
        }, {}, {
            baseBuilder: import("drizzle-orm/pg-core").PgColumnBuilder<{
                name: "watchPaths";
                dataType: "string";
                columnType: "PgText";
                data: string;
                enumValues: [string, ...string[]];
                driverParam: string;
            }, {}, {}, import("drizzle-orm").ColumnBuilderExtraConfig>;
            size: undefined;
        }>;
        previewBuildArgs: import("drizzle-orm/pg-core").PgColumn<{
            name: "previewBuildArgs";
            tableName: "application";
            dataType: "string";
            columnType: "PgText";
            data: string;
            driverParam: string;
            notNull: false;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        previewBuildSecrets: import("drizzle-orm/pg-core").PgColumn<{
            name: "previewBuildSecrets";
            tableName: "application";
            dataType: "string";
            columnType: "PgText";
            data: string;
            driverParam: string;
            notNull: false;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        previewLabels: import("drizzle-orm/pg-core").PgColumn<{
            name: "previewLabels";
            tableName: "application";
            dataType: "array";
            columnType: "PgArray";
            data: string[];
            driverParam: string | string[];
            notNull: false;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: import("drizzle-orm").Column<{
                name: "previewLabels";
                tableName: "application";
                dataType: "string";
                columnType: "PgText";
                data: string;
                driverParam: string;
                notNull: false;
                hasDefault: false;
                isPrimaryKey: false;
                isAutoincrement: false;
                hasRuntimeDefault: false;
                enumValues: [string, ...string[]];
                baseColumn: never;
                identity: undefined;
                generated: undefined;
            }, {}, {}>;
            identity: undefined;
            generated: undefined;
        }, {}, {
            baseBuilder: import("drizzle-orm/pg-core").PgColumnBuilder<{
                name: "previewLabels";
                dataType: "string";
                columnType: "PgText";
                data: string;
                enumValues: [string, ...string[]];
                driverParam: string;
            }, {}, {}, import("drizzle-orm").ColumnBuilderExtraConfig>;
            size: undefined;
        }>;
        previewWildcard: import("drizzle-orm/pg-core").PgColumn<{
            name: "previewWildcard";
            tableName: "application";
            dataType: "string";
            columnType: "PgText";
            data: string;
            driverParam: string;
            notNull: false;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        previewPort: import("drizzle-orm/pg-core").PgColumn<{
            name: "previewPort";
            tableName: "application";
            dataType: "number";
            columnType: "PgInteger";
            data: number;
            driverParam: string | number;
            notNull: false;
            hasDefault: true;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: undefined;
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        previewHttps: import("drizzle-orm/pg-core").PgColumn<{
            name: "previewHttps";
            tableName: "application";
            dataType: "boolean";
            columnType: "PgBoolean";
            data: boolean;
            driverParam: boolean;
            notNull: true;
            hasDefault: true;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: undefined;
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        previewPath: import("drizzle-orm/pg-core").PgColumn<{
            name: "previewPath";
            tableName: "application";
            dataType: "string";
            columnType: "PgText";
            data: string;
            driverParam: string;
            notNull: false;
            hasDefault: true;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        previewCertificateType: import("drizzle-orm/pg-core").PgColumn<{
            name: "certificateType";
            tableName: "application";
            dataType: "string";
            columnType: "PgEnumColumn";
            data: "letsencrypt" | "none" | "custom";
            driverParam: string;
            notNull: true;
            hasDefault: true;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: ["letsencrypt", "none", "custom"];
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        previewCustomCertResolver: import("drizzle-orm/pg-core").PgColumn<{
            name: "previewCustomCertResolver";
            tableName: "application";
            dataType: "string";
            columnType: "PgText";
            data: string;
            driverParam: string;
            notNull: false;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        previewLimit: import("drizzle-orm/pg-core").PgColumn<{
            name: "previewLimit";
            tableName: "application";
            dataType: "number";
            columnType: "PgInteger";
            data: number;
            driverParam: string | number;
            notNull: false;
            hasDefault: true;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: undefined;
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        isPreviewDeploymentsActive: import("drizzle-orm/pg-core").PgColumn<{
            name: "isPreviewDeploymentsActive";
            tableName: "application";
            dataType: "boolean";
            columnType: "PgBoolean";
            data: boolean;
            driverParam: boolean;
            notNull: false;
            hasDefault: true;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: undefined;
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        previewRequireCollaboratorPermissions: import("drizzle-orm/pg-core").PgColumn<{
            name: "previewRequireCollaboratorPermissions";
            tableName: "application";
            dataType: "boolean";
            columnType: "PgBoolean";
            data: boolean;
            driverParam: boolean;
            notNull: false;
            hasDefault: true;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: undefined;
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        rollbackActive: import("drizzle-orm/pg-core").PgColumn<{
            name: "rollbackActive";
            tableName: "application";
            dataType: "boolean";
            columnType: "PgBoolean";
            data: boolean;
            driverParam: boolean;
            notNull: false;
            hasDefault: true;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: undefined;
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        buildArgs: import("drizzle-orm/pg-core").PgColumn<{
            name: "buildArgs";
            tableName: "application";
            dataType: "string";
            columnType: "PgText";
            data: string;
            driverParam: string;
            notNull: false;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        buildSecrets: import("drizzle-orm/pg-core").PgColumn<{
            name: "buildSecrets";
            tableName: "application";
            dataType: "string";
            columnType: "PgText";
            data: string;
            driverParam: string;
            notNull: false;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        memoryReservation: import("drizzle-orm/pg-core").PgColumn<{
            name: "memoryReservation";
            tableName: "application";
            dataType: "string";
            columnType: "PgText";
            data: string;
            driverParam: string;
            notNull: false;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        memoryLimit: import("drizzle-orm/pg-core").PgColumn<{
            name: "memoryLimit";
            tableName: "application";
            dataType: "string";
            columnType: "PgText";
            data: string;
            driverParam: string;
            notNull: false;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        cpuReservation: import("drizzle-orm/pg-core").PgColumn<{
            name: "cpuReservation";
            tableName: "application";
            dataType: "string";
            columnType: "PgText";
            data: string;
            driverParam: string;
            notNull: false;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        cpuLimit: import("drizzle-orm/pg-core").PgColumn<{
            name: "cpuLimit";
            tableName: "application";
            dataType: "string";
            columnType: "PgText";
            data: string;
            driverParam: string;
            notNull: false;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        title: import("drizzle-orm/pg-core").PgColumn<{
            name: "title";
            tableName: "application";
            dataType: "string";
            columnType: "PgText";
            data: string;
            driverParam: string;
            notNull: false;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        enabled: import("drizzle-orm/pg-core").PgColumn<{
            name: "enabled";
            tableName: "application";
            dataType: "boolean";
            columnType: "PgBoolean";
            data: boolean;
            driverParam: boolean;
            notNull: false;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: undefined;
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        subtitle: import("drizzle-orm/pg-core").PgColumn<{
            name: "subtitle";
            tableName: "application";
            dataType: "string";
            columnType: "PgText";
            data: string;
            driverParam: string;
            notNull: false;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        command: import("drizzle-orm/pg-core").PgColumn<{
            name: "command";
            tableName: "application";
            dataType: "string";
            columnType: "PgText";
            data: string;
            driverParam: string;
            notNull: false;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        args: import("drizzle-orm/pg-core").PgColumn<{
            name: "args";
            tableName: "application";
            dataType: "array";
            columnType: "PgArray";
            data: string[];
            driverParam: string | string[];
            notNull: false;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: import("drizzle-orm").Column<{
                name: "args";
                tableName: "application";
                dataType: "string";
                columnType: "PgText";
                data: string;
                driverParam: string;
                notNull: false;
                hasDefault: false;
                isPrimaryKey: false;
                isAutoincrement: false;
                hasRuntimeDefault: false;
                enumValues: [string, ...string[]];
                baseColumn: never;
                identity: undefined;
                generated: undefined;
            }, {}, {}>;
            identity: undefined;
            generated: undefined;
        }, {}, {
            baseBuilder: import("drizzle-orm/pg-core").PgColumnBuilder<{
                name: "args";
                dataType: "string";
                columnType: "PgText";
                data: string;
                enumValues: [string, ...string[]];
                driverParam: string;
            }, {}, {}, import("drizzle-orm").ColumnBuilderExtraConfig>;
            size: undefined;
        }>;
        icon: import("drizzle-orm/pg-core").PgColumn<{
            name: "icon";
            tableName: "application";
            dataType: "string";
            columnType: "PgText";
            data: string;
            driverParam: string;
            notNull: false;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        refreshToken: import("drizzle-orm/pg-core").PgColumn<{
            name: "refreshToken";
            tableName: "application";
            dataType: "string";
            columnType: "PgText";
            data: string;
            driverParam: string;
            notNull: false;
            hasDefault: true;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: true;
            enumValues: [string, ...string[]];
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        sourceType: import("drizzle-orm/pg-core").PgColumn<{
            name: "sourceType";
            tableName: "application";
            dataType: "string";
            columnType: "PgEnumColumn";
            data: "gitea" | "github" | "gitlab" | "bitbucket" | "git" | "docker" | "drop";
            driverParam: string;
            notNull: true;
            hasDefault: true;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: ["docker", "git", "github", "gitlab", "bitbucket", "gitea", "drop"];
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        cleanCache: import("drizzle-orm/pg-core").PgColumn<{
            name: "cleanCache";
            tableName: "application";
            dataType: "boolean";
            columnType: "PgBoolean";
            data: boolean;
            driverParam: boolean;
            notNull: false;
            hasDefault: true;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: undefined;
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        repository: import("drizzle-orm/pg-core").PgColumn<{
            name: "repository";
            tableName: "application";
            dataType: "string";
            columnType: "PgText";
            data: string;
            driverParam: string;
            notNull: false;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        owner: import("drizzle-orm/pg-core").PgColumn<{
            name: "owner";
            tableName: "application";
            dataType: "string";
            columnType: "PgText";
            data: string;
            driverParam: string;
            notNull: false;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        branch: import("drizzle-orm/pg-core").PgColumn<{
            name: "branch";
            tableName: "application";
            dataType: "string";
            columnType: "PgText";
            data: string;
            driverParam: string;
            notNull: false;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        buildPath: import("drizzle-orm/pg-core").PgColumn<{
            name: "buildPath";
            tableName: "application";
            dataType: "string";
            columnType: "PgText";
            data: string;
            driverParam: string;
            notNull: false;
            hasDefault: true;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        triggerType: import("drizzle-orm/pg-core").PgColumn<{
            name: "triggerType";
            tableName: "application";
            dataType: "string";
            columnType: "PgEnumColumn";
            data: "push" | "tag";
            driverParam: string;
            notNull: false;
            hasDefault: true;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: ["push", "tag"];
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        autoDeploy: import("drizzle-orm/pg-core").PgColumn<{
            name: "autoDeploy";
            tableName: "application";
            dataType: "boolean";
            columnType: "PgBoolean";
            data: boolean;
            driverParam: boolean;
            notNull: false;
            hasDefault: true;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: true;
            enumValues: undefined;
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        gitlabProjectId: import("drizzle-orm/pg-core").PgColumn<{
            name: "gitlabProjectId";
            tableName: "application";
            dataType: "number";
            columnType: "PgInteger";
            data: number;
            driverParam: string | number;
            notNull: false;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: undefined;
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        gitlabRepository: import("drizzle-orm/pg-core").PgColumn<{
            name: "gitlabRepository";
            tableName: "application";
            dataType: "string";
            columnType: "PgText";
            data: string;
            driverParam: string;
            notNull: false;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        gitlabOwner: import("drizzle-orm/pg-core").PgColumn<{
            name: "gitlabOwner";
            tableName: "application";
            dataType: "string";
            columnType: "PgText";
            data: string;
            driverParam: string;
            notNull: false;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        gitlabBranch: import("drizzle-orm/pg-core").PgColumn<{
            name: "gitlabBranch";
            tableName: "application";
            dataType: "string";
            columnType: "PgText";
            data: string;
            driverParam: string;
            notNull: false;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        gitlabBuildPath: import("drizzle-orm/pg-core").PgColumn<{
            name: "gitlabBuildPath";
            tableName: "application";
            dataType: "string";
            columnType: "PgText";
            data: string;
            driverParam: string;
            notNull: false;
            hasDefault: true;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        gitlabPathNamespace: import("drizzle-orm/pg-core").PgColumn<{
            name: "gitlabPathNamespace";
            tableName: "application";
            dataType: "string";
            columnType: "PgText";
            data: string;
            driverParam: string;
            notNull: false;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        giteaRepository: import("drizzle-orm/pg-core").PgColumn<{
            name: "giteaRepository";
            tableName: "application";
            dataType: "string";
            columnType: "PgText";
            data: string;
            driverParam: string;
            notNull: false;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        giteaOwner: import("drizzle-orm/pg-core").PgColumn<{
            name: "giteaOwner";
            tableName: "application";
            dataType: "string";
            columnType: "PgText";
            data: string;
            driverParam: string;
            notNull: false;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        giteaBranch: import("drizzle-orm/pg-core").PgColumn<{
            name: "giteaBranch";
            tableName: "application";
            dataType: "string";
            columnType: "PgText";
            data: string;
            driverParam: string;
            notNull: false;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        giteaBuildPath: import("drizzle-orm/pg-core").PgColumn<{
            name: "giteaBuildPath";
            tableName: "application";
            dataType: "string";
            columnType: "PgText";
            data: string;
            driverParam: string;
            notNull: false;
            hasDefault: true;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        bitbucketRepository: import("drizzle-orm/pg-core").PgColumn<{
            name: "bitbucketRepository";
            tableName: "application";
            dataType: "string";
            columnType: "PgText";
            data: string;
            driverParam: string;
            notNull: false;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        bitbucketRepositorySlug: import("drizzle-orm/pg-core").PgColumn<{
            name: "bitbucketRepositorySlug";
            tableName: "application";
            dataType: "string";
            columnType: "PgText";
            data: string;
            driverParam: string;
            notNull: false;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        bitbucketOwner: import("drizzle-orm/pg-core").PgColumn<{
            name: "bitbucketOwner";
            tableName: "application";
            dataType: "string";
            columnType: "PgText";
            data: string;
            driverParam: string;
            notNull: false;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        bitbucketBranch: import("drizzle-orm/pg-core").PgColumn<{
            name: "bitbucketBranch";
            tableName: "application";
            dataType: "string";
            columnType: "PgText";
            data: string;
            driverParam: string;
            notNull: false;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        bitbucketBuildPath: import("drizzle-orm/pg-core").PgColumn<{
            name: "bitbucketBuildPath";
            tableName: "application";
            dataType: "string";
            columnType: "PgText";
            data: string;
            driverParam: string;
            notNull: false;
            hasDefault: true;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        username: import("drizzle-orm/pg-core").PgColumn<{
            name: "username";
            tableName: "application";
            dataType: "string";
            columnType: "PgText";
            data: string;
            driverParam: string;
            notNull: false;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        password: import("drizzle-orm/pg-core").PgColumn<{
            name: "password";
            tableName: "application";
            dataType: "string";
            columnType: "PgText";
            data: string;
            driverParam: string;
            notNull: false;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        dockerImage: import("drizzle-orm/pg-core").PgColumn<{
            name: "dockerImage";
            tableName: "application";
            dataType: "string";
            columnType: "PgText";
            data: string;
            driverParam: string;
            notNull: false;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        registryUrl: import("drizzle-orm/pg-core").PgColumn<{
            name: "registryUrl";
            tableName: "application";
            dataType: "string";
            columnType: "PgText";
            data: string;
            driverParam: string;
            notNull: false;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        customGitUrl: import("drizzle-orm/pg-core").PgColumn<{
            name: "customGitUrl";
            tableName: "application";
            dataType: "string";
            columnType: "PgText";
            data: string;
            driverParam: string;
            notNull: false;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        customGitBranch: import("drizzle-orm/pg-core").PgColumn<{
            name: "customGitBranch";
            tableName: "application";
            dataType: "string";
            columnType: "PgText";
            data: string;
            driverParam: string;
            notNull: false;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        customGitBuildPath: import("drizzle-orm/pg-core").PgColumn<{
            name: "customGitBuildPath";
            tableName: "application";
            dataType: "string";
            columnType: "PgText";
            data: string;
            driverParam: string;
            notNull: false;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        customGitSSHKeyId: import("drizzle-orm/pg-core").PgColumn<{
            name: "customGitSSHKeyId";
            tableName: "application";
            dataType: "string";
            columnType: "PgText";
            data: string;
            driverParam: string;
            notNull: false;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        enableSubmodules: import("drizzle-orm/pg-core").PgColumn<{
            name: "enableSubmodules";
            tableName: "application";
            dataType: "boolean";
            columnType: "PgBoolean";
            data: boolean;
            driverParam: boolean;
            notNull: true;
            hasDefault: true;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: undefined;
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        dockerfile: import("drizzle-orm/pg-core").PgColumn<{
            name: "dockerfile";
            tableName: "application";
            dataType: "string";
            columnType: "PgText";
            data: string;
            driverParam: string;
            notNull: false;
            hasDefault: true;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        dockerContextPath: import("drizzle-orm/pg-core").PgColumn<{
            name: "dockerContextPath";
            tableName: "application";
            dataType: "string";
            columnType: "PgText";
            data: string;
            driverParam: string;
            notNull: false;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        dockerBuildStage: import("drizzle-orm/pg-core").PgColumn<{
            name: "dockerBuildStage";
            tableName: "application";
            dataType: "string";
            columnType: "PgText";
            data: string;
            driverParam: string;
            notNull: false;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        dropBuildPath: import("drizzle-orm/pg-core").PgColumn<{
            name: "dropBuildPath";
            tableName: "application";
            dataType: "string";
            columnType: "PgText";
            data: string;
            driverParam: string;
            notNull: false;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        healthCheckSwarm: import("drizzle-orm/pg-core").PgColumn<{
            name: "healthCheckSwarm";
            tableName: "application";
            dataType: "json";
            columnType: "PgJson";
            data: HealthCheckSwarm;
            driverParam: unknown;
            notNull: false;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: undefined;
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {
            $type: HealthCheckSwarm;
        }>;
        restartPolicySwarm: import("drizzle-orm/pg-core").PgColumn<{
            name: "restartPolicySwarm";
            tableName: "application";
            dataType: "json";
            columnType: "PgJson";
            data: RestartPolicySwarm;
            driverParam: unknown;
            notNull: false;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: undefined;
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {
            $type: RestartPolicySwarm;
        }>;
        placementSwarm: import("drizzle-orm/pg-core").PgColumn<{
            name: "placementSwarm";
            tableName: "application";
            dataType: "json";
            columnType: "PgJson";
            data: PlacementSwarm;
            driverParam: unknown;
            notNull: false;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: undefined;
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {
            $type: PlacementSwarm;
        }>;
        updateConfigSwarm: import("drizzle-orm/pg-core").PgColumn<{
            name: "updateConfigSwarm";
            tableName: "application";
            dataType: "json";
            columnType: "PgJson";
            data: UpdateConfigSwarm;
            driverParam: unknown;
            notNull: false;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: undefined;
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {
            $type: UpdateConfigSwarm;
        }>;
        rollbackConfigSwarm: import("drizzle-orm/pg-core").PgColumn<{
            name: "rollbackConfigSwarm";
            tableName: "application";
            dataType: "json";
            columnType: "PgJson";
            data: UpdateConfigSwarm;
            driverParam: unknown;
            notNull: false;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: undefined;
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {
            $type: UpdateConfigSwarm;
        }>;
        modeSwarm: import("drizzle-orm/pg-core").PgColumn<{
            name: "modeSwarm";
            tableName: "application";
            dataType: "json";
            columnType: "PgJson";
            data: ServiceModeSwarm;
            driverParam: unknown;
            notNull: false;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: undefined;
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {
            $type: ServiceModeSwarm;
        }>;
        labelsSwarm: import("drizzle-orm/pg-core").PgColumn<{
            name: "labelsSwarm";
            tableName: "application";
            dataType: "json";
            columnType: "PgJson";
            data: LabelsSwarm;
            driverParam: unknown;
            notNull: false;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: undefined;
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {
            $type: LabelsSwarm;
        }>;
        networkSwarm: import("drizzle-orm/pg-core").PgColumn<{
            name: "networkSwarm";
            tableName: "application";
            dataType: "json";
            columnType: "PgJson";
            data: NetworkSwarm[];
            driverParam: unknown;
            notNull: false;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: undefined;
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {
            $type: NetworkSwarm[];
        }>;
        stopGracePeriodSwarm: import("drizzle-orm/pg-core").PgColumn<{
            name: "stopGracePeriodSwarm";
            tableName: "application";
            dataType: "number";
            columnType: "PgBigInt53";
            data: number;
            driverParam: string | number;
            notNull: false;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: undefined;
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        endpointSpecSwarm: import("drizzle-orm/pg-core").PgColumn<{
            name: "endpointSpecSwarm";
            tableName: "application";
            dataType: "json";
            columnType: "PgJson";
            data: EndpointSpecSwarm;
            driverParam: unknown;
            notNull: false;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: undefined;
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {
            $type: EndpointSpecSwarm;
        }>;
        ulimitsSwarm: import("drizzle-orm/pg-core").PgColumn<{
            name: "ulimitsSwarm";
            tableName: "application";
            dataType: "json";
            columnType: "PgJson";
            data: UlimitsSwarm;
            driverParam: unknown;
            notNull: false;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: undefined;
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {
            $type: UlimitsSwarm;
        }>;
        replicas: import("drizzle-orm/pg-core").PgColumn<{
            name: "replicas";
            tableName: "application";
            dataType: "number";
            columnType: "PgInteger";
            data: number;
            driverParam: string | number;
            notNull: true;
            hasDefault: true;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: undefined;
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        applicationStatus: import("drizzle-orm/pg-core").PgColumn<{
            name: "applicationStatus";
            tableName: "application";
            dataType: "string";
            columnType: "PgEnumColumn";
            data: "idle" | "running" | "done" | "error";
            driverParam: string;
            notNull: true;
            hasDefault: true;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: ["idle", "running", "done", "error"];
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        buildType: import("drizzle-orm/pg-core").PgColumn<{
            name: "buildType";
            tableName: "application";
            dataType: "string";
            columnType: "PgEnumColumn";
            data: "dockerfile" | "heroku_buildpacks" | "paketo_buildpacks" | "nixpacks" | "static" | "railpack";
            driverParam: string;
            notNull: true;
            hasDefault: true;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: ["dockerfile", "heroku_buildpacks", "paketo_buildpacks", "nixpacks", "static", "railpack"];
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        railpackVersion: import("drizzle-orm/pg-core").PgColumn<{
            name: "railpackVersion";
            tableName: "application";
            dataType: "string";
            columnType: "PgText";
            data: string;
            driverParam: string;
            notNull: false;
            hasDefault: true;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        herokuVersion: import("drizzle-orm/pg-core").PgColumn<{
            name: "herokuVersion";
            tableName: "application";
            dataType: "string";
            columnType: "PgText";
            data: string;
            driverParam: string;
            notNull: false;
            hasDefault: true;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        publishDirectory: import("drizzle-orm/pg-core").PgColumn<{
            name: "publishDirectory";
            tableName: "application";
            dataType: "string";
            columnType: "PgText";
            data: string;
            driverParam: string;
            notNull: false;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        isStaticSpa: import("drizzle-orm/pg-core").PgColumn<{
            name: "isStaticSpa";
            tableName: "application";
            dataType: "boolean";
            columnType: "PgBoolean";
            data: boolean;
            driverParam: boolean;
            notNull: false;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: undefined;
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        createEnvFile: import("drizzle-orm/pg-core").PgColumn<{
            name: "createEnvFile";
            tableName: "application";
            dataType: "boolean";
            columnType: "PgBoolean";
            data: boolean;
            driverParam: boolean;
            notNull: true;
            hasDefault: true;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: undefined;
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        createdAt: import("drizzle-orm/pg-core").PgColumn<{
            name: "createdAt";
            tableName: "application";
            dataType: "string";
            columnType: "PgText";
            data: string;
            driverParam: string;
            notNull: true;
            hasDefault: true;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: true;
            enumValues: [string, ...string[]];
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        registryId: import("drizzle-orm/pg-core").PgColumn<{
            name: "registryId";
            tableName: "application";
            dataType: "string";
            columnType: "PgText";
            data: string;
            driverParam: string;
            notNull: false;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        rollbackRegistryId: import("drizzle-orm/pg-core").PgColumn<{
            name: "rollbackRegistryId";
            tableName: "application";
            dataType: "string";
            columnType: "PgText";
            data: string;
            driverParam: string;
            notNull: false;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        environmentId: import("drizzle-orm/pg-core").PgColumn<{
            name: "environmentId";
            tableName: "application";
            dataType: "string";
            columnType: "PgText";
            data: string;
            driverParam: string;
            notNull: true;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        githubId: import("drizzle-orm/pg-core").PgColumn<{
            name: "githubId";
            tableName: "application";
            dataType: "string";
            columnType: "PgText";
            data: string;
            driverParam: string;
            notNull: false;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        gitlabId: import("drizzle-orm/pg-core").PgColumn<{
            name: "gitlabId";
            tableName: "application";
            dataType: "string";
            columnType: "PgText";
            data: string;
            driverParam: string;
            notNull: false;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        giteaId: import("drizzle-orm/pg-core").PgColumn<{
            name: "giteaId";
            tableName: "application";
            dataType: "string";
            columnType: "PgText";
            data: string;
            driverParam: string;
            notNull: false;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        bitbucketId: import("drizzle-orm/pg-core").PgColumn<{
            name: "bitbucketId";
            tableName: "application";
            dataType: "string";
            columnType: "PgText";
            data: string;
            driverParam: string;
            notNull: false;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        serverId: import("drizzle-orm/pg-core").PgColumn<{
            name: "serverId";
            tableName: "application";
            dataType: "string";
            columnType: "PgText";
            data: string;
            driverParam: string;
            notNull: false;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        buildServerId: import("drizzle-orm/pg-core").PgColumn<{
            name: "buildServerId";
            tableName: "application";
            dataType: "string";
            columnType: "PgText";
            data: string;
            driverParam: string;
            notNull: false;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        buildRegistryId: import("drizzle-orm/pg-core").PgColumn<{
            name: "buildRegistryId";
            tableName: "application";
            dataType: "string";
            columnType: "PgText";
            data: string;
            driverParam: string;
            notNull: false;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
    };
    dialect: "pg";
}>;
export declare const applicationsRelations: import("drizzle-orm").Relations<"application", {
    environment: import("drizzle-orm").One<"environment", true>;
    deployments: import("drizzle-orm").Many<"deployment">;
    customGitSSHKey: import("drizzle-orm").One<"ssh-key", false>;
    domains: import("drizzle-orm").Many<"domain">;
    mounts: import("drizzle-orm").Many<"mount">;
    redirects: import("drizzle-orm").Many<"redirect">;
    security: import("drizzle-orm").Many<"security">;
    ports: import("drizzle-orm").Many<"port">;
    registry: import("drizzle-orm").One<"registry", false>;
    github: import("drizzle-orm").One<"github", false>;
    gitlab: import("drizzle-orm").One<"gitlab", false>;
    gitea: import("drizzle-orm").One<"gitea", false>;
    bitbucket: import("drizzle-orm").One<"bitbucket", false>;
    server: import("drizzle-orm").One<"server", false>;
    buildServer: import("drizzle-orm").One<"server", false>;
    buildRegistry: import("drizzle-orm").One<"registry", false>;
    previewDeployments: import("drizzle-orm").Many<"preview_deployments">;
    rollbackRegistry: import("drizzle-orm").One<"registry", false>;
    patches: import("drizzle-orm").Many<"patch">;
}>;
export declare const apiCreateApplication: z.ZodObject<{
    name: z.ZodString;
    description: z.ZodOptional<z.ZodNullable<z.ZodOptional<z.ZodString>>>;
    appName: z.ZodOptional<z.ZodOptional<z.ZodString>>;
    environmentId: z.ZodString;
    serverId: z.ZodOptional<z.ZodNullable<z.ZodString>>;
}, z.core.$strip>;
export declare const apiFindOneApplication: z.ZodObject<{
    applicationId: z.ZodString;
}, z.core.$strip>;
export declare const apiDeployApplication: z.ZodObject<{
    applicationId: z.ZodString;
    title: z.ZodOptional<z.ZodString>;
    description: z.ZodOptional<z.ZodString>;
}, z.core.$strip>;
export declare const apiRedeployApplication: z.ZodObject<{
    applicationId: z.ZodString;
    title: z.ZodOptional<z.ZodString>;
    description: z.ZodOptional<z.ZodString>;
}, z.core.$strip>;
export declare const apiReloadApplication: z.ZodObject<{
    applicationId: z.ZodNonOptional<z.ZodOptional<z.ZodString>>;
    appName: z.ZodNonOptional<z.ZodOptional<z.ZodOptional<z.ZodString>>>;
}, z.core.$strip>;
export declare const apiSaveBuildType: z.ZodObject<{
    applicationId: z.ZodNonOptional<z.ZodOptional<z.ZodString>>;
    dockerfile: z.ZodNonOptional<z.ZodOptional<z.ZodNullable<z.ZodOptional<z.ZodString>>>>;
    dockerContextPath: z.ZodNonOptional<z.ZodOptional<z.ZodNullable<z.ZodString>>>;
    dockerBuildStage: z.ZodNonOptional<z.ZodOptional<z.ZodNullable<z.ZodString>>>;
    buildType: z.ZodNonOptional<z.ZodOptional<z.ZodEnum<{
        dockerfile: "dockerfile";
        heroku_buildpacks: "heroku_buildpacks";
        paketo_buildpacks: "paketo_buildpacks";
        nixpacks: "nixpacks";
        static: "static";
        railpack: "railpack";
    }>>>;
    railpackVersion: z.ZodNonOptional<z.ZodOptional<z.ZodNullable<z.ZodOptional<z.ZodString>>>>;
    herokuVersion: z.ZodNonOptional<z.ZodOptional<z.ZodNullable<z.ZodOptional<z.ZodString>>>>;
    publishDirectory: z.ZodOptional<z.ZodNullable<z.ZodOptional<z.ZodString>>>;
    isStaticSpa: z.ZodOptional<z.ZodNullable<z.ZodOptional<z.ZodBoolean>>>;
}, z.core.$strip>;
export declare const apiSaveGithubProvider: z.ZodObject<{
    owner: z.ZodNonOptional<z.ZodNonOptional<z.ZodOptional<z.ZodNullable<z.ZodString>>>>;
    githubId: z.ZodNonOptional<z.ZodNonOptional<z.ZodOptional<z.ZodNullable<z.ZodString>>>>;
    applicationId: z.ZodNonOptional<z.ZodNonOptional<z.ZodOptional<z.ZodString>>>;
    repository: z.ZodNonOptional<z.ZodNonOptional<z.ZodOptional<z.ZodNullable<z.ZodOptional<z.ZodString>>>>>;
    buildPath: z.ZodNonOptional<z.ZodNonOptional<z.ZodOptional<z.ZodNullable<z.ZodOptional<z.ZodString>>>>>;
    branch: z.ZodNonOptional<z.ZodString>;
    triggerType: z.ZodNonOptional<z.ZodDefault<z.ZodEnum<{
        push: "push";
        tag: "tag";
    }>>>;
    enableSubmodules: z.ZodOptional<z.ZodOptional<z.ZodBoolean>>;
    watchPaths: z.ZodOptional<z.ZodNullable<z.ZodOptional<z.ZodOptional<z.ZodArray<z.ZodString>>>>>;
}, z.core.$strip>;
export declare const apiSaveGitlabProvider: z.ZodObject<{
    gitlabId: z.ZodNonOptional<z.ZodOptional<z.ZodNullable<z.ZodString>>>;
    applicationId: z.ZodNonOptional<z.ZodOptional<z.ZodString>>;
    gitlabProjectId: z.ZodNonOptional<z.ZodOptional<z.ZodNullable<z.ZodNumber>>>;
    gitlabRepository: z.ZodNonOptional<z.ZodOptional<z.ZodNullable<z.ZodString>>>;
    gitlabOwner: z.ZodNonOptional<z.ZodOptional<z.ZodNullable<z.ZodString>>>;
    gitlabPathNamespace: z.ZodNonOptional<z.ZodOptional<z.ZodNullable<z.ZodString>>>;
    gitlabBuildPath: z.ZodNonOptional<z.ZodOptional<z.ZodNullable<z.ZodString>>>;
    gitlabBranch: z.ZodString;
    enableSubmodules: z.ZodOptional<z.ZodOptional<z.ZodBoolean>>;
    watchPaths: z.ZodOptional<z.ZodNullable<z.ZodOptional<z.ZodOptional<z.ZodArray<z.ZodString>>>>>;
}, z.core.$strip>;
export declare const apiSaveBitbucketProvider: z.ZodObject<{
    applicationId: z.ZodNonOptional<z.ZodOptional<z.ZodString>>;
    bitbucketRepository: z.ZodNonOptional<z.ZodOptional<z.ZodNullable<z.ZodString>>>;
    bitbucketRepositorySlug: z.ZodNonOptional<z.ZodOptional<z.ZodNullable<z.ZodString>>>;
    bitbucketOwner: z.ZodNonOptional<z.ZodOptional<z.ZodNullable<z.ZodString>>>;
    bitbucketId: z.ZodNonOptional<z.ZodOptional<z.ZodNullable<z.ZodString>>>;
    bitbucketBuildPath: z.ZodNonOptional<z.ZodOptional<z.ZodNullable<z.ZodString>>>;
    bitbucketBranch: z.ZodString;
    enableSubmodules: z.ZodOptional<z.ZodOptional<z.ZodBoolean>>;
    watchPaths: z.ZodOptional<z.ZodNullable<z.ZodOptional<z.ZodOptional<z.ZodArray<z.ZodString>>>>>;
}, z.core.$strip>;
export declare const apiSaveGiteaProvider: z.ZodObject<{
    giteaId: z.ZodNonOptional<z.ZodOptional<z.ZodNullable<z.ZodString>>>;
    applicationId: z.ZodNonOptional<z.ZodOptional<z.ZodString>>;
    giteaRepository: z.ZodNonOptional<z.ZodOptional<z.ZodNullable<z.ZodString>>>;
    giteaOwner: z.ZodNonOptional<z.ZodOptional<z.ZodNullable<z.ZodString>>>;
    giteaBuildPath: z.ZodNonOptional<z.ZodOptional<z.ZodNullable<z.ZodString>>>;
    giteaBranch: z.ZodString;
    enableSubmodules: z.ZodOptional<z.ZodOptional<z.ZodBoolean>>;
    watchPaths: z.ZodOptional<z.ZodNullable<z.ZodOptional<z.ZodOptional<z.ZodArray<z.ZodString>>>>>;
}, z.core.$strip>;
export declare const apiSaveDockerProvider: z.ZodObject<{
    applicationId: z.ZodNonOptional<z.ZodOptional<z.ZodString>>;
    username: z.ZodNonOptional<z.ZodOptional<z.ZodNullable<z.ZodOptional<z.ZodString>>>>;
    password: z.ZodNonOptional<z.ZodOptional<z.ZodNullable<z.ZodOptional<z.ZodString>>>>;
    dockerImage: z.ZodNonOptional<z.ZodOptional<z.ZodNullable<z.ZodOptional<z.ZodString>>>>;
    registryUrl: z.ZodNonOptional<z.ZodOptional<z.ZodNullable<z.ZodOptional<z.ZodString>>>>;
}, z.core.$strip>;
export declare const apiSaveGitProvider: z.ZodObject<{
    applicationId: z.ZodNonOptional<z.ZodOptional<z.ZodString>>;
    customGitUrl: z.ZodNonOptional<z.ZodOptional<z.ZodNullable<z.ZodOptional<z.ZodString>>>>;
    watchPaths: z.ZodNonOptional<z.ZodOptional<z.ZodNullable<z.ZodOptional<z.ZodOptional<z.ZodArray<z.ZodString>>>>>>;
    customGitBuildPath: z.ZodNonOptional<z.ZodOptional<z.ZodNullable<z.ZodOptional<z.ZodString>>>>;
    customGitBranch: z.ZodString;
    customGitSSHKeyId: z.ZodOptional<z.ZodNullable<z.ZodOptional<z.ZodString>>>;
    enableSubmodules: z.ZodOptional<z.ZodOptional<z.ZodBoolean>>;
}, z.core.$strip>;
export declare const apiSaveEnvironmentVariables: z.ZodObject<{
    applicationId: z.ZodNonOptional<z.ZodOptional<z.ZodString>>;
    env: z.ZodNonOptional<z.ZodOptional<z.ZodNullable<z.ZodOptional<z.ZodString>>>>;
    buildArgs: z.ZodNonOptional<z.ZodOptional<z.ZodNullable<z.ZodOptional<z.ZodString>>>>;
    buildSecrets: z.ZodNonOptional<z.ZodOptional<z.ZodNullable<z.ZodOptional<z.ZodString>>>>;
    createEnvFile: z.ZodNonOptional<z.ZodOptional<z.ZodOptional<z.ZodBoolean>>>;
}, z.core.$strip>;
export declare const apiFindMonitoringStats: z.ZodObject<{
    appName: z.ZodString;
}, z.core.$strip>;
export declare const apiUpdateApplication: z.ZodObject<{
    applicationStatus: z.ZodOptional<z.ZodOptional<z.ZodEnum<{
        idle: "idle";
        running: "running";
        done: "done";
        error: "error";
    }>>>;
    triggerType: z.ZodOptional<z.ZodOptional<z.ZodNullable<z.ZodOptional<z.ZodEnum<{
        push: "push";
        tag: "tag";
    }>>>>>;
    giteaId: z.ZodOptional<z.ZodOptional<z.ZodNullable<z.ZodString>>>;
    name: z.ZodOptional<z.ZodString>;
    createdAt: z.ZodOptional<z.ZodOptional<z.ZodString>>;
    refreshToken: z.ZodOptional<z.ZodOptional<z.ZodNullable<z.ZodString>>>;
    description: z.ZodOptional<z.ZodOptional<z.ZodNullable<z.ZodOptional<z.ZodString>>>>;
    owner: z.ZodOptional<z.ZodOptional<z.ZodNullable<z.ZodString>>>;
    githubId: z.ZodOptional<z.ZodOptional<z.ZodNullable<z.ZodString>>>;
    gitlabId: z.ZodOptional<z.ZodOptional<z.ZodNullable<z.ZodString>>>;
    applicationId: z.ZodString;
    appName: z.ZodOptional<z.ZodOptional<z.ZodOptional<z.ZodString>>>;
    env: z.ZodOptional<z.ZodOptional<z.ZodNullable<z.ZodOptional<z.ZodString>>>>;
    sourceType: z.ZodOptional<z.ZodOptional<z.ZodOptional<z.ZodEnum<{
        gitea: "gitea";
        github: "github";
        gitlab: "gitlab";
        bitbucket: "bitbucket";
        git: "git";
        docker: "docker";
        drop: "drop";
    }>>>>;
    repository: z.ZodOptional<z.ZodOptional<z.ZodNullable<z.ZodOptional<z.ZodString>>>>;
    branch: z.ZodOptional<z.ZodOptional<z.ZodNullable<z.ZodOptional<z.ZodString>>>>;
    autoDeploy: z.ZodOptional<z.ZodOptional<z.ZodNullable<z.ZodBoolean>>>;
    gitlabProjectId: z.ZodOptional<z.ZodOptional<z.ZodNullable<z.ZodNumber>>>;
    gitlabRepository: z.ZodOptional<z.ZodOptional<z.ZodNullable<z.ZodString>>>;
    gitlabOwner: z.ZodOptional<z.ZodOptional<z.ZodNullable<z.ZodString>>>;
    gitlabBranch: z.ZodOptional<z.ZodOptional<z.ZodNullable<z.ZodString>>>;
    gitlabPathNamespace: z.ZodOptional<z.ZodOptional<z.ZodNullable<z.ZodString>>>;
    bitbucketRepository: z.ZodOptional<z.ZodOptional<z.ZodNullable<z.ZodString>>>;
    bitbucketRepositorySlug: z.ZodOptional<z.ZodOptional<z.ZodNullable<z.ZodString>>>;
    bitbucketOwner: z.ZodOptional<z.ZodOptional<z.ZodNullable<z.ZodString>>>;
    bitbucketBranch: z.ZodOptional<z.ZodOptional<z.ZodNullable<z.ZodString>>>;
    giteaRepository: z.ZodOptional<z.ZodOptional<z.ZodNullable<z.ZodString>>>;
    giteaOwner: z.ZodOptional<z.ZodOptional<z.ZodNullable<z.ZodString>>>;
    giteaBranch: z.ZodOptional<z.ZodOptional<z.ZodNullable<z.ZodString>>>;
    customGitUrl: z.ZodOptional<z.ZodOptional<z.ZodNullable<z.ZodOptional<z.ZodString>>>>;
    customGitBranch: z.ZodOptional<z.ZodOptional<z.ZodNullable<z.ZodOptional<z.ZodString>>>>;
    customGitSSHKeyId: z.ZodOptional<z.ZodOptional<z.ZodNullable<z.ZodOptional<z.ZodString>>>>;
    command: z.ZodOptional<z.ZodOptional<z.ZodNullable<z.ZodString>>>;
    enableSubmodules: z.ZodOptional<z.ZodOptional<z.ZodOptional<z.ZodBoolean>>>;
    environmentId: z.ZodOptional<z.ZodString>;
    watchPaths: z.ZodOptional<z.ZodOptional<z.ZodNullable<z.ZodOptional<z.ZodOptional<z.ZodArray<z.ZodString>>>>>>;
    bitbucketId: z.ZodOptional<z.ZodOptional<z.ZodNullable<z.ZodString>>>;
    username: z.ZodOptional<z.ZodOptional<z.ZodNullable<z.ZodOptional<z.ZodString>>>>;
    previewEnv: z.ZodOptional<z.ZodOptional<z.ZodNullable<z.ZodOptional<z.ZodString>>>>;
    previewBuildArgs: z.ZodOptional<z.ZodOptional<z.ZodNullable<z.ZodOptional<z.ZodString>>>>;
    previewBuildSecrets: z.ZodOptional<z.ZodOptional<z.ZodNullable<z.ZodOptional<z.ZodString>>>>;
    previewLabels: z.ZodOptional<z.ZodOptional<z.ZodNullable<z.ZodOptional<z.ZodArray<z.ZodString>>>>>;
    previewWildcard: z.ZodOptional<z.ZodOptional<z.ZodNullable<z.ZodOptional<z.ZodString>>>>;
    previewPort: z.ZodOptional<z.ZodOptional<z.ZodNullable<z.ZodOptional<z.ZodNumber>>>>;
    previewHttps: z.ZodOptional<z.ZodOptional<z.ZodOptional<z.ZodBoolean>>>;
    previewPath: z.ZodOptional<z.ZodOptional<z.ZodNullable<z.ZodOptional<z.ZodString>>>>;
    previewCertificateType: z.ZodOptional<z.ZodOptional<z.ZodOptional<z.ZodEnum<{
        letsencrypt: "letsencrypt";
        none: "none";
        custom: "custom";
    }>>>>;
    previewCustomCertResolver: z.ZodOptional<z.ZodOptional<z.ZodNullable<z.ZodString>>>;
    previewLimit: z.ZodOptional<z.ZodOptional<z.ZodNullable<z.ZodOptional<z.ZodNumber>>>>;
    isPreviewDeploymentsActive: z.ZodOptional<z.ZodOptional<z.ZodNullable<z.ZodOptional<z.ZodBoolean>>>>;
    previewRequireCollaboratorPermissions: z.ZodOptional<z.ZodOptional<z.ZodNullable<z.ZodOptional<z.ZodBoolean>>>>;
    rollbackActive: z.ZodOptional<z.ZodOptional<z.ZodNullable<z.ZodBoolean>>>;
    buildArgs: z.ZodOptional<z.ZodOptional<z.ZodNullable<z.ZodOptional<z.ZodString>>>>;
    buildSecrets: z.ZodOptional<z.ZodOptional<z.ZodNullable<z.ZodOptional<z.ZodString>>>>;
    memoryReservation: z.ZodOptional<z.ZodOptional<z.ZodNullable<z.ZodOptional<z.ZodString>>>>;
    memoryLimit: z.ZodOptional<z.ZodOptional<z.ZodNullable<z.ZodOptional<z.ZodString>>>>;
    cpuReservation: z.ZodOptional<z.ZodOptional<z.ZodNullable<z.ZodOptional<z.ZodString>>>>;
    cpuLimit: z.ZodOptional<z.ZodOptional<z.ZodNullable<z.ZodOptional<z.ZodString>>>>;
    title: z.ZodOptional<z.ZodOptional<z.ZodNullable<z.ZodOptional<z.ZodString>>>>;
    enabled: z.ZodOptional<z.ZodOptional<z.ZodNullable<z.ZodOptional<z.ZodBoolean>>>>;
    subtitle: z.ZodOptional<z.ZodOptional<z.ZodNullable<z.ZodOptional<z.ZodString>>>>;
    args: z.ZodOptional<z.ZodOptional<z.ZodNullable<z.ZodOptional<z.ZodArray<z.ZodString>>>>>;
    icon: z.ZodOptional<z.ZodOptional<z.ZodNullable<z.ZodOptional<z.ZodNullable<z.ZodString>>>>>;
    cleanCache: z.ZodOptional<z.ZodOptional<z.ZodNullable<z.ZodOptional<z.ZodBoolean>>>>;
    buildPath: z.ZodOptional<z.ZodOptional<z.ZodNullable<z.ZodOptional<z.ZodString>>>>;
    gitlabBuildPath: z.ZodOptional<z.ZodOptional<z.ZodNullable<z.ZodString>>>;
    giteaBuildPath: z.ZodOptional<z.ZodOptional<z.ZodNullable<z.ZodString>>>;
    bitbucketBuildPath: z.ZodOptional<z.ZodOptional<z.ZodNullable<z.ZodString>>>;
    password: z.ZodOptional<z.ZodOptional<z.ZodNullable<z.ZodOptional<z.ZodString>>>>;
    dockerImage: z.ZodOptional<z.ZodOptional<z.ZodNullable<z.ZodOptional<z.ZodString>>>>;
    registryUrl: z.ZodOptional<z.ZodOptional<z.ZodNullable<z.ZodOptional<z.ZodString>>>>;
    customGitBuildPath: z.ZodOptional<z.ZodOptional<z.ZodNullable<z.ZodOptional<z.ZodString>>>>;
    dockerfile: z.ZodOptional<z.ZodOptional<z.ZodNullable<z.ZodOptional<z.ZodString>>>>;
    dockerContextPath: z.ZodOptional<z.ZodOptional<z.ZodNullable<z.ZodString>>>;
    dockerBuildStage: z.ZodOptional<z.ZodOptional<z.ZodNullable<z.ZodString>>>;
    dropBuildPath: z.ZodOptional<z.ZodOptional<z.ZodNullable<z.ZodString>>>;
    healthCheckSwarm: z.ZodOptional<z.ZodOptional<z.ZodNullable<z.ZodNullable<z.ZodObject<{
        Test: z.ZodOptional<z.ZodArray<z.ZodString>>;
        Interval: z.ZodOptional<z.ZodNumber>;
        Timeout: z.ZodOptional<z.ZodNumber>;
        StartPeriod: z.ZodOptional<z.ZodNumber>;
        Retries: z.ZodOptional<z.ZodNumber>;
    }, z.core.$strict>>>>>;
    restartPolicySwarm: z.ZodOptional<z.ZodOptional<z.ZodNullable<z.ZodNullable<z.ZodObject<{
        Condition: z.ZodOptional<z.ZodString>;
        Delay: z.ZodOptional<z.ZodNumber>;
        MaxAttempts: z.ZodOptional<z.ZodNumber>;
        Window: z.ZodOptional<z.ZodNumber>;
    }, z.core.$strict>>>>>;
    placementSwarm: z.ZodOptional<z.ZodOptional<z.ZodNullable<z.ZodNullable<z.ZodObject<{
        Constraints: z.ZodOptional<z.ZodArray<z.ZodString>>;
        Preferences: z.ZodOptional<z.ZodArray<z.ZodObject<{
            Spread: z.ZodObject<{
                SpreadDescriptor: z.ZodString;
            }, z.core.$strip>;
        }, z.core.$strict>>>;
        MaxReplicas: z.ZodOptional<z.ZodNumber>;
        Platforms: z.ZodOptional<z.ZodArray<z.ZodObject<{
            Architecture: z.ZodString;
            OS: z.ZodString;
        }, z.core.$strict>>>;
    }, z.core.$strict>>>>>;
    updateConfigSwarm: z.ZodOptional<z.ZodOptional<z.ZodNullable<z.ZodNullable<z.ZodObject<{
        Parallelism: z.ZodNumber;
        Delay: z.ZodOptional<z.ZodNumber>;
        FailureAction: z.ZodOptional<z.ZodString>;
        Monitor: z.ZodOptional<z.ZodNumber>;
        MaxFailureRatio: z.ZodOptional<z.ZodNumber>;
        Order: z.ZodString;
    }, z.core.$strict>>>>>;
    rollbackConfigSwarm: z.ZodOptional<z.ZodOptional<z.ZodNullable<z.ZodNullable<z.ZodObject<{
        Parallelism: z.ZodNumber;
        Delay: z.ZodOptional<z.ZodNumber>;
        FailureAction: z.ZodOptional<z.ZodString>;
        Monitor: z.ZodOptional<z.ZodNumber>;
        MaxFailureRatio: z.ZodOptional<z.ZodNumber>;
        Order: z.ZodString;
    }, z.core.$strict>>>>>;
    modeSwarm: z.ZodOptional<z.ZodOptional<z.ZodNullable<z.ZodNullable<z.ZodObject<{
        Replicated: z.ZodOptional<z.ZodObject<{
            Replicas: z.ZodOptional<z.ZodNumber>;
        }, z.core.$strict>>;
        Global: z.ZodOptional<z.ZodObject<{}, z.core.$strip>>;
        ReplicatedJob: z.ZodOptional<z.ZodObject<{
            MaxConcurrent: z.ZodOptional<z.ZodNumber>;
            TotalCompletions: z.ZodOptional<z.ZodNumber>;
        }, z.core.$strict>>;
        GlobalJob: z.ZodOptional<z.ZodObject<{}, z.core.$strip>>;
    }, z.core.$strict>>>>>;
    labelsSwarm: z.ZodOptional<z.ZodOptional<z.ZodNullable<z.ZodNullable<z.ZodRecord<z.ZodString, z.ZodString>>>>>;
    networkSwarm: z.ZodOptional<z.ZodOptional<z.ZodNullable<z.ZodNullable<z.ZodArray<z.ZodObject<{
        Target: z.ZodOptional<z.ZodString>;
        Aliases: z.ZodOptional<z.ZodArray<z.ZodString>>;
        DriverOpts: z.ZodOptional<z.ZodRecord<z.ZodString, z.ZodString>>;
    }, z.core.$strict>>>>>>;
    stopGracePeriodSwarm: z.ZodOptional<z.ZodOptional<z.ZodNullable<z.ZodNullable<z.ZodNumber>>>>;
    endpointSpecSwarm: z.ZodOptional<z.ZodOptional<z.ZodNullable<z.ZodNullable<z.ZodObject<{
        Mode: z.ZodOptional<z.ZodString>;
        Ports: z.ZodOptional<z.ZodArray<z.ZodObject<{
            Protocol: z.ZodOptional<z.ZodString>;
            TargetPort: z.ZodOptional<z.ZodNumber>;
            PublishedPort: z.ZodOptional<z.ZodNumber>;
            PublishMode: z.ZodOptional<z.ZodString>;
        }, z.core.$strict>>>;
    }, z.core.$strict>>>>>;
    ulimitsSwarm: z.ZodOptional<z.ZodOptional<z.ZodNullable<z.ZodNullable<z.ZodArray<z.ZodObject<{
        Name: z.ZodString;
        Soft: z.ZodNumber;
        Hard: z.ZodNumber;
    }, z.core.$strict>>>>>>;
    replicas: z.ZodOptional<z.ZodOptional<z.ZodNumber>>;
    buildType: z.ZodOptional<z.ZodOptional<z.ZodEnum<{
        dockerfile: "dockerfile";
        heroku_buildpacks: "heroku_buildpacks";
        paketo_buildpacks: "paketo_buildpacks";
        nixpacks: "nixpacks";
        static: "static";
        railpack: "railpack";
    }>>>;
    railpackVersion: z.ZodOptional<z.ZodOptional<z.ZodNullable<z.ZodOptional<z.ZodString>>>>;
    herokuVersion: z.ZodOptional<z.ZodOptional<z.ZodNullable<z.ZodOptional<z.ZodString>>>>;
    publishDirectory: z.ZodOptional<z.ZodOptional<z.ZodNullable<z.ZodOptional<z.ZodString>>>>;
    isStaticSpa: z.ZodOptional<z.ZodOptional<z.ZodNullable<z.ZodOptional<z.ZodBoolean>>>>;
    createEnvFile: z.ZodOptional<z.ZodOptional<z.ZodOptional<z.ZodBoolean>>>;
    registryId: z.ZodOptional<z.ZodOptional<z.ZodNullable<z.ZodString>>>;
    rollbackRegistryId: z.ZodOptional<z.ZodOptional<z.ZodNullable<z.ZodString>>>;
    buildServerId: z.ZodOptional<z.ZodOptional<z.ZodNullable<z.ZodString>>>;
    buildRegistryId: z.ZodOptional<z.ZodOptional<z.ZodNullable<z.ZodString>>>;
}, z.core.$strip>;
//# sourceMappingURL=application.d.ts.map