import { z } from "zod";
export declare const sourceTypeCompose: import("drizzle-orm/pg-core").PgEnum<["git", "github", "gitlab", "bitbucket", "gitea", "raw"]>;
export declare const composeType: import("drizzle-orm/pg-core").PgEnum<["docker-compose", "stack"]>;
export declare const compose: import("drizzle-orm/pg-core").PgTableWithColumns<{
    name: "compose";
    schema: undefined;
    columns: {
        composeId: import("drizzle-orm/pg-core").PgColumn<{
            name: "composeId";
            tableName: "compose";
            dataType: "string";
            columnType: "PgText";
            data: string;
            driverParam: string;
            notNull: true;
            hasDefault: true;
            isPrimaryKey: true;
            isAutoincrement: false;
            hasRuntimeDefault: true;
            enumValues: [string, ...string[]];
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        name: import("drizzle-orm/pg-core").PgColumn<{
            name: "name";
            tableName: "compose";
            dataType: "string";
            columnType: "PgText";
            data: string;
            driverParam: string;
            notNull: true;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        appName: import("drizzle-orm/pg-core").PgColumn<{
            name: "appName";
            tableName: "compose";
            dataType: "string";
            columnType: "PgText";
            data: string;
            driverParam: string;
            notNull: true;
            hasDefault: true;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: true;
            enumValues: [string, ...string[]];
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        description: import("drizzle-orm/pg-core").PgColumn<{
            name: "description";
            tableName: "compose";
            dataType: "string";
            columnType: "PgText";
            data: string;
            driverParam: string;
            notNull: false;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        env: import("drizzle-orm/pg-core").PgColumn<{
            name: "env";
            tableName: "compose";
            dataType: "string";
            columnType: "PgText";
            data: string;
            driverParam: string;
            notNull: false;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        composeFile: import("drizzle-orm/pg-core").PgColumn<{
            name: "composeFile";
            tableName: "compose";
            dataType: "string";
            columnType: "PgText";
            data: string;
            driverParam: string;
            notNull: true;
            hasDefault: true;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        refreshToken: import("drizzle-orm/pg-core").PgColumn<{
            name: "refreshToken";
            tableName: "compose";
            dataType: "string";
            columnType: "PgText";
            data: string;
            driverParam: string;
            notNull: false;
            hasDefault: true;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: true;
            enumValues: [string, ...string[]];
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        sourceType: import("drizzle-orm/pg-core").PgColumn<{
            name: "sourceType";
            tableName: "compose";
            dataType: "string";
            columnType: "PgEnumColumn";
            data: "gitea" | "github" | "gitlab" | "bitbucket" | "raw" | "git";
            driverParam: string;
            notNull: true;
            hasDefault: true;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: ["git", "github", "gitlab", "bitbucket", "gitea", "raw"];
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        composeType: import("drizzle-orm/pg-core").PgColumn<{
            name: "composeType";
            tableName: "compose";
            dataType: "string";
            columnType: "PgEnumColumn";
            data: "docker-compose" | "stack";
            driverParam: string;
            notNull: true;
            hasDefault: true;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: ["docker-compose", "stack"];
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        repository: import("drizzle-orm/pg-core").PgColumn<{
            name: "repository";
            tableName: "compose";
            dataType: "string";
            columnType: "PgText";
            data: string;
            driverParam: string;
            notNull: false;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        owner: import("drizzle-orm/pg-core").PgColumn<{
            name: "owner";
            tableName: "compose";
            dataType: "string";
            columnType: "PgText";
            data: string;
            driverParam: string;
            notNull: false;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        branch: import("drizzle-orm/pg-core").PgColumn<{
            name: "branch";
            tableName: "compose";
            dataType: "string";
            columnType: "PgText";
            data: string;
            driverParam: string;
            notNull: false;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        autoDeploy: import("drizzle-orm/pg-core").PgColumn<{
            name: "autoDeploy";
            tableName: "compose";
            dataType: "boolean";
            columnType: "PgBoolean";
            data: boolean;
            driverParam: boolean;
            notNull: false;
            hasDefault: true;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: true;
            enumValues: undefined;
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        gitlabProjectId: import("drizzle-orm/pg-core").PgColumn<{
            name: "gitlabProjectId";
            tableName: "compose";
            dataType: "number";
            columnType: "PgInteger";
            data: number;
            driverParam: string | number;
            notNull: false;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: undefined;
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        gitlabRepository: import("drizzle-orm/pg-core").PgColumn<{
            name: "gitlabRepository";
            tableName: "compose";
            dataType: "string";
            columnType: "PgText";
            data: string;
            driverParam: string;
            notNull: false;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        gitlabOwner: import("drizzle-orm/pg-core").PgColumn<{
            name: "gitlabOwner";
            tableName: "compose";
            dataType: "string";
            columnType: "PgText";
            data: string;
            driverParam: string;
            notNull: false;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        gitlabBranch: import("drizzle-orm/pg-core").PgColumn<{
            name: "gitlabBranch";
            tableName: "compose";
            dataType: "string";
            columnType: "PgText";
            data: string;
            driverParam: string;
            notNull: false;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        gitlabPathNamespace: import("drizzle-orm/pg-core").PgColumn<{
            name: "gitlabPathNamespace";
            tableName: "compose";
            dataType: "string";
            columnType: "PgText";
            data: string;
            driverParam: string;
            notNull: false;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        bitbucketRepository: import("drizzle-orm/pg-core").PgColumn<{
            name: "bitbucketRepository";
            tableName: "compose";
            dataType: "string";
            columnType: "PgText";
            data: string;
            driverParam: string;
            notNull: false;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        bitbucketRepositorySlug: import("drizzle-orm/pg-core").PgColumn<{
            name: "bitbucketRepositorySlug";
            tableName: "compose";
            dataType: "string";
            columnType: "PgText";
            data: string;
            driverParam: string;
            notNull: false;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        bitbucketOwner: import("drizzle-orm/pg-core").PgColumn<{
            name: "bitbucketOwner";
            tableName: "compose";
            dataType: "string";
            columnType: "PgText";
            data: string;
            driverParam: string;
            notNull: false;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        bitbucketBranch: import("drizzle-orm/pg-core").PgColumn<{
            name: "bitbucketBranch";
            tableName: "compose";
            dataType: "string";
            columnType: "PgText";
            data: string;
            driverParam: string;
            notNull: false;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        giteaRepository: import("drizzle-orm/pg-core").PgColumn<{
            name: "giteaRepository";
            tableName: "compose";
            dataType: "string";
            columnType: "PgText";
            data: string;
            driverParam: string;
            notNull: false;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        giteaOwner: import("drizzle-orm/pg-core").PgColumn<{
            name: "giteaOwner";
            tableName: "compose";
            dataType: "string";
            columnType: "PgText";
            data: string;
            driverParam: string;
            notNull: false;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        giteaBranch: import("drizzle-orm/pg-core").PgColumn<{
            name: "giteaBranch";
            tableName: "compose";
            dataType: "string";
            columnType: "PgText";
            data: string;
            driverParam: string;
            notNull: false;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        customGitUrl: import("drizzle-orm/pg-core").PgColumn<{
            name: "customGitUrl";
            tableName: "compose";
            dataType: "string";
            columnType: "PgText";
            data: string;
            driverParam: string;
            notNull: false;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        customGitBranch: import("drizzle-orm/pg-core").PgColumn<{
            name: "customGitBranch";
            tableName: "compose";
            dataType: "string";
            columnType: "PgText";
            data: string;
            driverParam: string;
            notNull: false;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        customGitSSHKeyId: import("drizzle-orm/pg-core").PgColumn<{
            name: "customGitSSHKeyId";
            tableName: "compose";
            dataType: "string";
            columnType: "PgText";
            data: string;
            driverParam: string;
            notNull: false;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        command: import("drizzle-orm/pg-core").PgColumn<{
            name: "command";
            tableName: "compose";
            dataType: "string";
            columnType: "PgText";
            data: string;
            driverParam: string;
            notNull: true;
            hasDefault: true;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        enableSubmodules: import("drizzle-orm/pg-core").PgColumn<{
            name: "enableSubmodules";
            tableName: "compose";
            dataType: "boolean";
            columnType: "PgBoolean";
            data: boolean;
            driverParam: boolean;
            notNull: true;
            hasDefault: true;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: undefined;
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        composePath: import("drizzle-orm/pg-core").PgColumn<{
            name: "composePath";
            tableName: "compose";
            dataType: "string";
            columnType: "PgText";
            data: string;
            driverParam: string;
            notNull: true;
            hasDefault: true;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        suffix: import("drizzle-orm/pg-core").PgColumn<{
            name: "suffix";
            tableName: "compose";
            dataType: "string";
            columnType: "PgText";
            data: string;
            driverParam: string;
            notNull: true;
            hasDefault: true;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        randomize: import("drizzle-orm/pg-core").PgColumn<{
            name: "randomize";
            tableName: "compose";
            dataType: "boolean";
            columnType: "PgBoolean";
            data: boolean;
            driverParam: boolean;
            notNull: true;
            hasDefault: true;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: undefined;
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        isolatedDeployment: import("drizzle-orm/pg-core").PgColumn<{
            name: "isolatedDeployment";
            tableName: "compose";
            dataType: "boolean";
            columnType: "PgBoolean";
            data: boolean;
            driverParam: boolean;
            notNull: true;
            hasDefault: true;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: undefined;
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        isolatedDeploymentsVolume: import("drizzle-orm/pg-core").PgColumn<{
            name: "isolatedDeploymentsVolume";
            tableName: "compose";
            dataType: "boolean";
            columnType: "PgBoolean";
            data: boolean;
            driverParam: boolean;
            notNull: true;
            hasDefault: true;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: undefined;
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        triggerType: import("drizzle-orm/pg-core").PgColumn<{
            name: "triggerType";
            tableName: "compose";
            dataType: "string";
            columnType: "PgEnumColumn";
            data: "push" | "tag";
            driverParam: string;
            notNull: false;
            hasDefault: true;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: ["push", "tag"];
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        composeStatus: import("drizzle-orm/pg-core").PgColumn<{
            name: "composeStatus";
            tableName: "compose";
            dataType: "string";
            columnType: "PgEnumColumn";
            data: "idle" | "running" | "done" | "error";
            driverParam: string;
            notNull: true;
            hasDefault: true;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: ["idle", "running", "done", "error"];
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        environmentId: import("drizzle-orm/pg-core").PgColumn<{
            name: "environmentId";
            tableName: "compose";
            dataType: "string";
            columnType: "PgText";
            data: string;
            driverParam: string;
            notNull: true;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        createdAt: import("drizzle-orm/pg-core").PgColumn<{
            name: "createdAt";
            tableName: "compose";
            dataType: "string";
            columnType: "PgText";
            data: string;
            driverParam: string;
            notNull: true;
            hasDefault: true;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: true;
            enumValues: [string, ...string[]];
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        watchPaths: import("drizzle-orm/pg-core").PgColumn<{
            name: "watchPaths";
            tableName: "compose";
            dataType: "array";
            columnType: "PgArray";
            data: string[];
            driverParam: string | string[];
            notNull: false;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: import("drizzle-orm").Column<{
                name: "watchPaths";
                tableName: "compose";
                dataType: "string";
                columnType: "PgText";
                data: string;
                driverParam: string;
                notNull: false;
                hasDefault: false;
                isPrimaryKey: false;
                isAutoincrement: false;
                hasRuntimeDefault: false;
                enumValues: [string, ...string[]];
                baseColumn: never;
                identity: undefined;
                generated: undefined;
            }, {}, {}>;
            identity: undefined;
            generated: undefined;
        }, {}, {
            baseBuilder: import("drizzle-orm/pg-core").PgColumnBuilder<{
                name: "watchPaths";
                dataType: "string";
                columnType: "PgText";
                data: string;
                enumValues: [string, ...string[]];
                driverParam: string;
            }, {}, {}, import("drizzle-orm").ColumnBuilderExtraConfig>;
            size: undefined;
        }>;
        githubId: import("drizzle-orm/pg-core").PgColumn<{
            name: "githubId";
            tableName: "compose";
            dataType: "string";
            columnType: "PgText";
            data: string;
            driverParam: string;
            notNull: false;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        gitlabId: import("drizzle-orm/pg-core").PgColumn<{
            name: "gitlabId";
            tableName: "compose";
            dataType: "string";
            columnType: "PgText";
            data: string;
            driverParam: string;
            notNull: false;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        bitbucketId: import("drizzle-orm/pg-core").PgColumn<{
            name: "bitbucketId";
            tableName: "compose";
            dataType: "string";
            columnType: "PgText";
            data: string;
            driverParam: string;
            notNull: false;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        giteaId: import("drizzle-orm/pg-core").PgColumn<{
            name: "giteaId";
            tableName: "compose";
            dataType: "string";
            columnType: "PgText";
            data: string;
            driverParam: string;
            notNull: false;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        serverId: import("drizzle-orm/pg-core").PgColumn<{
            name: "serverId";
            tableName: "compose";
            dataType: "string";
            columnType: "PgText";
            data: string;
            driverParam: string;
            notNull: false;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
    };
    dialect: "pg";
}>;
export declare const composeRelations: import("drizzle-orm").Relations<"compose", {
    environment: import("drizzle-orm").One<"environment", true>;
    deployments: import("drizzle-orm").Many<"deployment">;
    mounts: import("drizzle-orm").Many<"mount">;
    customGitSSHKey: import("drizzle-orm").One<"ssh-key", false>;
    domains: import("drizzle-orm").Many<"domain">;
    github: import("drizzle-orm").One<"github", false>;
    gitlab: import("drizzle-orm").One<"gitlab", false>;
    bitbucket: import("drizzle-orm").One<"bitbucket", false>;
    gitea: import("drizzle-orm").One<"gitea", false>;
    server: import("drizzle-orm").One<"server", false>;
    backups: import("drizzle-orm").Many<"backup">;
    schedules: import("drizzle-orm").Many<"schedule">;
    patches: import("drizzle-orm").Many<"patch">;
}>;
export declare const apiCreateCompose: z.ZodObject<{
    name: z.ZodString;
    description: z.ZodOptional<z.ZodNullable<z.ZodString>>;
    appName: z.ZodOptional<z.ZodOptional<z.ZodString>>;
    composeFile: z.ZodOptional<z.ZodOptional<z.ZodString>>;
    composeType: z.ZodOptional<z.ZodOptional<z.ZodEnum<{
        "docker-compose": "docker-compose";
        stack: "stack";
    }>>>;
    environmentId: z.ZodString;
    serverId: z.ZodOptional<z.ZodNullable<z.ZodString>>;
}, z.core.$strip>;
export declare const apiCreateComposeByTemplate: z.ZodObject<{
    environmentId: z.ZodString;
    id: z.ZodString;
    serverId: z.ZodOptional<z.ZodString>;
}, z.core.$strip>;
export declare const apiFindCompose: z.ZodObject<{
    composeId: z.ZodString;
}, z.core.$strip>;
export declare const apiDeployCompose: z.ZodObject<{
    composeId: z.ZodString;
    title: z.ZodOptional<z.ZodString>;
    description: z.ZodOptional<z.ZodString>;
}, z.core.$strip>;
export declare const apiRedeployCompose: z.ZodObject<{
    composeId: z.ZodString;
    title: z.ZodOptional<z.ZodString>;
    description: z.ZodOptional<z.ZodString>;
}, z.core.$strip>;
export declare const apiDeleteCompose: z.ZodObject<{
    composeId: z.ZodString;
    deleteVolumes: z.ZodBoolean;
}, z.core.$strip>;
export declare const apiFetchServices: z.ZodObject<{
    composeId: z.ZodString;
    type: z.ZodDefault<z.ZodOptional<z.ZodEnum<{
        fetch: "fetch";
        cache: "cache";
    }>>>;
}, z.core.$strip>;
export declare const apiUpdateCompose: z.ZodObject<{
    triggerType: z.ZodOptional<z.ZodOptional<z.ZodNullable<z.ZodOptional<z.ZodEnum<{
        push: "push";
        tag: "tag";
    }>>>>>;
    giteaId: z.ZodOptional<z.ZodOptional<z.ZodNullable<z.ZodString>>>;
    name: z.ZodOptional<z.ZodString>;
    createdAt: z.ZodOptional<z.ZodOptional<z.ZodString>>;
    refreshToken: z.ZodOptional<z.ZodOptional<z.ZodNullable<z.ZodString>>>;
    description: z.ZodOptional<z.ZodOptional<z.ZodNullable<z.ZodString>>>;
    owner: z.ZodOptional<z.ZodOptional<z.ZodNullable<z.ZodString>>>;
    githubId: z.ZodOptional<z.ZodOptional<z.ZodNullable<z.ZodString>>>;
    gitlabId: z.ZodOptional<z.ZodOptional<z.ZodNullable<z.ZodString>>>;
    composeId: z.ZodString;
    appName: z.ZodOptional<z.ZodOptional<z.ZodOptional<z.ZodString>>>;
    env: z.ZodOptional<z.ZodOptional<z.ZodNullable<z.ZodOptional<z.ZodString>>>>;
    composeFile: z.ZodOptional<z.ZodString>;
    sourceType: z.ZodOptional<z.ZodOptional<z.ZodOptional<z.ZodEnum<{
        gitea: "gitea";
        github: "github";
        gitlab: "gitlab";
        bitbucket: "bitbucket";
        raw: "raw";
        git: "git";
    }>>>>;
    composeType: z.ZodOptional<z.ZodOptional<z.ZodOptional<z.ZodEnum<{
        "docker-compose": "docker-compose";
        stack: "stack";
    }>>>>;
    repository: z.ZodOptional<z.ZodOptional<z.ZodNullable<z.ZodString>>>;
    branch: z.ZodOptional<z.ZodOptional<z.ZodNullable<z.ZodString>>>;
    autoDeploy: z.ZodOptional<z.ZodOptional<z.ZodNullable<z.ZodBoolean>>>;
    gitlabProjectId: z.ZodOptional<z.ZodOptional<z.ZodNullable<z.ZodNumber>>>;
    gitlabRepository: z.ZodOptional<z.ZodOptional<z.ZodNullable<z.ZodString>>>;
    gitlabOwner: z.ZodOptional<z.ZodOptional<z.ZodNullable<z.ZodString>>>;
    gitlabBranch: z.ZodOptional<z.ZodOptional<z.ZodNullable<z.ZodString>>>;
    gitlabPathNamespace: z.ZodOptional<z.ZodOptional<z.ZodNullable<z.ZodString>>>;
    bitbucketRepository: z.ZodOptional<z.ZodOptional<z.ZodNullable<z.ZodString>>>;
    bitbucketRepositorySlug: z.ZodOptional<z.ZodOptional<z.ZodNullable<z.ZodString>>>;
    bitbucketOwner: z.ZodOptional<z.ZodOptional<z.ZodNullable<z.ZodString>>>;
    bitbucketBranch: z.ZodOptional<z.ZodOptional<z.ZodNullable<z.ZodString>>>;
    giteaRepository: z.ZodOptional<z.ZodOptional<z.ZodNullable<z.ZodString>>>;
    giteaOwner: z.ZodOptional<z.ZodOptional<z.ZodNullable<z.ZodString>>>;
    giteaBranch: z.ZodOptional<z.ZodOptional<z.ZodNullable<z.ZodString>>>;
    customGitUrl: z.ZodOptional<z.ZodOptional<z.ZodNullable<z.ZodString>>>;
    customGitBranch: z.ZodOptional<z.ZodOptional<z.ZodNullable<z.ZodString>>>;
    customGitSSHKeyId: z.ZodOptional<z.ZodOptional<z.ZodNullable<z.ZodOptional<z.ZodString>>>>;
    command: z.ZodOptional<z.ZodString>;
    enableSubmodules: z.ZodOptional<z.ZodOptional<z.ZodBoolean>>;
    composePath: z.ZodOptional<z.ZodOptional<z.ZodString>>;
    suffix: z.ZodOptional<z.ZodOptional<z.ZodString>>;
    randomize: z.ZodOptional<z.ZodOptional<z.ZodBoolean>>;
    isolatedDeployment: z.ZodOptional<z.ZodOptional<z.ZodBoolean>>;
    isolatedDeploymentsVolume: z.ZodOptional<z.ZodOptional<z.ZodBoolean>>;
    composeStatus: z.ZodOptional<z.ZodOptional<z.ZodOptional<z.ZodEnum<{
        idle: "idle";
        running: "running";
        done: "done";
        error: "error";
    }>>>>;
    environmentId: z.ZodOptional<z.ZodString>;
    watchPaths: z.ZodOptional<z.ZodOptional<z.ZodNullable<z.ZodOptional<z.ZodArray<z.ZodString>>>>>;
    bitbucketId: z.ZodOptional<z.ZodOptional<z.ZodNullable<z.ZodString>>>;
}, z.core.$strip>;
export declare const apiSaveEnvironmentVariablesCompose: z.ZodObject<{
    composeId: z.ZodNonOptional<z.ZodOptional<z.ZodString>>;
    env: z.ZodNonOptional<z.ZodOptional<z.ZodNullable<z.ZodOptional<z.ZodString>>>>;
}, z.core.$strip>;
export declare const apiRandomizeCompose: z.ZodObject<{
    suffix: z.ZodOptional<z.ZodString>;
    composeId: z.ZodString;
}, z.core.$strip>;
//# sourceMappingURL=compose.d.ts.map