import { z } from "zod";
export declare const domainType: import("drizzle-orm/pg-core").PgEnum<["compose", "application", "preview"]>;
export declare const domains: import("drizzle-orm/pg-core").PgTableWithColumns<{
    name: "domain";
    schema: undefined;
    columns: {
        domainId: import("drizzle-orm/pg-core").PgColumn<{
            name: "domainId";
            tableName: "domain";
            dataType: "string";
            columnType: "PgText";
            data: string;
            driverParam: string;
            notNull: true;
            hasDefault: true;
            isPrimaryKey: true;
            isAutoincrement: false;
            hasRuntimeDefault: true;
            enumValues: [string, ...string[]];
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        host: import("drizzle-orm/pg-core").PgColumn<{
            name: "host";
            tableName: "domain";
            dataType: "string";
            columnType: "PgText";
            data: string;
            driverParam: string;
            notNull: true;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        https: import("drizzle-orm/pg-core").PgColumn<{
            name: "https";
            tableName: "domain";
            dataType: "boolean";
            columnType: "PgBoolean";
            data: boolean;
            driverParam: boolean;
            notNull: true;
            hasDefault: true;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: undefined;
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        port: import("drizzle-orm/pg-core").PgColumn<{
            name: "port";
            tableName: "domain";
            dataType: "number";
            columnType: "PgInteger";
            data: number;
            driverParam: string | number;
            notNull: false;
            hasDefault: true;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: undefined;
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        customEntrypoint: import("drizzle-orm/pg-core").PgColumn<{
            name: "customEntrypoint";
            tableName: "domain";
            dataType: "string";
            columnType: "PgText";
            data: string;
            driverParam: string;
            notNull: false;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        path: import("drizzle-orm/pg-core").PgColumn<{
            name: "path";
            tableName: "domain";
            dataType: "string";
            columnType: "PgText";
            data: string;
            driverParam: string;
            notNull: false;
            hasDefault: true;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        serviceName: import("drizzle-orm/pg-core").PgColumn<{
            name: "serviceName";
            tableName: "domain";
            dataType: "string";
            columnType: "PgText";
            data: string;
            driverParam: string;
            notNull: false;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        domainType: import("drizzle-orm/pg-core").PgColumn<{
            name: "domainType";
            tableName: "domain";
            dataType: "string";
            columnType: "PgEnumColumn";
            data: "application" | "compose" | "preview";
            driverParam: string;
            notNull: false;
            hasDefault: true;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: ["compose", "application", "preview"];
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        uniqueConfigKey: import("drizzle-orm/pg-core").PgColumn<{
            name: "uniqueConfigKey";
            tableName: "domain";
            dataType: "number";
            columnType: "PgSerial";
            data: number;
            driverParam: number;
            notNull: true;
            hasDefault: true;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: undefined;
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        createdAt: import("drizzle-orm/pg-core").PgColumn<{
            name: "createdAt";
            tableName: "domain";
            dataType: "string";
            columnType: "PgText";
            data: string;
            driverParam: string;
            notNull: true;
            hasDefault: true;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: true;
            enumValues: [string, ...string[]];
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        composeId: import("drizzle-orm/pg-core").PgColumn<{
            name: "composeId";
            tableName: "domain";
            dataType: "string";
            columnType: "PgText";
            data: string;
            driverParam: string;
            notNull: false;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        customCertResolver: import("drizzle-orm/pg-core").PgColumn<{
            name: "customCertResolver";
            tableName: "domain";
            dataType: "string";
            columnType: "PgText";
            data: string;
            driverParam: string;
            notNull: false;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        applicationId: import("drizzle-orm/pg-core").PgColumn<{
            name: "applicationId";
            tableName: "domain";
            dataType: "string";
            columnType: "PgText";
            data: string;
            driverParam: string;
            notNull: false;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        previewDeploymentId: import("drizzle-orm/pg-core").PgColumn<{
            name: "previewDeploymentId";
            tableName: "domain";
            dataType: "string";
            columnType: "PgText";
            data: string;
            driverParam: string;
            notNull: false;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        certificateType: import("drizzle-orm/pg-core").PgColumn<{
            name: "certificateType";
            tableName: "domain";
            dataType: "string";
            columnType: "PgEnumColumn";
            data: "letsencrypt" | "none" | "custom";
            driverParam: string;
            notNull: true;
            hasDefault: true;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: ["letsencrypt", "none", "custom"];
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        internalPath: import("drizzle-orm/pg-core").PgColumn<{
            name: "internalPath";
            tableName: "domain";
            dataType: "string";
            columnType: "PgText";
            data: string;
            driverParam: string;
            notNull: false;
            hasDefault: true;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        stripPath: import("drizzle-orm/pg-core").PgColumn<{
            name: "stripPath";
            tableName: "domain";
            dataType: "boolean";
            columnType: "PgBoolean";
            data: boolean;
            driverParam: boolean;
            notNull: true;
            hasDefault: true;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: undefined;
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        middlewares: import("drizzle-orm/pg-core").PgColumn<{
            name: "middlewares";
            tableName: "domain";
            dataType: "array";
            columnType: "PgArray";
            data: string[];
            driverParam: string | string[];
            notNull: false;
            hasDefault: true;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: import("drizzle-orm").Column<{
                name: "middlewares";
                tableName: "domain";
                dataType: "string";
                columnType: "PgText";
                data: string;
                driverParam: string;
                notNull: false;
                hasDefault: false;
                isPrimaryKey: false;
                isAutoincrement: false;
                hasRuntimeDefault: false;
                enumValues: [string, ...string[]];
                baseColumn: never;
                identity: undefined;
                generated: undefined;
            }, {}, {}>;
            identity: undefined;
            generated: undefined;
        }, {}, {
            baseBuilder: import("drizzle-orm/pg-core").PgColumnBuilder<{
                name: "middlewares";
                dataType: "string";
                columnType: "PgText";
                data: string;
                enumValues: [string, ...string[]];
                driverParam: string;
            }, {}, {}, import("drizzle-orm").ColumnBuilderExtraConfig>;
            size: undefined;
        }>;
    };
    dialect: "pg";
}>;
export declare const domainsRelations: import("drizzle-orm").Relations<"domain", {
    application: import("drizzle-orm").One<"application", false>;
    compose: import("drizzle-orm").One<"compose", false>;
    previewDeployment: import("drizzle-orm").One<"preview_deployments", false>;
}>;
export declare const apiCreateDomain: z.ZodObject<{
    certificateType: z.ZodOptional<z.ZodOptional<z.ZodEnum<{
        letsencrypt: "letsencrypt";
        none: "none";
        custom: "custom";
    }>>>;
    applicationId: z.ZodOptional<z.ZodNullable<z.ZodString>>;
    host: z.ZodPipe<z.ZodString, z.ZodTransform<string, string>>;
    port: z.ZodOptional<z.ZodNullable<z.ZodOptional<z.ZodNumber>>>;
    path: z.ZodOptional<z.ZodNullable<z.ZodOptional<z.ZodString>>>;
    internalPath: z.ZodOptional<z.ZodNullable<z.ZodOptional<z.ZodString>>>;
    stripPath: z.ZodOptional<z.ZodOptional<z.ZodBoolean>>;
    https: z.ZodOptional<z.ZodOptional<z.ZodBoolean>>;
    customCertResolver: z.ZodOptional<z.ZodNullable<z.ZodString>>;
    middlewares: z.ZodOptional<z.ZodNullable<z.ZodOptional<z.ZodArray<z.ZodString>>>>;
    serviceName: z.ZodOptional<z.ZodNullable<z.ZodString>>;
    domainType: z.ZodOptional<z.ZodNullable<z.ZodOptional<z.ZodEnum<{
        application: "application";
        compose: "compose";
        preview: "preview";
    }>>>>;
    customEntrypoint: z.ZodOptional<z.ZodNullable<z.ZodString>>;
    composeId: z.ZodOptional<z.ZodNullable<z.ZodString>>;
    previewDeploymentId: z.ZodOptional<z.ZodNullable<z.ZodString>>;
}, z.core.$strip>;
export declare const apiFindDomain: z.ZodObject<{
    domainId: z.ZodString;
}, z.core.$strip>;
export declare const apiFindDomainByApplication: z.ZodObject<{
    applicationId: z.ZodOptional<z.ZodNullable<z.ZodString>>;
}, z.core.$strip>;
export declare const apiCreateTraefikMeDomain: z.ZodObject<{
    appName: z.ZodString;
}, z.core.$strip>;
export declare const apiFindDomainByCompose: z.ZodObject<{
    composeId: z.ZodOptional<z.ZodNullable<z.ZodString>>;
}, z.core.$strip>;
export declare const apiUpdateDomain: z.ZodObject<{
    certificateType: z.ZodOptional<z.ZodOptional<z.ZodEnum<{
        letsencrypt: "letsencrypt";
        none: "none";
        custom: "custom";
    }>>>;
    host: z.ZodPipe<z.ZodString, z.ZodTransform<string, string>>;
    port: z.ZodOptional<z.ZodNullable<z.ZodOptional<z.ZodNumber>>>;
    path: z.ZodOptional<z.ZodNullable<z.ZodOptional<z.ZodString>>>;
    internalPath: z.ZodOptional<z.ZodNullable<z.ZodOptional<z.ZodString>>>;
    stripPath: z.ZodOptional<z.ZodOptional<z.ZodBoolean>>;
    https: z.ZodOptional<z.ZodOptional<z.ZodBoolean>>;
    customCertResolver: z.ZodOptional<z.ZodNullable<z.ZodString>>;
    middlewares: z.ZodOptional<z.ZodNullable<z.ZodOptional<z.ZodArray<z.ZodString>>>>;
    serviceName: z.ZodOptional<z.ZodNullable<z.ZodString>>;
    domainType: z.ZodOptional<z.ZodNullable<z.ZodOptional<z.ZodEnum<{
        application: "application";
        compose: "compose";
        preview: "preview";
    }>>>>;
    customEntrypoint: z.ZodOptional<z.ZodNullable<z.ZodString>>;
    domainId: z.ZodNonOptional<z.ZodOptional<z.ZodString>>;
}, z.core.$strip>;
//# sourceMappingURL=domain.d.ts.map