import { z } from "zod";
export declare const gitlab: import("drizzle-orm/pg-core").PgTableWithColumns<{
    name: "gitlab";
    schema: undefined;
    columns: {
        gitlabId: import("drizzle-orm/pg-core").PgColumn<{
            name: "gitlabId";
            tableName: "gitlab";
            dataType: "string";
            columnType: "PgText";
            data: string;
            driverParam: string;
            notNull: true;
            hasDefault: true;
            isPrimaryKey: true;
            isAutoincrement: false;
            hasRuntimeDefault: true;
            enumValues: [string, ...string[]];
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        gitlabUrl: import("drizzle-orm/pg-core").PgColumn<{
            name: "gitlabUrl";
            tableName: "gitlab";
            dataType: "string";
            columnType: "PgText";
            data: string;
            driverParam: string;
            notNull: true;
            hasDefault: true;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        gitlabInternalUrl: import("drizzle-orm/pg-core").PgColumn<{
            name: "gitlabInternalUrl";
            tableName: "gitlab";
            dataType: "string";
            columnType: "PgText";
            data: string;
            driverParam: string;
            notNull: false;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        applicationId: import("drizzle-orm/pg-core").PgColumn<{
            name: "application_id";
            tableName: "gitlab";
            dataType: "string";
            columnType: "PgText";
            data: string;
            driverParam: string;
            notNull: false;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        redirectUri: import("drizzle-orm/pg-core").PgColumn<{
            name: "redirect_uri";
            tableName: "gitlab";
            dataType: "string";
            columnType: "PgText";
            data: string;
            driverParam: string;
            notNull: false;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        secret: import("drizzle-orm/pg-core").PgColumn<{
            name: "secret";
            tableName: "gitlab";
            dataType: "string";
            columnType: "PgText";
            data: string;
            driverParam: string;
            notNull: false;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        accessToken: import("drizzle-orm/pg-core").PgColumn<{
            name: "access_token";
            tableName: "gitlab";
            dataType: "string";
            columnType: "PgText";
            data: string;
            driverParam: string;
            notNull: false;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        refreshToken: import("drizzle-orm/pg-core").PgColumn<{
            name: "refresh_token";
            tableName: "gitlab";
            dataType: "string";
            columnType: "PgText";
            data: string;
            driverParam: string;
            notNull: false;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        groupName: import("drizzle-orm/pg-core").PgColumn<{
            name: "group_name";
            tableName: "gitlab";
            dataType: "string";
            columnType: "PgText";
            data: string;
            driverParam: string;
            notNull: false;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        expiresAt: import("drizzle-orm/pg-core").PgColumn<{
            name: "expires_at";
            tableName: "gitlab";
            dataType: "number";
            columnType: "PgInteger";
            data: number;
            driverParam: string | number;
            notNull: false;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: undefined;
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        gitProviderId: import("drizzle-orm/pg-core").PgColumn<{
            name: "gitProviderId";
            tableName: "gitlab";
            dataType: "string";
            columnType: "PgText";
            data: string;
            driverParam: string;
            notNull: true;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
    };
    dialect: "pg";
}>;
export declare const gitlabProviderRelations: import("drizzle-orm").Relations<"gitlab", {
    gitProvider: import("drizzle-orm").One<"git_provider", true>;
}>;
export declare const apiCreateGitlab: z.ZodObject<{
    applicationId: z.ZodOptional<z.ZodString>;
    secret: z.ZodOptional<z.ZodString>;
    groupName: z.ZodOptional<z.ZodString>;
    gitProviderId: z.ZodOptional<z.ZodString>;
    redirectUri: z.ZodOptional<z.ZodString>;
    authId: z.ZodString;
    name: z.ZodString;
    gitlabUrl: z.ZodString;
    gitlabInternalUrl: z.ZodNullable<z.ZodOptional<z.ZodString>>;
}, z.core.$strip>;
export declare const apiFindOneGitlab: z.ZodObject<{
    gitlabId: z.ZodString;
}, z.core.$strip>;
export declare const apiGitlabTestConnection: z.ZodObject<{
    gitlabId: z.ZodString;
    groupName: z.ZodOptional<z.ZodString>;
}, z.core.$strip>;
export declare const apiFindGitlabBranches: z.ZodObject<{
    id: z.ZodOptional<z.ZodNumber>;
    owner: z.ZodString;
    repo: z.ZodString;
    gitlabId: z.ZodOptional<z.ZodString>;
}, z.core.$strip>;
export declare const apiUpdateGitlab: z.ZodObject<{
    applicationId: z.ZodOptional<z.ZodString>;
    secret: z.ZodOptional<z.ZodString>;
    groupName: z.ZodOptional<z.ZodString>;
    redirectUri: z.ZodOptional<z.ZodString>;
    name: z.ZodString;
    gitlabId: z.ZodString;
    gitlabUrl: z.ZodString;
    gitProviderId: z.ZodString;
    gitlabInternalUrl: z.ZodNullable<z.ZodOptional<z.ZodString>>;
}, z.core.$strip>;
//# sourceMappingURL=gitlab.d.ts.map