import { z } from "zod";
export declare const serviceType: import("drizzle-orm/pg-core").PgEnum<["application", "postgres", "mysql", "mariadb", "mongo", "redis", "compose", "libsql"]>;
export type ServiceType = (typeof serviceType.enumValues)[number];
export declare const mountType: import("drizzle-orm/pg-core").PgEnum<["bind", "volume", "file"]>;
export declare const mounts: import("drizzle-orm/pg-core").PgTableWithColumns<{
    name: "mount";
    schema: undefined;
    columns: {
        mountId: import("drizzle-orm/pg-core").PgColumn<{
            name: "mountId";
            tableName: "mount";
            dataType: "string";
            columnType: "PgText";
            data: string;
            driverParam: string;
            notNull: true;
            hasDefault: true;
            isPrimaryKey: true;
            isAutoincrement: false;
            hasRuntimeDefault: true;
            enumValues: [string, ...string[]];
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        type: import("drizzle-orm/pg-core").PgColumn<{
            name: "type";
            tableName: "mount";
            dataType: "string";
            columnType: "PgEnumColumn";
            data: "file" | "bind" | "volume";
            driverParam: string;
            notNull: true;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: ["bind", "volume", "file"];
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        hostPath: import("drizzle-orm/pg-core").PgColumn<{
            name: "hostPath";
            tableName: "mount";
            dataType: "string";
            columnType: "PgText";
            data: string;
            driverParam: string;
            notNull: false;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        volumeName: import("drizzle-orm/pg-core").PgColumn<{
            name: "volumeName";
            tableName: "mount";
            dataType: "string";
            columnType: "PgText";
            data: string;
            driverParam: string;
            notNull: false;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        filePath: import("drizzle-orm/pg-core").PgColumn<{
            name: "filePath";
            tableName: "mount";
            dataType: "string";
            columnType: "PgText";
            data: string;
            driverParam: string;
            notNull: false;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        content: import("drizzle-orm/pg-core").PgColumn<{
            name: "content";
            tableName: "mount";
            dataType: "string";
            columnType: "PgText";
            data: string;
            driverParam: string;
            notNull: false;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        serviceType: import("drizzle-orm/pg-core").PgColumn<{
            name: "serviceType";
            tableName: "mount";
            dataType: "string";
            columnType: "PgEnumColumn";
            data: "application" | "compose" | "mysql" | "libsql" | "mariadb" | "mongo" | "postgres" | "redis";
            driverParam: string;
            notNull: true;
            hasDefault: true;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: ["application", "postgres", "mysql", "mariadb", "mongo", "redis", "compose", "libsql"];
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        mountPath: import("drizzle-orm/pg-core").PgColumn<{
            name: "mountPath";
            tableName: "mount";
            dataType: "string";
            columnType: "PgText";
            data: string;
            driverParam: string;
            notNull: true;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        applicationId: import("drizzle-orm/pg-core").PgColumn<{
            name: "applicationId";
            tableName: "mount";
            dataType: "string";
            columnType: "PgText";
            data: string;
            driverParam: string;
            notNull: false;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        composeId: import("drizzle-orm/pg-core").PgColumn<{
            name: "composeId";
            tableName: "mount";
            dataType: "string";
            columnType: "PgText";
            data: string;
            driverParam: string;
            notNull: false;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        libsqlId: import("drizzle-orm/pg-core").PgColumn<{
            name: "libsqlId";
            tableName: "mount";
            dataType: "string";
            columnType: "PgText";
            data: string;
            driverParam: string;
            notNull: false;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        mariadbId: import("drizzle-orm/pg-core").PgColumn<{
            name: "mariadbId";
            tableName: "mount";
            dataType: "string";
            columnType: "PgText";
            data: string;
            driverParam: string;
            notNull: false;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        mongoId: import("drizzle-orm/pg-core").PgColumn<{
            name: "mongoId";
            tableName: "mount";
            dataType: "string";
            columnType: "PgText";
            data: string;
            driverParam: string;
            notNull: false;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        mysqlId: import("drizzle-orm/pg-core").PgColumn<{
            name: "mysqlId";
            tableName: "mount";
            dataType: "string";
            columnType: "PgText";
            data: string;
            driverParam: string;
            notNull: false;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        postgresId: import("drizzle-orm/pg-core").PgColumn<{
            name: "postgresId";
            tableName: "mount";
            dataType: "string";
            columnType: "PgText";
            data: string;
            driverParam: string;
            notNull: false;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        redisId: import("drizzle-orm/pg-core").PgColumn<{
            name: "redisId";
            tableName: "mount";
            dataType: "string";
            columnType: "PgText";
            data: string;
            driverParam: string;
            notNull: false;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
    };
    dialect: "pg";
}>;
export declare const MountssRelations: import("drizzle-orm").Relations<"mount", {
    application: import("drizzle-orm").One<"application", false>;
    compose: import("drizzle-orm").One<"compose", false>;
    libsql: import("drizzle-orm").One<"libsql", false>;
    mariadb: import("drizzle-orm").One<"mariadb", false>;
    mongo: import("drizzle-orm").One<"mongo", false>;
    mysql: import("drizzle-orm").One<"mysql", false>;
    postgres: import("drizzle-orm").One<"postgres", false>;
    redis: import("drizzle-orm").One<"redis", false>;
}>;
export declare const apiCreateMount: z.ZodObject<{
    type: z.ZodEnum<{
        file: "file";
        bind: "bind";
        volume: "volume";
    }>;
    serviceType: z.ZodOptional<z.ZodEnum<{
        application: "application";
        compose: "compose";
        mysql: "mysql";
        libsql: "libsql";
        mariadb: "mariadb";
        mongo: "mongo";
        postgres: "postgres";
        redis: "redis";
    }>>;
    filePath: z.ZodOptional<z.ZodNullable<z.ZodOptional<z.ZodString>>>;
    content: z.ZodOptional<z.ZodNullable<z.ZodOptional<z.ZodString>>>;
    hostPath: z.ZodOptional<z.ZodNullable<z.ZodOptional<z.ZodString>>>;
    volumeName: z.ZodOptional<z.ZodNullable<z.ZodOptional<z.ZodString>>>;
    mountPath: z.ZodString;
    serviceId: z.ZodString;
}, z.core.$strip>;
export declare const apiFindOneMount: z.ZodObject<{
    mountId: z.ZodString;
}, z.core.$strip>;
export declare const apiRemoveMount: z.ZodObject<{
    mountId: z.ZodNonOptional<z.ZodOptional<z.ZodOptional<z.ZodString>>>;
}, z.core.$strip>;
export declare const apiFindMountByApplicationId: z.ZodObject<{
    serviceType: z.ZodPipe<z.ZodString, z.ZodTransform<"application" | "compose" | "mysql" | "libsql" | "mariadb" | "mongo" | "postgres" | "redis", string>>;
    serviceId: z.ZodString;
}, z.core.$strip>;
export declare const apiUpdateMount: z.ZodObject<{
    type: z.ZodOptional<z.ZodEnum<{
        file: "file";
        bind: "bind";
        volume: "volume";
    }>>;
    applicationId: z.ZodOptional<z.ZodOptional<z.ZodNullable<z.ZodString>>>;
    composeId: z.ZodOptional<z.ZodOptional<z.ZodNullable<z.ZodString>>>;
    serviceType: z.ZodOptional<z.ZodOptional<z.ZodEnum<{
        application: "application";
        compose: "compose";
        mysql: "mysql";
        libsql: "libsql";
        mariadb: "mariadb";
        mongo: "mongo";
        postgres: "postgres";
        redis: "redis";
    }>>>;
    mysqlId: z.ZodOptional<z.ZodOptional<z.ZodNullable<z.ZodString>>>;
    filePath: z.ZodOptional<z.ZodOptional<z.ZodNullable<z.ZodOptional<z.ZodString>>>>;
    content: z.ZodOptional<z.ZodOptional<z.ZodNullable<z.ZodOptional<z.ZodString>>>>;
    hostPath: z.ZodOptional<z.ZodOptional<z.ZodNullable<z.ZodOptional<z.ZodString>>>>;
    volumeName: z.ZodOptional<z.ZodOptional<z.ZodNullable<z.ZodOptional<z.ZodString>>>>;
    mountPath: z.ZodOptional<z.ZodString>;
    libsqlId: z.ZodOptional<z.ZodOptional<z.ZodNullable<z.ZodString>>>;
    mariadbId: z.ZodOptional<z.ZodOptional<z.ZodNullable<z.ZodString>>>;
    mongoId: z.ZodOptional<z.ZodOptional<z.ZodNullable<z.ZodString>>>;
    postgresId: z.ZodOptional<z.ZodOptional<z.ZodNullable<z.ZodString>>>;
    redisId: z.ZodOptional<z.ZodOptional<z.ZodNullable<z.ZodString>>>;
    mountId: z.ZodString;
}, z.core.$strip>;
//# sourceMappingURL=mount.d.ts.map