import { z } from "zod";
export declare const notificationType: import("drizzle-orm/pg-core").PgEnum<["slack", "telegram", "discord", "email", "resend", "gotify", "ntfy", "mattermost", "pushover", "custom", "lark", "teams"]>;
export declare const notifications: import("drizzle-orm/pg-core").PgTableWithColumns<{
    name: "notification";
    schema: undefined;
    columns: {
        notificationId: import("drizzle-orm/pg-core").PgColumn<{
            name: "notificationId";
            tableName: "notification";
            dataType: "string";
            columnType: "PgText";
            data: string;
            driverParam: string;
            notNull: true;
            hasDefault: true;
            isPrimaryKey: true;
            isAutoincrement: false;
            hasRuntimeDefault: true;
            enumValues: [string, ...string[]];
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        name: import("drizzle-orm/pg-core").PgColumn<{
            name: "name";
            tableName: "notification";
            dataType: "string";
            columnType: "PgText";
            data: string;
            driverParam: string;
            notNull: true;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        appDeploy: import("drizzle-orm/pg-core").PgColumn<{
            name: "appDeploy";
            tableName: "notification";
            dataType: "boolean";
            columnType: "PgBoolean";
            data: boolean;
            driverParam: boolean;
            notNull: true;
            hasDefault: true;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: undefined;
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        appBuildError: import("drizzle-orm/pg-core").PgColumn<{
            name: "appBuildError";
            tableName: "notification";
            dataType: "boolean";
            columnType: "PgBoolean";
            data: boolean;
            driverParam: boolean;
            notNull: true;
            hasDefault: true;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: undefined;
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        databaseBackup: import("drizzle-orm/pg-core").PgColumn<{
            name: "databaseBackup";
            tableName: "notification";
            dataType: "boolean";
            columnType: "PgBoolean";
            data: boolean;
            driverParam: boolean;
            notNull: true;
            hasDefault: true;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: undefined;
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        volumeBackup: import("drizzle-orm/pg-core").PgColumn<{
            name: "volumeBackup";
            tableName: "notification";
            dataType: "boolean";
            columnType: "PgBoolean";
            data: boolean;
            driverParam: boolean;
            notNull: true;
            hasDefault: true;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: undefined;
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        dokployRestart: import("drizzle-orm/pg-core").PgColumn<{
            name: "dokployRestart";
            tableName: "notification";
            dataType: "boolean";
            columnType: "PgBoolean";
            data: boolean;
            driverParam: boolean;
            notNull: true;
            hasDefault: true;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: undefined;
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        dokployBackup: import("drizzle-orm/pg-core").PgColumn<{
            name: "dokployBackup";
            tableName: "notification";
            dataType: "boolean";
            columnType: "PgBoolean";
            data: boolean;
            driverParam: boolean;
            notNull: true;
            hasDefault: true;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: undefined;
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        dockerCleanup: import("drizzle-orm/pg-core").PgColumn<{
            name: "dockerCleanup";
            tableName: "notification";
            dataType: "boolean";
            columnType: "PgBoolean";
            data: boolean;
            driverParam: boolean;
            notNull: true;
            hasDefault: true;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: undefined;
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        serverThreshold: import("drizzle-orm/pg-core").PgColumn<{
            name: "serverThreshold";
            tableName: "notification";
            dataType: "boolean";
            columnType: "PgBoolean";
            data: boolean;
            driverParam: boolean;
            notNull: true;
            hasDefault: true;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: undefined;
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        notificationType: import("drizzle-orm/pg-core").PgColumn<{
            name: "notificationType";
            tableName: "notification";
            dataType: "string";
            columnType: "PgEnumColumn";
            data: "custom" | "email" | "slack" | "telegram" | "discord" | "resend" | "gotify" | "ntfy" | "mattermost" | "lark" | "pushover" | "teams";
            driverParam: string;
            notNull: true;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: ["slack", "telegram", "discord", "email", "resend", "gotify", "ntfy", "mattermost", "pushover", "custom", "lark", "teams"];
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        createdAt: import("drizzle-orm/pg-core").PgColumn<{
            name: "createdAt";
            tableName: "notification";
            dataType: "string";
            columnType: "PgText";
            data: string;
            driverParam: string;
            notNull: true;
            hasDefault: true;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: true;
            enumValues: [string, ...string[]];
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        slackId: import("drizzle-orm/pg-core").PgColumn<{
            name: "slackId";
            tableName: "notification";
            dataType: "string";
            columnType: "PgText";
            data: string;
            driverParam: string;
            notNull: false;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        telegramId: import("drizzle-orm/pg-core").PgColumn<{
            name: "telegramId";
            tableName: "notification";
            dataType: "string";
            columnType: "PgText";
            data: string;
            driverParam: string;
            notNull: false;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        discordId: import("drizzle-orm/pg-core").PgColumn<{
            name: "discordId";
            tableName: "notification";
            dataType: "string";
            columnType: "PgText";
            data: string;
            driverParam: string;
            notNull: false;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        emailId: import("drizzle-orm/pg-core").PgColumn<{
            name: "emailId";
            tableName: "notification";
            dataType: "string";
            columnType: "PgText";
            data: string;
            driverParam: string;
            notNull: false;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        resendId: import("drizzle-orm/pg-core").PgColumn<{
            name: "resendId";
            tableName: "notification";
            dataType: "string";
            columnType: "PgText";
            data: string;
            driverParam: string;
            notNull: false;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        gotifyId: import("drizzle-orm/pg-core").PgColumn<{
            name: "gotifyId";
            tableName: "notification";
            dataType: "string";
            columnType: "PgText";
            data: string;
            driverParam: string;
            notNull: false;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        ntfyId: import("drizzle-orm/pg-core").PgColumn<{
            name: "ntfyId";
            tableName: "notification";
            dataType: "string";
            columnType: "PgText";
            data: string;
            driverParam: string;
            notNull: false;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        mattermostId: import("drizzle-orm/pg-core").PgColumn<{
            name: "mattermostId";
            tableName: "notification";
            dataType: "string";
            columnType: "PgText";
            data: string;
            driverParam: string;
            notNull: false;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        customId: import("drizzle-orm/pg-core").PgColumn<{
            name: "customId";
            tableName: "notification";
            dataType: "string";
            columnType: "PgText";
            data: string;
            driverParam: string;
            notNull: false;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        larkId: import("drizzle-orm/pg-core").PgColumn<{
            name: "larkId";
            tableName: "notification";
            dataType: "string";
            columnType: "PgText";
            data: string;
            driverParam: string;
            notNull: false;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        pushoverId: import("drizzle-orm/pg-core").PgColumn<{
            name: "pushoverId";
            tableName: "notification";
            dataType: "string";
            columnType: "PgText";
            data: string;
            driverParam: string;
            notNull: false;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        teamsId: import("drizzle-orm/pg-core").PgColumn<{
            name: "teamsId";
            tableName: "notification";
            dataType: "string";
            columnType: "PgText";
            data: string;
            driverParam: string;
            notNull: false;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        organizationId: import("drizzle-orm/pg-core").PgColumn<{
            name: "organizationId";
            tableName: "notification";
            dataType: "string";
            columnType: "PgText";
            data: string;
            driverParam: string;
            notNull: true;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
    };
    dialect: "pg";
}>;
export declare const slack: import("drizzle-orm/pg-core").PgTableWithColumns<{
    name: "slack";
    schema: undefined;
    columns: {
        slackId: import("drizzle-orm/pg-core").PgColumn<{
            name: "slackId";
            tableName: "slack";
            dataType: "string";
            columnType: "PgText";
            data: string;
            driverParam: string;
            notNull: true;
            hasDefault: true;
            isPrimaryKey: true;
            isAutoincrement: false;
            hasRuntimeDefault: true;
            enumValues: [string, ...string[]];
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        webhookUrl: import("drizzle-orm/pg-core").PgColumn<{
            name: "webhookUrl";
            tableName: "slack";
            dataType: "string";
            columnType: "PgText";
            data: string;
            driverParam: string;
            notNull: true;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        channel: import("drizzle-orm/pg-core").PgColumn<{
            name: "channel";
            tableName: "slack";
            dataType: "string";
            columnType: "PgText";
            data: string;
            driverParam: string;
            notNull: false;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
    };
    dialect: "pg";
}>;
export declare const telegram: import("drizzle-orm/pg-core").PgTableWithColumns<{
    name: "telegram";
    schema: undefined;
    columns: {
        telegramId: import("drizzle-orm/pg-core").PgColumn<{
            name: "telegramId";
            tableName: "telegram";
            dataType: "string";
            columnType: "PgText";
            data: string;
            driverParam: string;
            notNull: true;
            hasDefault: true;
            isPrimaryKey: true;
            isAutoincrement: false;
            hasRuntimeDefault: true;
            enumValues: [string, ...string[]];
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        botToken: import("drizzle-orm/pg-core").PgColumn<{
            name: "botToken";
            tableName: "telegram";
            dataType: "string";
            columnType: "PgText";
            data: string;
            driverParam: string;
            notNull: true;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        chatId: import("drizzle-orm/pg-core").PgColumn<{
            name: "chatId";
            tableName: "telegram";
            dataType: "string";
            columnType: "PgText";
            data: string;
            driverParam: string;
            notNull: true;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        messageThreadId: import("drizzle-orm/pg-core").PgColumn<{
            name: "messageThreadId";
            tableName: "telegram";
            dataType: "string";
            columnType: "PgText";
            data: string;
            driverParam: string;
            notNull: false;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
    };
    dialect: "pg";
}>;
export declare const discord: import("drizzle-orm/pg-core").PgTableWithColumns<{
    name: "discord";
    schema: undefined;
    columns: {
        discordId: import("drizzle-orm/pg-core").PgColumn<{
            name: "discordId";
            tableName: "discord";
            dataType: "string";
            columnType: "PgText";
            data: string;
            driverParam: string;
            notNull: true;
            hasDefault: true;
            isPrimaryKey: true;
            isAutoincrement: false;
            hasRuntimeDefault: true;
            enumValues: [string, ...string[]];
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        webhookUrl: import("drizzle-orm/pg-core").PgColumn<{
            name: "webhookUrl";
            tableName: "discord";
            dataType: "string";
            columnType: "PgText";
            data: string;
            driverParam: string;
            notNull: true;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        decoration: import("drizzle-orm/pg-core").PgColumn<{
            name: "decoration";
            tableName: "discord";
            dataType: "boolean";
            columnType: "PgBoolean";
            data: boolean;
            driverParam: boolean;
            notNull: false;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: undefined;
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
    };
    dialect: "pg";
}>;
export declare const email: import("drizzle-orm/pg-core").PgTableWithColumns<{
    name: "email";
    schema: undefined;
    columns: {
        emailId: import("drizzle-orm/pg-core").PgColumn<{
            name: "emailId";
            tableName: "email";
            dataType: "string";
            columnType: "PgText";
            data: string;
            driverParam: string;
            notNull: true;
            hasDefault: true;
            isPrimaryKey: true;
            isAutoincrement: false;
            hasRuntimeDefault: true;
            enumValues: [string, ...string[]];
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        smtpServer: import("drizzle-orm/pg-core").PgColumn<{
            name: "smtpServer";
            tableName: "email";
            dataType: "string";
            columnType: "PgText";
            data: string;
            driverParam: string;
            notNull: true;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        smtpPort: import("drizzle-orm/pg-core").PgColumn<{
            name: "smtpPort";
            tableName: "email";
            dataType: "number";
            columnType: "PgInteger";
            data: number;
            driverParam: string | number;
            notNull: true;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: undefined;
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        username: import("drizzle-orm/pg-core").PgColumn<{
            name: "username";
            tableName: "email";
            dataType: "string";
            columnType: "PgText";
            data: string;
            driverParam: string;
            notNull: true;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        password: import("drizzle-orm/pg-core").PgColumn<{
            name: "password";
            tableName: "email";
            dataType: "string";
            columnType: "PgText";
            data: string;
            driverParam: string;
            notNull: true;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        fromAddress: import("drizzle-orm/pg-core").PgColumn<{
            name: "fromAddress";
            tableName: "email";
            dataType: "string";
            columnType: "PgText";
            data: string;
            driverParam: string;
            notNull: true;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        toAddresses: import("drizzle-orm/pg-core").PgColumn<{
            name: "toAddress";
            tableName: "email";
            dataType: "array";
            columnType: "PgArray";
            data: string[];
            driverParam: string | string[];
            notNull: true;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: import("drizzle-orm").Column<{
                name: "toAddress";
                tableName: "email";
                dataType: "string";
                columnType: "PgText";
                data: string;
                driverParam: string;
                notNull: false;
                hasDefault: false;
                isPrimaryKey: false;
                isAutoincrement: false;
                hasRuntimeDefault: false;
                enumValues: [string, ...string[]];
                baseColumn: never;
                identity: undefined;
                generated: undefined;
            }, {}, {}>;
            identity: undefined;
            generated: undefined;
        }, {}, {
            baseBuilder: import("drizzle-orm/pg-core").PgColumnBuilder<{
                name: "toAddress";
                dataType: "string";
                columnType: "PgText";
                data: string;
                enumValues: [string, ...string[]];
                driverParam: string;
            }, {}, {}, import("drizzle-orm").ColumnBuilderExtraConfig>;
            size: undefined;
        }>;
    };
    dialect: "pg";
}>;
export declare const resend: import("drizzle-orm/pg-core").PgTableWithColumns<{
    name: "resend";
    schema: undefined;
    columns: {
        resendId: import("drizzle-orm/pg-core").PgColumn<{
            name: "resendId";
            tableName: "resend";
            dataType: "string";
            columnType: "PgText";
            data: string;
            driverParam: string;
            notNull: true;
            hasDefault: true;
            isPrimaryKey: true;
            isAutoincrement: false;
            hasRuntimeDefault: true;
            enumValues: [string, ...string[]];
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        apiKey: import("drizzle-orm/pg-core").PgColumn<{
            name: "apiKey";
            tableName: "resend";
            dataType: "string";
            columnType: "PgText";
            data: string;
            driverParam: string;
            notNull: true;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        fromAddress: import("drizzle-orm/pg-core").PgColumn<{
            name: "fromAddress";
            tableName: "resend";
            dataType: "string";
            columnType: "PgText";
            data: string;
            driverParam: string;
            notNull: true;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        toAddresses: import("drizzle-orm/pg-core").PgColumn<{
            name: "toAddress";
            tableName: "resend";
            dataType: "array";
            columnType: "PgArray";
            data: string[];
            driverParam: string | string[];
            notNull: true;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: import("drizzle-orm").Column<{
                name: "toAddress";
                tableName: "resend";
                dataType: "string";
                columnType: "PgText";
                data: string;
                driverParam: string;
                notNull: false;
                hasDefault: false;
                isPrimaryKey: false;
                isAutoincrement: false;
                hasRuntimeDefault: false;
                enumValues: [string, ...string[]];
                baseColumn: never;
                identity: undefined;
                generated: undefined;
            }, {}, {}>;
            identity: undefined;
            generated: undefined;
        }, {}, {
            baseBuilder: import("drizzle-orm/pg-core").PgColumnBuilder<{
                name: "toAddress";
                dataType: "string";
                columnType: "PgText";
                data: string;
                enumValues: [string, ...string[]];
                driverParam: string;
            }, {}, {}, import("drizzle-orm").ColumnBuilderExtraConfig>;
            size: undefined;
        }>;
    };
    dialect: "pg";
}>;
export declare const gotify: import("drizzle-orm/pg-core").PgTableWithColumns<{
    name: "gotify";
    schema: undefined;
    columns: {
        gotifyId: import("drizzle-orm/pg-core").PgColumn<{
            name: "gotifyId";
            tableName: "gotify";
            dataType: "string";
            columnType: "PgText";
            data: string;
            driverParam: string;
            notNull: true;
            hasDefault: true;
            isPrimaryKey: true;
            isAutoincrement: false;
            hasRuntimeDefault: true;
            enumValues: [string, ...string[]];
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        serverUrl: import("drizzle-orm/pg-core").PgColumn<{
            name: "serverUrl";
            tableName: "gotify";
            dataType: "string";
            columnType: "PgText";
            data: string;
            driverParam: string;
            notNull: true;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        appToken: import("drizzle-orm/pg-core").PgColumn<{
            name: "appToken";
            tableName: "gotify";
            dataType: "string";
            columnType: "PgText";
            data: string;
            driverParam: string;
            notNull: true;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        priority: import("drizzle-orm/pg-core").PgColumn<{
            name: "priority";
            tableName: "gotify";
            dataType: "number";
            columnType: "PgInteger";
            data: number;
            driverParam: string | number;
            notNull: true;
            hasDefault: true;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: undefined;
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        decoration: import("drizzle-orm/pg-core").PgColumn<{
            name: "decoration";
            tableName: "gotify";
            dataType: "boolean";
            columnType: "PgBoolean";
            data: boolean;
            driverParam: boolean;
            notNull: false;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: undefined;
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
    };
    dialect: "pg";
}>;
export declare const ntfy: import("drizzle-orm/pg-core").PgTableWithColumns<{
    name: "ntfy";
    schema: undefined;
    columns: {
        ntfyId: import("drizzle-orm/pg-core").PgColumn<{
            name: "ntfyId";
            tableName: "ntfy";
            dataType: "string";
            columnType: "PgText";
            data: string;
            driverParam: string;
            notNull: true;
            hasDefault: true;
            isPrimaryKey: true;
            isAutoincrement: false;
            hasRuntimeDefault: true;
            enumValues: [string, ...string[]];
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        serverUrl: import("drizzle-orm/pg-core").PgColumn<{
            name: "serverUrl";
            tableName: "ntfy";
            dataType: "string";
            columnType: "PgText";
            data: string;
            driverParam: string;
            notNull: true;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        topic: import("drizzle-orm/pg-core").PgColumn<{
            name: "topic";
            tableName: "ntfy";
            dataType: "string";
            columnType: "PgText";
            data: string;
            driverParam: string;
            notNull: true;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        accessToken: import("drizzle-orm/pg-core").PgColumn<{
            name: "accessToken";
            tableName: "ntfy";
            dataType: "string";
            columnType: "PgText";
            data: string;
            driverParam: string;
            notNull: false;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        priority: import("drizzle-orm/pg-core").PgColumn<{
            name: "priority";
            tableName: "ntfy";
            dataType: "number";
            columnType: "PgInteger";
            data: number;
            driverParam: string | number;
            notNull: true;
            hasDefault: true;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: undefined;
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
    };
    dialect: "pg";
}>;
export declare const mattermost: import("drizzle-orm/pg-core").PgTableWithColumns<{
    name: "mattermost";
    schema: undefined;
    columns: {
        mattermostId: import("drizzle-orm/pg-core").PgColumn<{
            name: "mattermostId";
            tableName: "mattermost";
            dataType: "string";
            columnType: "PgText";
            data: string;
            driverParam: string;
            notNull: true;
            hasDefault: true;
            isPrimaryKey: true;
            isAutoincrement: false;
            hasRuntimeDefault: true;
            enumValues: [string, ...string[]];
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        webhookUrl: import("drizzle-orm/pg-core").PgColumn<{
            name: "webhookUrl";
            tableName: "mattermost";
            dataType: "string";
            columnType: "PgText";
            data: string;
            driverParam: string;
            notNull: true;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        channel: import("drizzle-orm/pg-core").PgColumn<{
            name: "channel";
            tableName: "mattermost";
            dataType: "string";
            columnType: "PgText";
            data: string;
            driverParam: string;
            notNull: false;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        username: import("drizzle-orm/pg-core").PgColumn<{
            name: "username";
            tableName: "mattermost";
            dataType: "string";
            columnType: "PgText";
            data: string;
            driverParam: string;
            notNull: false;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
    };
    dialect: "pg";
}>;
export declare const custom: import("drizzle-orm/pg-core").PgTableWithColumns<{
    name: "custom";
    schema: undefined;
    columns: {
        customId: import("drizzle-orm/pg-core").PgColumn<{
            name: "customId";
            tableName: "custom";
            dataType: "string";
            columnType: "PgText";
            data: string;
            driverParam: string;
            notNull: true;
            hasDefault: true;
            isPrimaryKey: true;
            isAutoincrement: false;
            hasRuntimeDefault: true;
            enumValues: [string, ...string[]];
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        endpoint: import("drizzle-orm/pg-core").PgColumn<{
            name: "endpoint";
            tableName: "custom";
            dataType: "string";
            columnType: "PgText";
            data: string;
            driverParam: string;
            notNull: true;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        headers: import("drizzle-orm/pg-core").PgColumn<{
            name: "headers";
            tableName: "custom";
            dataType: "json";
            columnType: "PgJsonb";
            data: Record<string, string>;
            driverParam: unknown;
            notNull: false;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: undefined;
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {
            $type: Record<string, string>;
        }>;
    };
    dialect: "pg";
}>;
export declare const lark: import("drizzle-orm/pg-core").PgTableWithColumns<{
    name: "lark";
    schema: undefined;
    columns: {
        larkId: import("drizzle-orm/pg-core").PgColumn<{
            name: "larkId";
            tableName: "lark";
            dataType: "string";
            columnType: "PgText";
            data: string;
            driverParam: string;
            notNull: true;
            hasDefault: true;
            isPrimaryKey: true;
            isAutoincrement: false;
            hasRuntimeDefault: true;
            enumValues: [string, ...string[]];
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        webhookUrl: import("drizzle-orm/pg-core").PgColumn<{
            name: "webhookUrl";
            tableName: "lark";
            dataType: "string";
            columnType: "PgText";
            data: string;
            driverParam: string;
            notNull: true;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
    };
    dialect: "pg";
}>;
export declare const pushover: import("drizzle-orm/pg-core").PgTableWithColumns<{
    name: "pushover";
    schema: undefined;
    columns: {
        pushoverId: import("drizzle-orm/pg-core").PgColumn<{
            name: "pushoverId";
            tableName: "pushover";
            dataType: "string";
            columnType: "PgText";
            data: string;
            driverParam: string;
            notNull: true;
            hasDefault: true;
            isPrimaryKey: true;
            isAutoincrement: false;
            hasRuntimeDefault: true;
            enumValues: [string, ...string[]];
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        userKey: import("drizzle-orm/pg-core").PgColumn<{
            name: "userKey";
            tableName: "pushover";
            dataType: "string";
            columnType: "PgText";
            data: string;
            driverParam: string;
            notNull: true;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        apiToken: import("drizzle-orm/pg-core").PgColumn<{
            name: "apiToken";
            tableName: "pushover";
            dataType: "string";
            columnType: "PgText";
            data: string;
            driverParam: string;
            notNull: true;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        priority: import("drizzle-orm/pg-core").PgColumn<{
            name: "priority";
            tableName: "pushover";
            dataType: "number";
            columnType: "PgInteger";
            data: number;
            driverParam: string | number;
            notNull: true;
            hasDefault: true;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: undefined;
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        retry: import("drizzle-orm/pg-core").PgColumn<{
            name: "retry";
            tableName: "pushover";
            dataType: "number";
            columnType: "PgInteger";
            data: number;
            driverParam: string | number;
            notNull: false;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: undefined;
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        expire: import("drizzle-orm/pg-core").PgColumn<{
            name: "expire";
            tableName: "pushover";
            dataType: "number";
            columnType: "PgInteger";
            data: number;
            driverParam: string | number;
            notNull: false;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: undefined;
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
    };
    dialect: "pg";
}>;
export declare const teams: import("drizzle-orm/pg-core").PgTableWithColumns<{
    name: "teams";
    schema: undefined;
    columns: {
        teamsId: import("drizzle-orm/pg-core").PgColumn<{
            name: "teamsId";
            tableName: "teams";
            dataType: "string";
            columnType: "PgText";
            data: string;
            driverParam: string;
            notNull: true;
            hasDefault: true;
            isPrimaryKey: true;
            isAutoincrement: false;
            hasRuntimeDefault: true;
            enumValues: [string, ...string[]];
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        webhookUrl: import("drizzle-orm/pg-core").PgColumn<{
            name: "webhookUrl";
            tableName: "teams";
            dataType: "string";
            columnType: "PgText";
            data: string;
            driverParam: string;
            notNull: true;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
    };
    dialect: "pg";
}>;
export declare const notificationsRelations: import("drizzle-orm").Relations<"notification", {
    slack: import("drizzle-orm").One<"slack", false>;
    telegram: import("drizzle-orm").One<"telegram", false>;
    discord: import("drizzle-orm").One<"discord", false>;
    email: import("drizzle-orm").One<"email", false>;
    resend: import("drizzle-orm").One<"resend", false>;
    gotify: import("drizzle-orm").One<"gotify", false>;
    ntfy: import("drizzle-orm").One<"ntfy", false>;
    mattermost: import("drizzle-orm").One<"mattermost", false>;
    custom: import("drizzle-orm").One<"custom", false>;
    lark: import("drizzle-orm").One<"lark", false>;
    pushover: import("drizzle-orm").One<"pushover", false>;
    teams: import("drizzle-orm").One<"teams", false>;
    organization: import("drizzle-orm").One<"organization", true>;
}>;
export declare const notificationsSchema: z.ZodObject<{
    name: z.ZodString;
    createdAt: z.ZodOptional<z.ZodString>;
    organizationId: z.ZodString;
    notificationType: z.ZodEnum<["slack", "telegram", "discord", "email", "resend", "gotify", "ntfy", "mattermost", "pushover", "custom", "lark", "teams"]>;
    customId: z.ZodOptional<z.ZodNullable<z.ZodString>>;
    emailId: z.ZodOptional<z.ZodNullable<z.ZodString>>;
    volumeBackup: z.ZodOptional<z.ZodBoolean>;
    notificationId: z.ZodOptional<z.ZodString>;
    appDeploy: z.ZodOptional<z.ZodBoolean>;
    appBuildError: z.ZodOptional<z.ZodBoolean>;
    databaseBackup: z.ZodOptional<z.ZodBoolean>;
    dokployRestart: z.ZodOptional<z.ZodBoolean>;
    dokployBackup: z.ZodOptional<z.ZodBoolean>;
    dockerCleanup: z.ZodOptional<z.ZodBoolean>;
    serverThreshold: z.ZodOptional<z.ZodBoolean>;
    slackId: z.ZodOptional<z.ZodNullable<z.ZodString>>;
    telegramId: z.ZodOptional<z.ZodNullable<z.ZodString>>;
    discordId: z.ZodOptional<z.ZodNullable<z.ZodString>>;
    resendId: z.ZodOptional<z.ZodNullable<z.ZodString>>;
    gotifyId: z.ZodOptional<z.ZodNullable<z.ZodString>>;
    ntfyId: z.ZodOptional<z.ZodNullable<z.ZodString>>;
    mattermostId: z.ZodOptional<z.ZodNullable<z.ZodString>>;
    larkId: z.ZodOptional<z.ZodNullable<z.ZodString>>;
    pushoverId: z.ZodOptional<z.ZodNullable<z.ZodString>>;
    teamsId: z.ZodOptional<z.ZodNullable<z.ZodString>>;
}, z.core.$strip>;
export declare const apiCreateSlack: z.ZodObject<{
    name: z.ZodNonOptional<z.ZodString>;
    volumeBackup: z.ZodNonOptional<z.ZodOptional<z.ZodBoolean>>;
    appDeploy: z.ZodNonOptional<z.ZodOptional<z.ZodBoolean>>;
    appBuildError: z.ZodNonOptional<z.ZodOptional<z.ZodBoolean>>;
    databaseBackup: z.ZodNonOptional<z.ZodOptional<z.ZodBoolean>>;
    dokployRestart: z.ZodNonOptional<z.ZodOptional<z.ZodBoolean>>;
    dokployBackup: z.ZodNonOptional<z.ZodOptional<z.ZodBoolean>>;
    dockerCleanup: z.ZodNonOptional<z.ZodOptional<z.ZodBoolean>>;
    serverThreshold: z.ZodNonOptional<z.ZodOptional<z.ZodBoolean>>;
    webhookUrl: z.ZodNonOptional<z.ZodString>;
    channel: z.ZodNonOptional<z.ZodString>;
}, z.core.$strip>;
export declare const apiUpdateSlack: z.ZodObject<{
    name: z.ZodOptional<z.ZodNonOptional<z.ZodString>>;
    volumeBackup: z.ZodOptional<z.ZodNonOptional<z.ZodOptional<z.ZodBoolean>>>;
    appDeploy: z.ZodOptional<z.ZodNonOptional<z.ZodOptional<z.ZodBoolean>>>;
    appBuildError: z.ZodOptional<z.ZodNonOptional<z.ZodOptional<z.ZodBoolean>>>;
    databaseBackup: z.ZodOptional<z.ZodNonOptional<z.ZodOptional<z.ZodBoolean>>>;
    dokployRestart: z.ZodOptional<z.ZodNonOptional<z.ZodOptional<z.ZodBoolean>>>;
    dokployBackup: z.ZodOptional<z.ZodNonOptional<z.ZodOptional<z.ZodBoolean>>>;
    dockerCleanup: z.ZodOptional<z.ZodNonOptional<z.ZodOptional<z.ZodBoolean>>>;
    serverThreshold: z.ZodOptional<z.ZodNonOptional<z.ZodOptional<z.ZodBoolean>>>;
    webhookUrl: z.ZodOptional<z.ZodNonOptional<z.ZodString>>;
    channel: z.ZodOptional<z.ZodNonOptional<z.ZodString>>;
    notificationId: z.ZodString;
    slackId: z.ZodString;
    organizationId: z.ZodOptional<z.ZodString>;
}, z.core.$strip>;
export declare const apiTestSlackConnection: z.ZodObject<{
    webhookUrl: z.ZodNonOptional<z.ZodString>;
    channel: z.ZodNonOptional<z.ZodString>;
}, z.core.$strip>;
export declare const apiCreateTelegram: z.ZodObject<{
    name: z.ZodNonOptional<z.ZodString>;
    volumeBackup: z.ZodNonOptional<z.ZodOptional<z.ZodBoolean>>;
    appDeploy: z.ZodNonOptional<z.ZodOptional<z.ZodBoolean>>;
    appBuildError: z.ZodNonOptional<z.ZodOptional<z.ZodBoolean>>;
    databaseBackup: z.ZodNonOptional<z.ZodOptional<z.ZodBoolean>>;
    dokployRestart: z.ZodNonOptional<z.ZodOptional<z.ZodBoolean>>;
    dokployBackup: z.ZodNonOptional<z.ZodOptional<z.ZodBoolean>>;
    dockerCleanup: z.ZodNonOptional<z.ZodOptional<z.ZodBoolean>>;
    serverThreshold: z.ZodNonOptional<z.ZodOptional<z.ZodBoolean>>;
    botToken: z.ZodNonOptional<z.ZodString>;
    chatId: z.ZodNonOptional<z.ZodString>;
    messageThreadId: z.ZodNonOptional<z.ZodString>;
}, z.core.$strip>;
export declare const apiUpdateTelegram: z.ZodObject<{
    name: z.ZodOptional<z.ZodNonOptional<z.ZodString>>;
    volumeBackup: z.ZodOptional<z.ZodNonOptional<z.ZodOptional<z.ZodBoolean>>>;
    appDeploy: z.ZodOptional<z.ZodNonOptional<z.ZodOptional<z.ZodBoolean>>>;
    appBuildError: z.ZodOptional<z.ZodNonOptional<z.ZodOptional<z.ZodBoolean>>>;
    databaseBackup: z.ZodOptional<z.ZodNonOptional<z.ZodOptional<z.ZodBoolean>>>;
    dokployRestart: z.ZodOptional<z.ZodNonOptional<z.ZodOptional<z.ZodBoolean>>>;
    dokployBackup: z.ZodOptional<z.ZodNonOptional<z.ZodOptional<z.ZodBoolean>>>;
    dockerCleanup: z.ZodOptional<z.ZodNonOptional<z.ZodOptional<z.ZodBoolean>>>;
    serverThreshold: z.ZodOptional<z.ZodNonOptional<z.ZodOptional<z.ZodBoolean>>>;
    botToken: z.ZodOptional<z.ZodNonOptional<z.ZodString>>;
    chatId: z.ZodOptional<z.ZodNonOptional<z.ZodString>>;
    messageThreadId: z.ZodOptional<z.ZodNonOptional<z.ZodString>>;
    notificationId: z.ZodString;
    telegramId: z.ZodString;
    organizationId: z.ZodOptional<z.ZodString>;
}, z.core.$strip>;
export declare const apiTestTelegramConnection: z.ZodObject<{
    botToken: z.ZodNonOptional<z.ZodString>;
    chatId: z.ZodNonOptional<z.ZodString>;
    messageThreadId: z.ZodNonOptional<z.ZodString>;
}, z.core.$strip>;
export declare const apiCreateDiscord: z.ZodObject<{
    name: z.ZodNonOptional<z.ZodString>;
    volumeBackup: z.ZodNonOptional<z.ZodOptional<z.ZodBoolean>>;
    appDeploy: z.ZodNonOptional<z.ZodOptional<z.ZodBoolean>>;
    appBuildError: z.ZodNonOptional<z.ZodOptional<z.ZodBoolean>>;
    databaseBackup: z.ZodNonOptional<z.ZodOptional<z.ZodBoolean>>;
    dokployRestart: z.ZodNonOptional<z.ZodOptional<z.ZodBoolean>>;
    dokployBackup: z.ZodNonOptional<z.ZodOptional<z.ZodBoolean>>;
    dockerCleanup: z.ZodNonOptional<z.ZodOptional<z.ZodBoolean>>;
    serverThreshold: z.ZodNonOptional<z.ZodOptional<z.ZodBoolean>>;
    webhookUrl: z.ZodNonOptional<z.ZodString>;
    decoration: z.ZodNonOptional<z.ZodBoolean>;
}, z.core.$strip>;
export declare const apiUpdateDiscord: z.ZodObject<{
    name: z.ZodOptional<z.ZodNonOptional<z.ZodString>>;
    volumeBackup: z.ZodOptional<z.ZodNonOptional<z.ZodOptional<z.ZodBoolean>>>;
    appDeploy: z.ZodOptional<z.ZodNonOptional<z.ZodOptional<z.ZodBoolean>>>;
    appBuildError: z.ZodOptional<z.ZodNonOptional<z.ZodOptional<z.ZodBoolean>>>;
    databaseBackup: z.ZodOptional<z.ZodNonOptional<z.ZodOptional<z.ZodBoolean>>>;
    dokployRestart: z.ZodOptional<z.ZodNonOptional<z.ZodOptional<z.ZodBoolean>>>;
    dokployBackup: z.ZodOptional<z.ZodNonOptional<z.ZodOptional<z.ZodBoolean>>>;
    dockerCleanup: z.ZodOptional<z.ZodNonOptional<z.ZodOptional<z.ZodBoolean>>>;
    serverThreshold: z.ZodOptional<z.ZodNonOptional<z.ZodOptional<z.ZodBoolean>>>;
    webhookUrl: z.ZodOptional<z.ZodNonOptional<z.ZodString>>;
    decoration: z.ZodOptional<z.ZodNonOptional<z.ZodBoolean>>;
    notificationId: z.ZodString;
    discordId: z.ZodString;
    organizationId: z.ZodOptional<z.ZodString>;
}, z.core.$strip>;
export declare const apiTestDiscordConnection: z.ZodObject<{
    webhookUrl: z.ZodNonOptional<z.ZodString>;
    decoration: z.ZodOptional<z.ZodBoolean>;
}, z.core.$strip>;
export declare const apiCreateEmail: z.ZodObject<{
    name: z.ZodNonOptional<z.ZodString>;
    volumeBackup: z.ZodNonOptional<z.ZodOptional<z.ZodBoolean>>;
    appDeploy: z.ZodNonOptional<z.ZodOptional<z.ZodBoolean>>;
    appBuildError: z.ZodNonOptional<z.ZodOptional<z.ZodBoolean>>;
    databaseBackup: z.ZodNonOptional<z.ZodOptional<z.ZodBoolean>>;
    dokployRestart: z.ZodNonOptional<z.ZodOptional<z.ZodBoolean>>;
    dokployBackup: z.ZodNonOptional<z.ZodOptional<z.ZodBoolean>>;
    dockerCleanup: z.ZodNonOptional<z.ZodOptional<z.ZodBoolean>>;
    serverThreshold: z.ZodNonOptional<z.ZodOptional<z.ZodBoolean>>;
    smtpServer: z.ZodNonOptional<z.ZodString>;
    smtpPort: z.ZodNonOptional<z.ZodNumber>;
    username: z.ZodNonOptional<z.ZodString>;
    password: z.ZodNonOptional<z.ZodString>;
    fromAddress: z.ZodNonOptional<z.ZodString>;
    toAddresses: z.ZodNonOptional<z.ZodArray<z.ZodString>>;
}, z.core.$strip>;
export declare const apiUpdateEmail: z.ZodObject<{
    name: z.ZodOptional<z.ZodNonOptional<z.ZodString>>;
    volumeBackup: z.ZodOptional<z.ZodNonOptional<z.ZodOptional<z.ZodBoolean>>>;
    appDeploy: z.ZodOptional<z.ZodNonOptional<z.ZodOptional<z.ZodBoolean>>>;
    appBuildError: z.ZodOptional<z.ZodNonOptional<z.ZodOptional<z.ZodBoolean>>>;
    databaseBackup: z.ZodOptional<z.ZodNonOptional<z.ZodOptional<z.ZodBoolean>>>;
    dokployRestart: z.ZodOptional<z.ZodNonOptional<z.ZodOptional<z.ZodBoolean>>>;
    dokployBackup: z.ZodOptional<z.ZodNonOptional<z.ZodOptional<z.ZodBoolean>>>;
    dockerCleanup: z.ZodOptional<z.ZodNonOptional<z.ZodOptional<z.ZodBoolean>>>;
    serverThreshold: z.ZodOptional<z.ZodNonOptional<z.ZodOptional<z.ZodBoolean>>>;
    smtpServer: z.ZodOptional<z.ZodNonOptional<z.ZodString>>;
    smtpPort: z.ZodOptional<z.ZodNonOptional<z.ZodNumber>>;
    username: z.ZodOptional<z.ZodNonOptional<z.ZodString>>;
    password: z.ZodOptional<z.ZodNonOptional<z.ZodString>>;
    fromAddress: z.ZodOptional<z.ZodNonOptional<z.ZodString>>;
    toAddresses: z.ZodOptional<z.ZodNonOptional<z.ZodArray<z.ZodString>>>;
    notificationId: z.ZodString;
    emailId: z.ZodString;
    organizationId: z.ZodOptional<z.ZodString>;
}, z.core.$strip>;
export declare const apiTestEmailConnection: z.ZodObject<{
    username: z.ZodNonOptional<z.ZodString>;
    password: z.ZodNonOptional<z.ZodString>;
    smtpServer: z.ZodNonOptional<z.ZodString>;
    smtpPort: z.ZodNonOptional<z.ZodNumber>;
    fromAddress: z.ZodNonOptional<z.ZodString>;
    toAddresses: z.ZodNonOptional<z.ZodArray<z.ZodString>>;
}, z.core.$strip>;
export declare const apiCreateResend: z.ZodObject<{
    name: z.ZodNonOptional<z.ZodString>;
    volumeBackup: z.ZodNonOptional<z.ZodOptional<z.ZodBoolean>>;
    appDeploy: z.ZodNonOptional<z.ZodOptional<z.ZodBoolean>>;
    appBuildError: z.ZodNonOptional<z.ZodOptional<z.ZodBoolean>>;
    databaseBackup: z.ZodNonOptional<z.ZodOptional<z.ZodBoolean>>;
    dokployRestart: z.ZodNonOptional<z.ZodOptional<z.ZodBoolean>>;
    dokployBackup: z.ZodNonOptional<z.ZodOptional<z.ZodBoolean>>;
    dockerCleanup: z.ZodNonOptional<z.ZodOptional<z.ZodBoolean>>;
    serverThreshold: z.ZodNonOptional<z.ZodOptional<z.ZodBoolean>>;
    apiKey: z.ZodNonOptional<z.ZodString>;
    fromAddress: z.ZodNonOptional<z.ZodString>;
    toAddresses: z.ZodNonOptional<z.ZodArray<z.ZodString>>;
}, z.core.$strip>;
export declare const apiUpdateResend: z.ZodObject<{
    name: z.ZodOptional<z.ZodNonOptional<z.ZodString>>;
    volumeBackup: z.ZodOptional<z.ZodNonOptional<z.ZodOptional<z.ZodBoolean>>>;
    appDeploy: z.ZodOptional<z.ZodNonOptional<z.ZodOptional<z.ZodBoolean>>>;
    appBuildError: z.ZodOptional<z.ZodNonOptional<z.ZodOptional<z.ZodBoolean>>>;
    databaseBackup: z.ZodOptional<z.ZodNonOptional<z.ZodOptional<z.ZodBoolean>>>;
    dokployRestart: z.ZodOptional<z.ZodNonOptional<z.ZodOptional<z.ZodBoolean>>>;
    dokployBackup: z.ZodOptional<z.ZodNonOptional<z.ZodOptional<z.ZodBoolean>>>;
    dockerCleanup: z.ZodOptional<z.ZodNonOptional<z.ZodOptional<z.ZodBoolean>>>;
    serverThreshold: z.ZodOptional<z.ZodNonOptional<z.ZodOptional<z.ZodBoolean>>>;
    apiKey: z.ZodOptional<z.ZodNonOptional<z.ZodString>>;
    fromAddress: z.ZodOptional<z.ZodNonOptional<z.ZodString>>;
    toAddresses: z.ZodOptional<z.ZodNonOptional<z.ZodArray<z.ZodString>>>;
    notificationId: z.ZodString;
    resendId: z.ZodString;
    organizationId: z.ZodOptional<z.ZodString>;
}, z.core.$strip>;
export declare const apiTestResendConnection: z.ZodObject<{
    fromAddress: z.ZodNonOptional<z.ZodString>;
    toAddresses: z.ZodNonOptional<z.ZodArray<z.ZodString>>;
    apiKey: z.ZodNonOptional<z.ZodString>;
}, z.core.$strip>;
export declare const apiCreateGotify: z.ZodObject<{
    name: z.ZodNonOptional<z.ZodString>;
    volumeBackup: z.ZodNonOptional<z.ZodOptional<z.ZodBoolean>>;
    appDeploy: z.ZodNonOptional<z.ZodOptional<z.ZodBoolean>>;
    appBuildError: z.ZodNonOptional<z.ZodOptional<z.ZodBoolean>>;
    databaseBackup: z.ZodNonOptional<z.ZodOptional<z.ZodBoolean>>;
    dokployRestart: z.ZodNonOptional<z.ZodOptional<z.ZodBoolean>>;
    dokployBackup: z.ZodNonOptional<z.ZodOptional<z.ZodBoolean>>;
    dockerCleanup: z.ZodNonOptional<z.ZodOptional<z.ZodBoolean>>;
    serverUrl: z.ZodNonOptional<z.ZodString>;
    appToken: z.ZodNonOptional<z.ZodString>;
    priority: z.ZodNonOptional<z.ZodNumber>;
    decoration: z.ZodNonOptional<z.ZodBoolean>;
}, z.core.$strip>;
export declare const apiUpdateGotify: z.ZodObject<{
    name: z.ZodOptional<z.ZodNonOptional<z.ZodString>>;
    volumeBackup: z.ZodOptional<z.ZodNonOptional<z.ZodOptional<z.ZodBoolean>>>;
    appDeploy: z.ZodOptional<z.ZodNonOptional<z.ZodOptional<z.ZodBoolean>>>;
    appBuildError: z.ZodOptional<z.ZodNonOptional<z.ZodOptional<z.ZodBoolean>>>;
    databaseBackup: z.ZodOptional<z.ZodNonOptional<z.ZodOptional<z.ZodBoolean>>>;
    dokployRestart: z.ZodOptional<z.ZodNonOptional<z.ZodOptional<z.ZodBoolean>>>;
    dokployBackup: z.ZodOptional<z.ZodNonOptional<z.ZodOptional<z.ZodBoolean>>>;
    dockerCleanup: z.ZodOptional<z.ZodNonOptional<z.ZodOptional<z.ZodBoolean>>>;
    serverUrl: z.ZodOptional<z.ZodNonOptional<z.ZodString>>;
    appToken: z.ZodOptional<z.ZodNonOptional<z.ZodString>>;
    priority: z.ZodOptional<z.ZodNonOptional<z.ZodNumber>>;
    decoration: z.ZodOptional<z.ZodNonOptional<z.ZodBoolean>>;
    notificationId: z.ZodString;
    gotifyId: z.ZodString;
    organizationId: z.ZodOptional<z.ZodString>;
}, z.core.$strip>;
export declare const apiTestGotifyConnection: z.ZodObject<{
    serverUrl: z.ZodNonOptional<z.ZodString>;
    appToken: z.ZodNonOptional<z.ZodString>;
    priority: z.ZodNonOptional<z.ZodNumber>;
    decoration: z.ZodOptional<z.ZodBoolean>;
}, z.core.$strip>;
export declare const apiCreateNtfy: z.ZodObject<{
    name: z.ZodNonOptional<z.ZodString>;
    volumeBackup: z.ZodNonOptional<z.ZodOptional<z.ZodBoolean>>;
    appDeploy: z.ZodNonOptional<z.ZodOptional<z.ZodBoolean>>;
    appBuildError: z.ZodNonOptional<z.ZodOptional<z.ZodBoolean>>;
    databaseBackup: z.ZodNonOptional<z.ZodOptional<z.ZodBoolean>>;
    dokployRestart: z.ZodNonOptional<z.ZodOptional<z.ZodBoolean>>;
    dokployBackup: z.ZodNonOptional<z.ZodOptional<z.ZodBoolean>>;
    dockerCleanup: z.ZodNonOptional<z.ZodOptional<z.ZodBoolean>>;
    serverUrl: z.ZodNonOptional<z.ZodString>;
    topic: z.ZodNonOptional<z.ZodString>;
    accessToken: z.ZodNonOptional<z.ZodOptional<z.ZodString>>;
    priority: z.ZodNonOptional<z.ZodNumber>;
}, z.core.$strip>;
export declare const apiUpdateNtfy: z.ZodObject<{
    name: z.ZodOptional<z.ZodNonOptional<z.ZodString>>;
    volumeBackup: z.ZodOptional<z.ZodNonOptional<z.ZodOptional<z.ZodBoolean>>>;
    appDeploy: z.ZodOptional<z.ZodNonOptional<z.ZodOptional<z.ZodBoolean>>>;
    appBuildError: z.ZodOptional<z.ZodNonOptional<z.ZodOptional<z.ZodBoolean>>>;
    databaseBackup: z.ZodOptional<z.ZodNonOptional<z.ZodOptional<z.ZodBoolean>>>;
    dokployRestart: z.ZodOptional<z.ZodNonOptional<z.ZodOptional<z.ZodBoolean>>>;
    dokployBackup: z.ZodOptional<z.ZodNonOptional<z.ZodOptional<z.ZodBoolean>>>;
    dockerCleanup: z.ZodOptional<z.ZodNonOptional<z.ZodOptional<z.ZodBoolean>>>;
    serverUrl: z.ZodOptional<z.ZodNonOptional<z.ZodString>>;
    topic: z.ZodOptional<z.ZodNonOptional<z.ZodString>>;
    accessToken: z.ZodOptional<z.ZodNonOptional<z.ZodOptional<z.ZodString>>>;
    priority: z.ZodOptional<z.ZodNonOptional<z.ZodNumber>>;
    notificationId: z.ZodString;
    ntfyId: z.ZodString;
    organizationId: z.ZodOptional<z.ZodString>;
}, z.core.$strip>;
export declare const apiTestNtfyConnection: z.ZodObject<{
    accessToken: z.ZodNonOptional<z.ZodOptional<z.ZodString>>;
    serverUrl: z.ZodNonOptional<z.ZodString>;
    priority: z.ZodNonOptional<z.ZodNumber>;
    topic: z.ZodNonOptional<z.ZodString>;
}, z.core.$strip>;
export declare const apiCreateMattermost: z.ZodObject<{
    name: z.ZodNonOptional<z.ZodString>;
    volumeBackup: z.ZodNonOptional<z.ZodOptional<z.ZodBoolean>>;
    appDeploy: z.ZodNonOptional<z.ZodOptional<z.ZodBoolean>>;
    appBuildError: z.ZodNonOptional<z.ZodOptional<z.ZodBoolean>>;
    databaseBackup: z.ZodNonOptional<z.ZodOptional<z.ZodBoolean>>;
    dokployRestart: z.ZodNonOptional<z.ZodOptional<z.ZodBoolean>>;
    dokployBackup: z.ZodNonOptional<z.ZodOptional<z.ZodBoolean>>;
    dockerCleanup: z.ZodNonOptional<z.ZodOptional<z.ZodBoolean>>;
    serverThreshold: z.ZodNonOptional<z.ZodOptional<z.ZodBoolean>>;
    webhookUrl: z.ZodNonOptional<z.ZodString>;
    channel: z.ZodOptional<z.ZodString>;
    username: z.ZodOptional<z.ZodString>;
}, z.core.$strip>;
export declare const apiUpdateMattermost: z.ZodObject<{
    name: z.ZodOptional<z.ZodNonOptional<z.ZodString>>;
    volumeBackup: z.ZodOptional<z.ZodNonOptional<z.ZodOptional<z.ZodBoolean>>>;
    appDeploy: z.ZodOptional<z.ZodNonOptional<z.ZodOptional<z.ZodBoolean>>>;
    appBuildError: z.ZodOptional<z.ZodNonOptional<z.ZodOptional<z.ZodBoolean>>>;
    databaseBackup: z.ZodOptional<z.ZodNonOptional<z.ZodOptional<z.ZodBoolean>>>;
    dokployRestart: z.ZodOptional<z.ZodNonOptional<z.ZodOptional<z.ZodBoolean>>>;
    dokployBackup: z.ZodOptional<z.ZodNonOptional<z.ZodOptional<z.ZodBoolean>>>;
    dockerCleanup: z.ZodOptional<z.ZodNonOptional<z.ZodOptional<z.ZodBoolean>>>;
    serverThreshold: z.ZodOptional<z.ZodNonOptional<z.ZodOptional<z.ZodBoolean>>>;
    webhookUrl: z.ZodOptional<z.ZodNonOptional<z.ZodString>>;
    channel: z.ZodOptional<z.ZodOptional<z.ZodString>>;
    username: z.ZodOptional<z.ZodOptional<z.ZodString>>;
    notificationId: z.ZodString;
    mattermostId: z.ZodString;
    organizationId: z.ZodOptional<z.ZodString>;
}, z.core.$strip>;
export declare const apiTestMattermostConnection: z.ZodObject<{
    webhookUrl: z.ZodNonOptional<z.ZodString>;
    channel: z.ZodOptional<z.ZodString>;
    username: z.ZodOptional<z.ZodString>;
}, z.core.$strip>;
export declare const apiFindOneNotification: z.ZodObject<{
    notificationId: z.ZodString;
}, z.core.$strip>;
export declare const apiCreateCustom: z.ZodObject<{
    name: z.ZodString;
    volumeBackup: z.ZodOptional<z.ZodBoolean>;
    appDeploy: z.ZodOptional<z.ZodBoolean>;
    appBuildError: z.ZodOptional<z.ZodBoolean>;
    databaseBackup: z.ZodOptional<z.ZodBoolean>;
    dokployRestart: z.ZodOptional<z.ZodBoolean>;
    dokployBackup: z.ZodOptional<z.ZodBoolean>;
    dockerCleanup: z.ZodOptional<z.ZodBoolean>;
    serverThreshold: z.ZodOptional<z.ZodBoolean>;
    endpoint: z.ZodString;
    headers: z.ZodOptional<z.ZodRecord<z.ZodString, z.ZodString>>;
}, z.core.$strip>;
export declare const apiUpdateCustom: z.ZodObject<{
    name: z.ZodOptional<z.ZodString>;
    volumeBackup: z.ZodOptional<z.ZodOptional<z.ZodBoolean>>;
    appDeploy: z.ZodOptional<z.ZodOptional<z.ZodBoolean>>;
    appBuildError: z.ZodOptional<z.ZodOptional<z.ZodBoolean>>;
    databaseBackup: z.ZodOptional<z.ZodOptional<z.ZodBoolean>>;
    dokployRestart: z.ZodOptional<z.ZodOptional<z.ZodBoolean>>;
    dokployBackup: z.ZodOptional<z.ZodOptional<z.ZodBoolean>>;
    dockerCleanup: z.ZodOptional<z.ZodOptional<z.ZodBoolean>>;
    serverThreshold: z.ZodOptional<z.ZodOptional<z.ZodBoolean>>;
    endpoint: z.ZodOptional<z.ZodString>;
    headers: z.ZodOptional<z.ZodOptional<z.ZodRecord<z.ZodString, z.ZodString>>>;
    notificationId: z.ZodString;
    customId: z.ZodString;
    organizationId: z.ZodOptional<z.ZodString>;
}, z.core.$strip>;
export declare const apiTestCustomConnection: z.ZodObject<{
    endpoint: z.ZodString;
    headers: z.ZodOptional<z.ZodRecord<z.ZodString, z.ZodString>>;
}, z.core.$strip>;
export declare const apiCreateLark: z.ZodObject<{
    name: z.ZodNonOptional<z.ZodString>;
    volumeBackup: z.ZodNonOptional<z.ZodOptional<z.ZodBoolean>>;
    appDeploy: z.ZodNonOptional<z.ZodOptional<z.ZodBoolean>>;
    appBuildError: z.ZodNonOptional<z.ZodOptional<z.ZodBoolean>>;
    databaseBackup: z.ZodNonOptional<z.ZodOptional<z.ZodBoolean>>;
    dokployRestart: z.ZodNonOptional<z.ZodOptional<z.ZodBoolean>>;
    dokployBackup: z.ZodNonOptional<z.ZodOptional<z.ZodBoolean>>;
    dockerCleanup: z.ZodNonOptional<z.ZodOptional<z.ZodBoolean>>;
    serverThreshold: z.ZodNonOptional<z.ZodOptional<z.ZodBoolean>>;
    webhookUrl: z.ZodNonOptional<z.ZodString>;
}, z.core.$strip>;
export declare const apiUpdateLark: z.ZodObject<{
    name: z.ZodOptional<z.ZodNonOptional<z.ZodString>>;
    volumeBackup: z.ZodOptional<z.ZodNonOptional<z.ZodOptional<z.ZodBoolean>>>;
    appDeploy: z.ZodOptional<z.ZodNonOptional<z.ZodOptional<z.ZodBoolean>>>;
    appBuildError: z.ZodOptional<z.ZodNonOptional<z.ZodOptional<z.ZodBoolean>>>;
    databaseBackup: z.ZodOptional<z.ZodNonOptional<z.ZodOptional<z.ZodBoolean>>>;
    dokployRestart: z.ZodOptional<z.ZodNonOptional<z.ZodOptional<z.ZodBoolean>>>;
    dokployBackup: z.ZodOptional<z.ZodNonOptional<z.ZodOptional<z.ZodBoolean>>>;
    dockerCleanup: z.ZodOptional<z.ZodNonOptional<z.ZodOptional<z.ZodBoolean>>>;
    serverThreshold: z.ZodOptional<z.ZodNonOptional<z.ZodOptional<z.ZodBoolean>>>;
    webhookUrl: z.ZodOptional<z.ZodNonOptional<z.ZodString>>;
    notificationId: z.ZodString;
    larkId: z.ZodString;
    organizationId: z.ZodOptional<z.ZodString>;
}, z.core.$strip>;
export declare const apiTestLarkConnection: z.ZodObject<{
    webhookUrl: z.ZodNonOptional<z.ZodString>;
}, z.core.$strip>;
export declare const apiCreateTeams: z.ZodObject<{
    name: z.ZodNonOptional<z.ZodString>;
    volumeBackup: z.ZodNonOptional<z.ZodOptional<z.ZodBoolean>>;
    appDeploy: z.ZodNonOptional<z.ZodOptional<z.ZodBoolean>>;
    appBuildError: z.ZodNonOptional<z.ZodOptional<z.ZodBoolean>>;
    databaseBackup: z.ZodNonOptional<z.ZodOptional<z.ZodBoolean>>;
    dokployRestart: z.ZodNonOptional<z.ZodOptional<z.ZodBoolean>>;
    dokployBackup: z.ZodNonOptional<z.ZodOptional<z.ZodBoolean>>;
    dockerCleanup: z.ZodNonOptional<z.ZodOptional<z.ZodBoolean>>;
    serverThreshold: z.ZodNonOptional<z.ZodOptional<z.ZodBoolean>>;
    webhookUrl: z.ZodNonOptional<z.ZodString>;
}, z.core.$strip>;
export declare const apiUpdateTeams: z.ZodObject<{
    name: z.ZodOptional<z.ZodNonOptional<z.ZodString>>;
    volumeBackup: z.ZodOptional<z.ZodNonOptional<z.ZodOptional<z.ZodBoolean>>>;
    appDeploy: z.ZodOptional<z.ZodNonOptional<z.ZodOptional<z.ZodBoolean>>>;
    appBuildError: z.ZodOptional<z.ZodNonOptional<z.ZodOptional<z.ZodBoolean>>>;
    databaseBackup: z.ZodOptional<z.ZodNonOptional<z.ZodOptional<z.ZodBoolean>>>;
    dokployRestart: z.ZodOptional<z.ZodNonOptional<z.ZodOptional<z.ZodBoolean>>>;
    dokployBackup: z.ZodOptional<z.ZodNonOptional<z.ZodOptional<z.ZodBoolean>>>;
    dockerCleanup: z.ZodOptional<z.ZodNonOptional<z.ZodOptional<z.ZodBoolean>>>;
    serverThreshold: z.ZodOptional<z.ZodNonOptional<z.ZodOptional<z.ZodBoolean>>>;
    webhookUrl: z.ZodOptional<z.ZodNonOptional<z.ZodString>>;
    notificationId: z.ZodString;
    teamsId: z.ZodString;
    organizationId: z.ZodOptional<z.ZodString>;
}, z.core.$strip>;
export declare const apiTestTeamsConnection: z.ZodObject<{
    webhookUrl: z.ZodNonOptional<z.ZodString>;
}, z.core.$strip>;
export declare const apiCreatePushover: z.ZodObject<{
    name: z.ZodString;
    volumeBackup: z.ZodOptional<z.ZodBoolean>;
    appDeploy: z.ZodOptional<z.ZodBoolean>;
    appBuildError: z.ZodOptional<z.ZodBoolean>;
    databaseBackup: z.ZodOptional<z.ZodBoolean>;
    dokployRestart: z.ZodOptional<z.ZodBoolean>;
    dokployBackup: z.ZodOptional<z.ZodBoolean>;
    dockerCleanup: z.ZodOptional<z.ZodBoolean>;
    serverThreshold: z.ZodOptional<z.ZodBoolean>;
    userKey: z.ZodString;
    apiToken: z.ZodString;
    priority: z.ZodDefault<z.ZodNumber>;
    retry: z.ZodOptional<z.ZodNullable<z.ZodNumber>>;
    expire: z.ZodOptional<z.ZodNullable<z.ZodNumber>>;
}, z.core.$strip>;
export declare const apiUpdatePushover: z.ZodObject<{
    notificationId: z.ZodString;
    pushoverId: z.ZodString;
    organizationId: z.ZodOptional<z.ZodString>;
    userKey: z.ZodOptional<z.ZodString>;
    apiToken: z.ZodOptional<z.ZodString>;
    priority: z.ZodOptional<z.ZodNumber>;
    retry: z.ZodOptional<z.ZodNullable<z.ZodNumber>>;
    expire: z.ZodOptional<z.ZodNullable<z.ZodNumber>>;
    appBuildError: z.ZodOptional<z.ZodBoolean>;
    databaseBackup: z.ZodOptional<z.ZodBoolean>;
    dokployBackup: z.ZodOptional<z.ZodBoolean>;
    volumeBackup: z.ZodOptional<z.ZodBoolean>;
    dokployRestart: z.ZodOptional<z.ZodBoolean>;
    name: z.ZodOptional<z.ZodString>;
    appDeploy: z.ZodOptional<z.ZodBoolean>;
    dockerCleanup: z.ZodOptional<z.ZodBoolean>;
    serverThreshold: z.ZodOptional<z.ZodBoolean>;
}, z.core.$strip>;
export declare const apiTestPushoverConnection: z.ZodObject<{
    userKey: z.ZodString;
    apiToken: z.ZodString;
    priority: z.ZodNumber;
    retry: z.ZodOptional<z.ZodNullable<z.ZodNumber>>;
    expire: z.ZodOptional<z.ZodNullable<z.ZodNumber>>;
}, z.core.$strip>;
export declare const apiSendTest: z.ZodObject<{
    name: z.ZodOptional<z.ZodString>;
    createdAt: z.ZodOptional<z.ZodOptional<z.ZodString>>;
    organizationId: z.ZodOptional<z.ZodString>;
    notificationType: z.ZodOptional<z.ZodEnum<["slack", "telegram", "discord", "email", "resend", "gotify", "ntfy", "mattermost", "pushover", "custom", "lark", "teams"]>>;
    customId: z.ZodOptional<z.ZodOptional<z.ZodNullable<z.ZodString>>>;
    emailId: z.ZodOptional<z.ZodOptional<z.ZodNullable<z.ZodString>>>;
    volumeBackup: z.ZodOptional<z.ZodOptional<z.ZodBoolean>>;
    notificationId: z.ZodOptional<z.ZodOptional<z.ZodString>>;
    appDeploy: z.ZodOptional<z.ZodOptional<z.ZodBoolean>>;
    appBuildError: z.ZodOptional<z.ZodOptional<z.ZodBoolean>>;
    databaseBackup: z.ZodOptional<z.ZodOptional<z.ZodBoolean>>;
    dokployRestart: z.ZodOptional<z.ZodOptional<z.ZodBoolean>>;
    dokployBackup: z.ZodOptional<z.ZodOptional<z.ZodBoolean>>;
    dockerCleanup: z.ZodOptional<z.ZodOptional<z.ZodBoolean>>;
    serverThreshold: z.ZodOptional<z.ZodOptional<z.ZodBoolean>>;
    slackId: z.ZodOptional<z.ZodOptional<z.ZodNullable<z.ZodString>>>;
    telegramId: z.ZodOptional<z.ZodOptional<z.ZodNullable<z.ZodString>>>;
    discordId: z.ZodOptional<z.ZodOptional<z.ZodNullable<z.ZodString>>>;
    resendId: z.ZodOptional<z.ZodOptional<z.ZodNullable<z.ZodString>>>;
    gotifyId: z.ZodOptional<z.ZodOptional<z.ZodNullable<z.ZodString>>>;
    ntfyId: z.ZodOptional<z.ZodOptional<z.ZodNullable<z.ZodString>>>;
    mattermostId: z.ZodOptional<z.ZodOptional<z.ZodNullable<z.ZodString>>>;
    larkId: z.ZodOptional<z.ZodOptional<z.ZodNullable<z.ZodString>>>;
    pushoverId: z.ZodOptional<z.ZodOptional<z.ZodNullable<z.ZodString>>>;
    teamsId: z.ZodOptional<z.ZodOptional<z.ZodNullable<z.ZodString>>>;
    botToken: z.ZodOptional<z.ZodString>;
    chatId: z.ZodOptional<z.ZodString>;
    webhookUrl: z.ZodOptional<z.ZodString>;
    channel: z.ZodOptional<z.ZodString>;
    smtpServer: z.ZodOptional<z.ZodString>;
    smtpPort: z.ZodOptional<z.ZodNumber>;
    fromAddress: z.ZodOptional<z.ZodString>;
    username: z.ZodOptional<z.ZodString>;
    password: z.ZodOptional<z.ZodString>;
    toAddresses: z.ZodOptional<z.ZodArray<z.ZodString>>;
    apiKey: z.ZodOptional<z.ZodString>;
    serverUrl: z.ZodOptional<z.ZodString>;
    topic: z.ZodOptional<z.ZodString>;
    appToken: z.ZodOptional<z.ZodString>;
    accessToken: z.ZodOptional<z.ZodOptional<z.ZodString>>;
    priority: z.ZodOptional<z.ZodNumber>;
    endpoint: z.ZodOptional<z.ZodString>;
    headers: z.ZodOptional<z.ZodString>;
}, z.core.$strip>;
//# sourceMappingURL=notification.d.ts.map