import { z } from "zod";
export declare const ssoProvider: import("drizzle-orm/pg-core").PgTableWithColumns<{
    name: "sso_provider";
    schema: undefined;
    columns: {
        id: import("drizzle-orm/pg-core").PgColumn<{
            name: "id";
            tableName: "sso_provider";
            dataType: "string";
            columnType: "PgText";
            data: string;
            driverParam: string;
            notNull: true;
            hasDefault: false;
            isPrimaryKey: true;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        issuer: import("drizzle-orm/pg-core").PgColumn<{
            name: "issuer";
            tableName: "sso_provider";
            dataType: "string";
            columnType: "PgText";
            data: string;
            driverParam: string;
            notNull: true;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        oidcConfig: import("drizzle-orm/pg-core").PgColumn<{
            name: "oidc_config";
            tableName: "sso_provider";
            dataType: "string";
            columnType: "PgText";
            data: string;
            driverParam: string;
            notNull: false;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        samlConfig: import("drizzle-orm/pg-core").PgColumn<{
            name: "saml_config";
            tableName: "sso_provider";
            dataType: "string";
            columnType: "PgText";
            data: string;
            driverParam: string;
            notNull: false;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        providerId: import("drizzle-orm/pg-core").PgColumn<{
            name: "provider_id";
            tableName: "sso_provider";
            dataType: "string";
            columnType: "PgText";
            data: string;
            driverParam: string;
            notNull: true;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        userId: import("drizzle-orm/pg-core").PgColumn<{
            name: "user_id";
            tableName: "sso_provider";
            dataType: "string";
            columnType: "PgText";
            data: string;
            driverParam: string;
            notNull: false;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        organizationId: import("drizzle-orm/pg-core").PgColumn<{
            name: "organization_id";
            tableName: "sso_provider";
            dataType: "string";
            columnType: "PgText";
            data: string;
            driverParam: string;
            notNull: false;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        domain: import("drizzle-orm/pg-core").PgColumn<{
            name: "domain";
            tableName: "sso_provider";
            dataType: "string";
            columnType: "PgText";
            data: string;
            driverParam: string;
            notNull: true;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        createdAt: import("drizzle-orm/pg-core").PgColumn<{
            name: "created_at";
            tableName: "sso_provider";
            dataType: "date";
            columnType: "PgTimestamp";
            data: Date;
            driverParam: string;
            notNull: true;
            hasDefault: true;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: undefined;
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
    };
    dialect: "pg";
}>;
export declare const ssoProviderRelations: import("drizzle-orm").Relations<"sso_provider", {
    organization: import("drizzle-orm").One<"organization", false>;
    user: import("drizzle-orm").One<"user", false>;
}>;
export declare const ssoProviderBodySchema: z.ZodObject<{
    providerId: z.ZodString;
    issuer: z.ZodString;
    domains: z.ZodPipe<z.ZodArray<z.ZodString>, z.ZodTransform<string[], string[]>>;
    oidcConfig: z.ZodOptional<z.ZodObject<{
        clientId: z.ZodString;
        clientSecret: z.ZodString;
        authorizationEndpoint: z.ZodOptional<z.ZodString>;
        tokenEndpoint: z.ZodOptional<z.ZodString>;
        userInfoEndpoint: z.ZodOptional<z.ZodString>;
        tokenEndpointAuthentication: z.ZodOptional<z.ZodEnum<{
            client_secret_post: "client_secret_post";
            client_secret_basic: "client_secret_basic";
        }>>;
        jwksEndpoint: z.ZodOptional<z.ZodString>;
        discoveryEndpoint: z.ZodOptional<z.ZodString>;
        skipDiscovery: z.ZodOptional<z.ZodBoolean>;
        scopes: z.ZodOptional<z.ZodArray<z.ZodString>>;
        pkce: z.ZodOptional<z.ZodDefault<z.ZodBoolean>>;
        mapping: z.ZodOptional<z.ZodObject<{
            id: z.ZodString;
            email: z.ZodString;
            emailVerified: z.ZodOptional<z.ZodString>;
            name: z.ZodString;
            image: z.ZodOptional<z.ZodString>;
            extraFields: z.ZodOptional<z.ZodRecord<z.ZodString, z.ZodAny>>;
        }, z.core.$strip>>;
    }, z.core.$strip>>;
    samlConfig: z.ZodOptional<z.ZodObject<{
        entryPoint: z.ZodString;
        cert: z.ZodString;
        callbackUrl: z.ZodString;
        audience: z.ZodOptional<z.ZodString>;
        idpMetadata: z.ZodOptional<z.ZodObject<{
            metadata: z.ZodOptional<z.ZodString>;
            entityID: z.ZodOptional<z.ZodString>;
            cert: z.ZodOptional<z.ZodString>;
            privateKey: z.ZodOptional<z.ZodString>;
            privateKeyPass: z.ZodOptional<z.ZodString>;
            isAssertionEncrypted: z.ZodOptional<z.ZodBoolean>;
            encPrivateKey: z.ZodOptional<z.ZodString>;
            encPrivateKeyPass: z.ZodOptional<z.ZodString>;
            singleSignOnService: z.ZodOptional<z.ZodArray<z.ZodObject<{
                Binding: z.ZodString;
                Location: z.ZodString;
            }, z.core.$strip>>>;
        }, z.core.$strip>>;
        spMetadata: z.ZodObject<{
            metadata: z.ZodOptional<z.ZodString>;
            entityID: z.ZodOptional<z.ZodString>;
            binding: z.ZodOptional<z.ZodString>;
            privateKey: z.ZodOptional<z.ZodString>;
            privateKeyPass: z.ZodOptional<z.ZodString>;
            isAssertionEncrypted: z.ZodOptional<z.ZodBoolean>;
            encPrivateKey: z.ZodOptional<z.ZodString>;
            encPrivateKeyPass: z.ZodOptional<z.ZodString>;
        }, z.core.$strip>;
        wantAssertionsSigned: z.ZodOptional<z.ZodBoolean>;
        authnRequestsSigned: z.ZodOptional<z.ZodBoolean>;
        signatureAlgorithm: z.ZodOptional<z.ZodString>;
        digestAlgorithm: z.ZodOptional<z.ZodString>;
        identifierFormat: z.ZodOptional<z.ZodString>;
        privateKey: z.ZodOptional<z.ZodString>;
        decryptionPvk: z.ZodOptional<z.ZodString>;
        additionalParams: z.ZodOptional<z.ZodRecord<z.ZodString, z.ZodAny>>;
        mapping: z.ZodOptional<z.ZodObject<{
            id: z.ZodString;
            email: z.ZodString;
            emailVerified: z.ZodOptional<z.ZodString>;
            name: z.ZodString;
            firstName: z.ZodOptional<z.ZodString>;
            lastName: z.ZodOptional<z.ZodString>;
            extraFields: z.ZodOptional<z.ZodRecord<z.ZodString, z.ZodAny>>;
        }, z.core.$strip>>;
    }, z.core.$strip>>;
    organizationId: z.ZodOptional<z.ZodString>;
    overrideUserInfo: z.ZodOptional<z.ZodDefault<z.ZodBoolean>>;
}, z.core.$strip>;
//# sourceMappingURL=sso.d.ts.map