import { z } from "zod";
/**
 * This is an example of how to use the multi-project schema feature of Drizzle ORM. Use the same
 * database instance for multiple projects.
 *
 * @see https://orm.drizzle.team/docs/goodies#multi-project-schema
 */
export declare const user: import("drizzle-orm/pg-core").PgTableWithColumns<{
    name: "user";
    schema: undefined;
    columns: {
        id: import("drizzle-orm/pg-core").PgColumn<{
            name: "id";
            tableName: "user";
            dataType: "string";
            columnType: "PgText";
            data: string;
            driverParam: string;
            notNull: true;
            hasDefault: true;
            isPrimaryKey: true;
            isAutoincrement: false;
            hasRuntimeDefault: true;
            enumValues: [string, ...string[]];
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        firstName: import("drizzle-orm/pg-core").PgColumn<{
            name: "firstName";
            tableName: "user";
            dataType: "string";
            columnType: "PgText";
            data: string;
            driverParam: string;
            notNull: true;
            hasDefault: true;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        lastName: import("drizzle-orm/pg-core").PgColumn<{
            name: "lastName";
            tableName: "user";
            dataType: "string";
            columnType: "PgText";
            data: string;
            driverParam: string;
            notNull: true;
            hasDefault: true;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        isRegistered: import("drizzle-orm/pg-core").PgColumn<{
            name: "isRegistered";
            tableName: "user";
            dataType: "boolean";
            columnType: "PgBoolean";
            data: boolean;
            driverParam: boolean;
            notNull: true;
            hasDefault: true;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: undefined;
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        expirationDate: import("drizzle-orm/pg-core").PgColumn<{
            name: "expirationDate";
            tableName: "user";
            dataType: "string";
            columnType: "PgText";
            data: string;
            driverParam: string;
            notNull: true;
            hasDefault: true;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: true;
            enumValues: [string, ...string[]];
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        createdAt2: import("drizzle-orm/pg-core").PgColumn<{
            name: "createdAt";
            tableName: "user";
            dataType: "string";
            columnType: "PgText";
            data: string;
            driverParam: string;
            notNull: true;
            hasDefault: true;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: true;
            enumValues: [string, ...string[]];
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        createdAt: import("drizzle-orm/pg-core").PgColumn<{
            name: "created_at";
            tableName: "user";
            dataType: "date";
            columnType: "PgTimestamp";
            data: Date;
            driverParam: string;
            notNull: false;
            hasDefault: true;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: undefined;
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        twoFactorEnabled: import("drizzle-orm/pg-core").PgColumn<{
            name: "two_factor_enabled";
            tableName: "user";
            dataType: "boolean";
            columnType: "PgBoolean";
            data: boolean;
            driverParam: boolean;
            notNull: false;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: undefined;
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        email: import("drizzle-orm/pg-core").PgColumn<{
            name: "email";
            tableName: "user";
            dataType: "string";
            columnType: "PgText";
            data: string;
            driverParam: string;
            notNull: true;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        emailVerified: import("drizzle-orm/pg-core").PgColumn<{
            name: "email_verified";
            tableName: "user";
            dataType: "boolean";
            columnType: "PgBoolean";
            data: boolean;
            driverParam: boolean;
            notNull: true;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: undefined;
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        image: import("drizzle-orm/pg-core").PgColumn<{
            name: "image";
            tableName: "user";
            dataType: "string";
            columnType: "PgText";
            data: string;
            driverParam: string;
            notNull: false;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        banned: import("drizzle-orm/pg-core").PgColumn<{
            name: "banned";
            tableName: "user";
            dataType: "boolean";
            columnType: "PgBoolean";
            data: boolean;
            driverParam: boolean;
            notNull: false;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: undefined;
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        banReason: import("drizzle-orm/pg-core").PgColumn<{
            name: "ban_reason";
            tableName: "user";
            dataType: "string";
            columnType: "PgText";
            data: string;
            driverParam: string;
            notNull: false;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        banExpires: import("drizzle-orm/pg-core").PgColumn<{
            name: "ban_expires";
            tableName: "user";
            dataType: "date";
            columnType: "PgTimestamp";
            data: Date;
            driverParam: string;
            notNull: false;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: undefined;
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        updatedAt: import("drizzle-orm/pg-core").PgColumn<{
            name: "updated_at";
            tableName: "user";
            dataType: "date";
            columnType: "PgTimestamp";
            data: Date;
            driverParam: string;
            notNull: true;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: undefined;
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        role: import("drizzle-orm/pg-core").PgColumn<{
            name: "role";
            tableName: "user";
            dataType: "string";
            columnType: "PgText";
            data: string;
            driverParam: string;
            notNull: true;
            hasDefault: true;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        enablePaidFeatures: import("drizzle-orm/pg-core").PgColumn<{
            name: "enablePaidFeatures";
            tableName: "user";
            dataType: "boolean";
            columnType: "PgBoolean";
            data: boolean;
            driverParam: boolean;
            notNull: true;
            hasDefault: true;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: undefined;
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        allowImpersonation: import("drizzle-orm/pg-core").PgColumn<{
            name: "allowImpersonation";
            tableName: "user";
            dataType: "boolean";
            columnType: "PgBoolean";
            data: boolean;
            driverParam: boolean;
            notNull: true;
            hasDefault: true;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: undefined;
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        enableEnterpriseFeatures: import("drizzle-orm/pg-core").PgColumn<{
            name: "enableEnterpriseFeatures";
            tableName: "user";
            dataType: "boolean";
            columnType: "PgBoolean";
            data: boolean;
            driverParam: boolean;
            notNull: true;
            hasDefault: true;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: undefined;
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        licenseKey: import("drizzle-orm/pg-core").PgColumn<{
            name: "licenseKey";
            tableName: "user";
            dataType: "string";
            columnType: "PgText";
            data: string;
            driverParam: string;
            notNull: false;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        isValidEnterpriseLicense: import("drizzle-orm/pg-core").PgColumn<{
            name: "isValidEnterpriseLicense";
            tableName: "user";
            dataType: "boolean";
            columnType: "PgBoolean";
            data: boolean;
            driverParam: boolean;
            notNull: true;
            hasDefault: true;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: undefined;
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        stripeCustomerId: import("drizzle-orm/pg-core").PgColumn<{
            name: "stripeCustomerId";
            tableName: "user";
            dataType: "string";
            columnType: "PgText";
            data: string;
            driverParam: string;
            notNull: false;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        stripeSubscriptionId: import("drizzle-orm/pg-core").PgColumn<{
            name: "stripeSubscriptionId";
            tableName: "user";
            dataType: "string";
            columnType: "PgText";
            data: string;
            driverParam: string;
            notNull: false;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        serversQuantity: import("drizzle-orm/pg-core").PgColumn<{
            name: "serversQuantity";
            tableName: "user";
            dataType: "number";
            columnType: "PgInteger";
            data: number;
            driverParam: string | number;
            notNull: true;
            hasDefault: true;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: undefined;
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        sendInvoiceNotifications: import("drizzle-orm/pg-core").PgColumn<{
            name: "sendInvoiceNotifications";
            tableName: "user";
            dataType: "boolean";
            columnType: "PgBoolean";
            data: boolean;
            driverParam: boolean;
            notNull: true;
            hasDefault: true;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: undefined;
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        isEnterpriseCloud: import("drizzle-orm/pg-core").PgColumn<{
            name: "isEnterpriseCloud";
            tableName: "user";
            dataType: "boolean";
            columnType: "PgBoolean";
            data: boolean;
            driverParam: boolean;
            notNull: true;
            hasDefault: true;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: undefined;
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        trustedOrigins: import("drizzle-orm/pg-core").PgColumn<{
            name: "trustedOrigins";
            tableName: "user";
            dataType: "array";
            columnType: "PgArray";
            data: string[];
            driverParam: string | string[];
            notNull: false;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: import("drizzle-orm").Column<{
                name: "trustedOrigins";
                tableName: "user";
                dataType: "string";
                columnType: "PgText";
                data: string;
                driverParam: string;
                notNull: false;
                hasDefault: false;
                isPrimaryKey: false;
                isAutoincrement: false;
                hasRuntimeDefault: false;
                enumValues: [string, ...string[]];
                baseColumn: never;
                identity: undefined;
                generated: undefined;
            }, {}, {}>;
            identity: undefined;
            generated: undefined;
        }, {}, {
            baseBuilder: import("drizzle-orm/pg-core").PgColumnBuilder<{
                name: "trustedOrigins";
                dataType: "string";
                columnType: "PgText";
                data: string;
                enumValues: [string, ...string[]];
                driverParam: string;
            }, {}, {}, import("drizzle-orm").ColumnBuilderExtraConfig>;
            size: undefined;
        }>;
        bookmarkedTemplates: import("drizzle-orm/pg-core").PgColumn<{
            name: "bookmarkedTemplates";
            tableName: "user";
            dataType: "array";
            columnType: "PgArray";
            data: string[];
            driverParam: string | string[];
            notNull: false;
            hasDefault: true;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: import("drizzle-orm").Column<{
                name: "bookmarkedTemplates";
                tableName: "user";
                dataType: "string";
                columnType: "PgText";
                data: string;
                driverParam: string;
                notNull: false;
                hasDefault: false;
                isPrimaryKey: false;
                isAutoincrement: false;
                hasRuntimeDefault: false;
                enumValues: [string, ...string[]];
                baseColumn: never;
                identity: undefined;
                generated: undefined;
            }, {}, {}>;
            identity: undefined;
            generated: undefined;
        }, {}, {
            baseBuilder: import("drizzle-orm/pg-core").PgColumnBuilder<{
                name: "bookmarkedTemplates";
                dataType: "string";
                columnType: "PgText";
                data: string;
                enumValues: [string, ...string[]];
                driverParam: string;
            }, {}, {}, import("drizzle-orm").ColumnBuilderExtraConfig>;
            size: undefined;
        }>;
    };
    dialect: "pg";
}>;
export declare const usersRelations: import("drizzle-orm").Relations<"user", {
    account: import("drizzle-orm").One<"account", true>;
    organizations: import("drizzle-orm").Many<"organization">;
    projects: import("drizzle-orm").Many<"project">;
    apiKeys: import("drizzle-orm").Many<"apikey">;
    ssoProviders: import("drizzle-orm").Many<"sso_provider">;
    backups: import("drizzle-orm").Many<"backup">;
    schedules: import("drizzle-orm").Many<"schedule">;
}>;
export declare const apiCreateUserInvitation: z.ZodObject<{
    email: z.ZodString;
}, z.core.$strip>;
export declare const apiRemoveUser: z.ZodObject<{
    id: z.ZodNonOptional<z.ZodOptional<z.ZodString>>;
}, z.core.$strip>;
export declare const apiFindOneToken: z.ZodObject<{
    token: z.ZodString;
}, z.core.$strip>;
export declare const apiAssignPermissions: z.ZodObject<{
    id: z.ZodNonOptional<z.ZodOptional<z.ZodString>>;
    accessedProjects: z.ZodNonOptional<z.ZodOptional<z.ZodArray<z.ZodString>>>;
    accessedEnvironments: z.ZodNonOptional<z.ZodOptional<z.ZodArray<z.ZodString>>>;
    accessedServices: z.ZodNonOptional<z.ZodOptional<z.ZodArray<z.ZodString>>>;
    accessedGitProviders: z.ZodNonOptional<z.ZodOptional<z.ZodArray<z.ZodString>>>;
    accessedServers: z.ZodNonOptional<z.ZodOptional<z.ZodArray<z.ZodString>>>;
    canCreateProjects: z.ZodNonOptional<z.ZodOptional<z.ZodBoolean>>;
    canCreateServices: z.ZodNonOptional<z.ZodOptional<z.ZodBoolean>>;
    canDeleteProjects: z.ZodNonOptional<z.ZodOptional<z.ZodBoolean>>;
    canDeleteServices: z.ZodNonOptional<z.ZodOptional<z.ZodBoolean>>;
    canAccessToDocker: z.ZodNonOptional<z.ZodOptional<z.ZodBoolean>>;
    canAccessToTraefikFiles: z.ZodNonOptional<z.ZodOptional<z.ZodBoolean>>;
    canAccessToAPI: z.ZodNonOptional<z.ZodOptional<z.ZodBoolean>>;
    canAccessToSSHKeys: z.ZodNonOptional<z.ZodOptional<z.ZodBoolean>>;
    canAccessToGitProviders: z.ZodNonOptional<z.ZodOptional<z.ZodBoolean>>;
    canDeleteEnvironments: z.ZodNonOptional<z.ZodOptional<z.ZodBoolean>>;
    canCreateEnvironments: z.ZodNonOptional<z.ZodOptional<z.ZodBoolean>>;
}, z.core.$strip>;
export declare const apiFindOneUser: z.ZodObject<{
    id: z.ZodNonOptional<z.ZodOptional<z.ZodString>>;
}, z.core.$strip>;
export declare const apiFindOneUserByAuth: z.ZodObject<{}, z.core.$strip>;
export declare const apiTraefikConfig: z.ZodObject<{
    traefikConfig: z.ZodString;
}, z.core.$strip>;
export declare const apiModifyTraefikConfig: z.ZodObject<{
    path: z.ZodString;
    traefikConfig: z.ZodString;
    serverId: z.ZodOptional<z.ZodString>;
}, z.core.$strip>;
export declare const apiReadTraefikConfig: z.ZodObject<{
    path: z.ZodString;
    serverId: z.ZodOptional<z.ZodString>;
}, z.core.$strip>;
export declare const apiEnableDashboard: z.ZodObject<{
    enableDashboard: z.ZodOptional<z.ZodBoolean>;
    serverId: z.ZodOptional<z.ZodString>;
}, z.core.$strip>;
export declare const apiServerSchema: z.ZodOptional<z.ZodObject<{
    serverId: z.ZodOptional<z.ZodString>;
}, z.core.$strip>>;
export declare const apiReadStatsLogs: z.ZodObject<{
    page: z.ZodOptional<z.ZodObject<{
        pageIndex: z.ZodNumber;
        pageSize: z.ZodNumber;
    }, z.core.$strip>>;
    status: z.ZodOptional<z.ZodArray<z.ZodString>>;
    search: z.ZodOptional<z.ZodString>;
    sort: z.ZodOptional<z.ZodObject<{
        id: z.ZodString;
        desc: z.ZodBoolean;
    }, z.core.$strip>>;
    dateRange: z.ZodOptional<z.ZodObject<{
        start: z.ZodOptional<z.ZodString>;
        end: z.ZodOptional<z.ZodString>;
    }, z.core.$strip>>;
}, z.core.$strip>;
export declare const apiUpdateUser: z.ZodObject<{
    createdAt: z.ZodOptional<z.ZodOptional<z.ZodNullable<z.ZodDate>>>;
    id: z.ZodOptional<z.ZodOptional<z.ZodString>>;
    isRegistered: z.ZodOptional<z.ZodOptional<z.ZodOptional<z.ZodBoolean>>>;
    expirationDate: z.ZodOptional<z.ZodOptional<z.ZodString>>;
    createdAt2: z.ZodOptional<z.ZodOptional<z.ZodString>>;
    twoFactorEnabled: z.ZodOptional<z.ZodOptional<z.ZodNullable<z.ZodBoolean>>>;
    emailVerified: z.ZodOptional<z.ZodBoolean>;
    image: z.ZodOptional<z.ZodOptional<z.ZodNullable<z.ZodString>>>;
    banned: z.ZodOptional<z.ZodOptional<z.ZodNullable<z.ZodBoolean>>>;
    banReason: z.ZodOptional<z.ZodOptional<z.ZodNullable<z.ZodString>>>;
    banExpires: z.ZodOptional<z.ZodOptional<z.ZodNullable<z.ZodDate>>>;
    updatedAt: z.ZodOptional<z.ZodDate>;
    enablePaidFeatures: z.ZodOptional<z.ZodOptional<z.ZodBoolean>>;
    allowImpersonation: z.ZodOptional<z.ZodOptional<z.ZodBoolean>>;
    enableEnterpriseFeatures: z.ZodOptional<z.ZodOptional<z.ZodBoolean>>;
    licenseKey: z.ZodOptional<z.ZodOptional<z.ZodNullable<z.ZodString>>>;
    stripeCustomerId: z.ZodOptional<z.ZodOptional<z.ZodNullable<z.ZodString>>>;
    stripeSubscriptionId: z.ZodOptional<z.ZodOptional<z.ZodNullable<z.ZodString>>>;
    serversQuantity: z.ZodOptional<z.ZodOptional<z.ZodNumber>>;
    sendInvoiceNotifications: z.ZodOptional<z.ZodOptional<z.ZodBoolean>>;
    email: z.ZodOptional<z.ZodString>;
    password: z.ZodOptional<z.ZodString>;
    currentPassword: z.ZodOptional<z.ZodString>;
    firstName: z.ZodOptional<z.ZodString>;
    lastName: z.ZodOptional<z.ZodString>;
}, z.core.$strip>;
//# sourceMappingURL=user.d.ts.map