import { z } from "zod";
export declare const volumeBackups: import("drizzle-orm/pg-core").PgTableWithColumns<{
    name: "volume_backup";
    schema: undefined;
    columns: {
        volumeBackupId: import("drizzle-orm/pg-core").PgColumn<{
            name: "volumeBackupId";
            tableName: "volume_backup";
            dataType: "string";
            columnType: "PgText";
            data: string;
            driverParam: string;
            notNull: true;
            hasDefault: true;
            isPrimaryKey: true;
            isAutoincrement: false;
            hasRuntimeDefault: true;
            enumValues: [string, ...string[]];
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        name: import("drizzle-orm/pg-core").PgColumn<{
            name: "name";
            tableName: "volume_backup";
            dataType: "string";
            columnType: "PgText";
            data: string;
            driverParam: string;
            notNull: true;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        volumeName: import("drizzle-orm/pg-core").PgColumn<{
            name: "volumeName";
            tableName: "volume_backup";
            dataType: "string";
            columnType: "PgText";
            data: string;
            driverParam: string;
            notNull: true;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        prefix: import("drizzle-orm/pg-core").PgColumn<{
            name: "prefix";
            tableName: "volume_backup";
            dataType: "string";
            columnType: "PgText";
            data: string;
            driverParam: string;
            notNull: true;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        serviceType: import("drizzle-orm/pg-core").PgColumn<{
            name: "serviceType";
            tableName: "volume_backup";
            dataType: "string";
            columnType: "PgEnumColumn";
            data: "application" | "compose" | "mysql" | "libsql" | "mariadb" | "mongo" | "postgres" | "redis";
            driverParam: string;
            notNull: true;
            hasDefault: true;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: ["application", "postgres", "mysql", "mariadb", "mongo", "redis", "compose", "libsql"];
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        appName: import("drizzle-orm/pg-core").PgColumn<{
            name: "appName";
            tableName: "volume_backup";
            dataType: "string";
            columnType: "PgText";
            data: string;
            driverParam: string;
            notNull: true;
            hasDefault: true;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: true;
            enumValues: [string, ...string[]];
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        serviceName: import("drizzle-orm/pg-core").PgColumn<{
            name: "serviceName";
            tableName: "volume_backup";
            dataType: "string";
            columnType: "PgText";
            data: string;
            driverParam: string;
            notNull: false;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        turnOff: import("drizzle-orm/pg-core").PgColumn<{
            name: "turnOff";
            tableName: "volume_backup";
            dataType: "boolean";
            columnType: "PgBoolean";
            data: boolean;
            driverParam: boolean;
            notNull: true;
            hasDefault: true;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: undefined;
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        cronExpression: import("drizzle-orm/pg-core").PgColumn<{
            name: "cronExpression";
            tableName: "volume_backup";
            dataType: "string";
            columnType: "PgText";
            data: string;
            driverParam: string;
            notNull: true;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        keepLatestCount: import("drizzle-orm/pg-core").PgColumn<{
            name: "keepLatestCount";
            tableName: "volume_backup";
            dataType: "number";
            columnType: "PgInteger";
            data: number;
            driverParam: string | number;
            notNull: false;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: undefined;
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        enabled: import("drizzle-orm/pg-core").PgColumn<{
            name: "enabled";
            tableName: "volume_backup";
            dataType: "boolean";
            columnType: "PgBoolean";
            data: boolean;
            driverParam: boolean;
            notNull: false;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: undefined;
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        applicationId: import("drizzle-orm/pg-core").PgColumn<{
            name: "applicationId";
            tableName: "volume_backup";
            dataType: "string";
            columnType: "PgText";
            data: string;
            driverParam: string;
            notNull: false;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        postgresId: import("drizzle-orm/pg-core").PgColumn<{
            name: "postgresId";
            tableName: "volume_backup";
            dataType: "string";
            columnType: "PgText";
            data: string;
            driverParam: string;
            notNull: false;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        mariadbId: import("drizzle-orm/pg-core").PgColumn<{
            name: "mariadbId";
            tableName: "volume_backup";
            dataType: "string";
            columnType: "PgText";
            data: string;
            driverParam: string;
            notNull: false;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        mongoId: import("drizzle-orm/pg-core").PgColumn<{
            name: "mongoId";
            tableName: "volume_backup";
            dataType: "string";
            columnType: "PgText";
            data: string;
            driverParam: string;
            notNull: false;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        mysqlId: import("drizzle-orm/pg-core").PgColumn<{
            name: "mysqlId";
            tableName: "volume_backup";
            dataType: "string";
            columnType: "PgText";
            data: string;
            driverParam: string;
            notNull: false;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        redisId: import("drizzle-orm/pg-core").PgColumn<{
            name: "redisId";
            tableName: "volume_backup";
            dataType: "string";
            columnType: "PgText";
            data: string;
            driverParam: string;
            notNull: false;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        libsqlId: import("drizzle-orm/pg-core").PgColumn<{
            name: "libsqlId";
            tableName: "volume_backup";
            dataType: "string";
            columnType: "PgText";
            data: string;
            driverParam: string;
            notNull: false;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        composeId: import("drizzle-orm/pg-core").PgColumn<{
            name: "composeId";
            tableName: "volume_backup";
            dataType: "string";
            columnType: "PgText";
            data: string;
            driverParam: string;
            notNull: false;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        createdAt: import("drizzle-orm/pg-core").PgColumn<{
            name: "createdAt";
            tableName: "volume_backup";
            dataType: "string";
            columnType: "PgText";
            data: string;
            driverParam: string;
            notNull: true;
            hasDefault: true;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: true;
            enumValues: [string, ...string[]];
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        destinationId: import("drizzle-orm/pg-core").PgColumn<{
            name: "destinationId";
            tableName: "volume_backup";
            dataType: "string";
            columnType: "PgText";
            data: string;
            driverParam: string;
            notNull: true;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
    };
    dialect: "pg";
}>;
export type VolumeBackup = typeof volumeBackups.$inferSelect;
export declare const volumeBackupsRelations: import("drizzle-orm").Relations<"volume_backup", {
    application: import("drizzle-orm").One<"application", false>;
    postgres: import("drizzle-orm").One<"postgres", false>;
    mariadb: import("drizzle-orm").One<"mariadb", false>;
    mongo: import("drizzle-orm").One<"mongo", false>;
    mysql: import("drizzle-orm").One<"mysql", false>;
    redis: import("drizzle-orm").One<"redis", false>;
    libsql: import("drizzle-orm").One<"libsql", false>;
    compose: import("drizzle-orm").One<"compose", false>;
    destination: import("drizzle-orm").One<"destination", true>;
    deployments: import("drizzle-orm").Many<"deployment">;
}>;
export declare const createVolumeBackupSchema: z.ZodObject<{
    name: z.ZodString;
    createdAt: z.ZodOptional<z.ZodString>;
    applicationId: z.ZodOptional<z.ZodNullable<z.ZodString>>;
    serviceName: z.ZodOptional<z.ZodNullable<z.ZodString>>;
    composeId: z.ZodOptional<z.ZodNullable<z.ZodString>>;
    appName: z.ZodOptional<z.ZodString>;
    enabled: z.ZodOptional<z.ZodNullable<z.ZodBoolean>>;
    serviceType: z.ZodOptional<z.ZodEnum<["application", "postgres", "mysql", "mariadb", "mongo", "redis", "compose", "libsql"]>>;
    mysqlId: z.ZodOptional<z.ZodNullable<z.ZodString>>;
    prefix: z.ZodString;
    volumeName: z.ZodString;
    libsqlId: z.ZodOptional<z.ZodNullable<z.ZodString>>;
    mariadbId: z.ZodOptional<z.ZodNullable<z.ZodString>>;
    mongoId: z.ZodOptional<z.ZodNullable<z.ZodString>>;
    postgresId: z.ZodOptional<z.ZodNullable<z.ZodString>>;
    redisId: z.ZodOptional<z.ZodNullable<z.ZodString>>;
    destinationId: z.ZodString;
    keepLatestCount: z.ZodOptional<z.ZodNullable<z.ZodNumber>>;
    cronExpression: z.ZodString;
    turnOff: z.ZodOptional<z.ZodBoolean>;
}, z.core.$strip>;
export declare const updateVolumeBackupSchema: z.ZodObject<{
    name: z.ZodString;
    createdAt: z.ZodOptional<z.ZodString>;
    applicationId: z.ZodOptional<z.ZodNullable<z.ZodString>>;
    serviceName: z.ZodOptional<z.ZodNullable<z.ZodString>>;
    composeId: z.ZodOptional<z.ZodNullable<z.ZodString>>;
    appName: z.ZodOptional<z.ZodString>;
    enabled: z.ZodOptional<z.ZodNullable<z.ZodBoolean>>;
    serviceType: z.ZodOptional<z.ZodEnum<["application", "postgres", "mysql", "mariadb", "mongo", "redis", "compose", "libsql"]>>;
    mysqlId: z.ZodOptional<z.ZodNullable<z.ZodString>>;
    prefix: z.ZodString;
    volumeName: z.ZodString;
    libsqlId: z.ZodOptional<z.ZodNullable<z.ZodString>>;
    mariadbId: z.ZodOptional<z.ZodNullable<z.ZodString>>;
    mongoId: z.ZodOptional<z.ZodNullable<z.ZodString>>;
    postgresId: z.ZodOptional<z.ZodNullable<z.ZodString>>;
    redisId: z.ZodOptional<z.ZodNullable<z.ZodString>>;
    destinationId: z.ZodString;
    keepLatestCount: z.ZodOptional<z.ZodNullable<z.ZodNumber>>;
    cronExpression: z.ZodString;
    turnOff: z.ZodOptional<z.ZodBoolean>;
    volumeBackupId: z.ZodString;
}, z.core.$strip>;
export declare const apiFindOneVolumeBackup: z.ZodObject<{
    volumeBackupId: z.ZodString;
}, z.core.$strip>;
//# sourceMappingURL=volume-backups.d.ts.map